/**
 * Do not edit directly
 * Generated on Sun, 27 Oct 2024 04:05:11 GMT
 */


module.exports = {
  'leaf-font-families-rubik': '"Rubik", sans-serif',
  'leaf-color-content-default': '#515761',
  'leaf-color-content-subtle': '#747981',
  'leaf-color-content-disabled': '#979aa0',
  'leaf-color-content-link-disabled': '#979aa0',
  'leaf-color-content-inverse-link-disabled': '#edeeef',
  'leaf-color-content-knockout': '#ffffff',
  'leaf-color-content-brand-knockout': '#addbf0',
  'leaf-color-content-brand': '#005e9c',
  'leaf-color-content-brand-strong': '#14568d',
  'leaf-color-content-success': '#256700',
  'leaf-color-content-success-icon': '#3c8700',
  'leaf-color-content-error': '#e4292f',
  'leaf-color-content-error-icon': '#e4292f',
  'leaf-color-content-warning-icon': '#fdb81e',
  'leaf-color-content-info-icon': '#073b64',
  'leaf-color-content-attention-icon': '#982393',
  'leaf-color-content-link': '#14568d',
  'leaf-color-content-inverse-link': '#ffffff',
  'leaf-color-content-link-hover': '#073b64',
  'leaf-color-content-inverse-link-hover': '#addbf0',
  'leaf-color-content-link-focus': '#ffffff',
  'leaf-color-content-inverse-link-focus': '#000000',
  'leaf-color-content-link-visited': '#073b64',
  'leaf-color-content-inverse-link-visited': '#d0dde8',
  'leaf-color-content-link-active': '#073b64',
  'leaf-color-content-inverse-link-active': '#addbf0',
  'leaf-color-button-primary-danger-bg': '#979aa0',
  'leaf-color-button-primary-danger-inverse-bg': '#ffffff',
  'leaf-color-button-primary-danger-bg-hover': '#1f232a',
  'leaf-color-button-primary-danger-inverse-bg-hover': '#eff8fc',
  'leaf-color-button-primary-danger-bg-active': '#1f232a',
  'leaf-color-button-primary-danger-inverse-bg-active': '#def1f9',
  'leaf-color-button-primary-danger-bg-disabled': '#dcdddf',
  'leaf-color-button-primary-danger-inverse-bg-disabled': '#979aa0',
  'leaf-color-button-primary-danger-content': '#ffffff',
  'leaf-color-button-primary-danger-inverse-content': '#000000',
  'leaf-color-button-primary-danger-content-hover': '#ffffff',
  'leaf-color-button-primary-danger-inverse-content-hover': '#000000',
  'leaf-color-button-primary-danger-content-active': '#ffffff',
  'leaf-color-button-primary-danger-inverse-content-active': '#000000',
  'leaf-color-button-primary-danger-content-disabled': '#ffffff',
  'leaf-color-button-primary-danger-inverse-content-disabled': '#000000',
  'leaf-color-button-primary-danger-border': '#2f343d',
  'leaf-color-button-primary-danger-inverse-border': '#ffffff',
  'leaf-color-button-primary-danger-border-hover': '#1f232a',
  'leaf-color-button-primary-danger-inverse-border-hover': '#eff8fc',
  'leaf-color-button-primary-danger-border-active': '#1f232a',
  'leaf-color-button-primary-danger-inverse-border-active': '#edeeef',
  'leaf-color-button-primary-danger-border-disabled': '#979aa0',
  'leaf-color-button-primary-danger-inverse-border-disabled': '#979aa0',
  'leaf-color-button-primary-danger-outline': '#000000',
  'leaf-color-button-primary-danger-inverse-outline': '#ffffff',
  'leaf-color-button-primary-bg': '#14568d',
  'leaf-color-button-primary-inverse-bg': '#ffffff',
  'leaf-color-button-primary-bg-hover': '#073b64',
  'leaf-color-button-primary-inverse-bg-hover': '#eff8fc',
  'leaf-color-button-primary-bg-active': '#073b64',
  'leaf-color-button-primary-inverse-bg-active': '#def1f9',
  'leaf-color-button-primary-bg-disabled': '#dcdddf',
  'leaf-color-button-primary-inverse-bg-disabled': '#edeeef',
  'leaf-color-button-primary-border': '#14568d',
  'leaf-color-button-primary-inverse-border': '#ffffff',
  'leaf-color-button-primary-border-hover': '#073b64',
  'leaf-color-button-primary-inverse-border-hover': '#eff8fc',
  'leaf-color-button-primary-border-active': '#073b64',
  'leaf-color-button-primary-inverse-border-active': '#def1f9',
  'leaf-color-button-primary-border-disabled': '#dcdddf',
  'leaf-color-button-primary-inverse-border-disabled': '#edeeef',
  'leaf-color-button-primary-content': '#ffffff',
  'leaf-color-button-primary-inverse-content': '#073b64',
  'leaf-color-button-primary-content-hover': '#ffffff',
  'leaf-color-button-primary-inverse-content-hover': '#073b64',
  'leaf-color-button-primary-content-active': '#ffffff',
  'leaf-color-button-primary-inverse-content-active': '#073b64',
  'leaf-color-button-primary-content-disabled': '#979aa0',
  'leaf-color-button-primary-inverse-content-disabled': '#979aa0',
  'leaf-color-button-primary-outline': '#073b64',
  'leaf-color-button-primary-inverse-outline': '#eff8fc',
  'leaf-color-button-secondary-neutral-bg': 'rgba(#000000,0.0)',
  'leaf-color-button-secondary-neutral-inverse-bg': 'rgba(#000000,0.0)',
  'leaf-color-button-secondary-neutral-content': '#1f232a',
  'leaf-color-button-secondary-neutral-inverse-content': '#ffffff',
  'leaf-color-button-secondary-neutral-border': '#1f232a',
  'leaf-color-button-secondary-neutral-inverse-border': '#ffffff',
  'leaf-color-button-secondary-neutral-bg-hover': 'rgba(#000000,0.08)',
  'leaf-color-button-secondary-neutral-inverse-bg-hover': 'rgba(#000000,0.25)',
  'leaf-color-button-secondary-neutral-content-hover': '#1f232a',
  'leaf-color-button-secondary-neutral-inverse-content-hover': '#ffffff',
  'leaf-color-button-secondary-neutral-border-hover': '#1f232a',
  'leaf-color-button-secondary-neutral-inverse-border-hover': '#ffffff',
  'leaf-color-button-secondary-neutral-border-active': '#1f232a',
  'leaf-color-button-secondary-neutral-inverse-border-active': '#ffffff',
  'leaf-color-button-secondary-neutral-bg-active': 'rgba(#000000,0.25)',
  'leaf-color-button-secondary-neutral-inverse-bg-active': '#979aa0',
  'leaf-color-button-secondary-neutral-content-active': '#1f232a',
  'leaf-color-button-secondary-neutral-inverse-content-active': '#ffffff',
  'leaf-color-button-secondary-neutral-bg-disabled': '#f8f8f9',
  'leaf-color-button-secondary-neutral-inverse-bg-disabled': '#b9bcc0',
  'leaf-color-button-secondary-neutral-border-disabled': '#f8f8f9',
  'leaf-color-button-secondary-neutral-inverse-border-disabled': '#b9bcc0',
  'leaf-color-button-secondary-neutral-content-disabled': '#979aa0',
  'leaf-color-button-secondary-neutral-inverse-content-disabled': '#515761',
  'leaf-color-button-secondary-neutral-outline': '#1f232a',
  'leaf-color-button-secondary-neutral-inverse-outline': '#ffffff',
  'leaf-color-button-secondary-danger-bg': 'rgba(#000000,0.0)',
  'leaf-color-button-secondary-danger-inverse-bg': 'rgba(#000000,0.0)',
  'leaf-color-button-secondary-danger-bg-hover': '#2f343d',
  'leaf-color-button-secondary-danger-inverse-bg-hover': '#f8f8f9',
  'leaf-color-button-secondary-danger-bg-active': '#1f232a',
  'leaf-color-button-secondary-danger-inverse-bg-active': '#edeeef',
  'leaf-color-button-secondary-danger-bg-disabled': '#b9bcc0',
  'leaf-color-button-secondary-danger-inverse-bg-disabled': '#b9bcc0',
  'leaf-color-button-secondary-danger-content': '#ffffff',
  'leaf-color-button-secondary-danger-inverse-content': '#1f232a',
  'leaf-color-button-secondary-danger-content-hover': '#ffffff',
  'leaf-color-button-secondary-danger-inverse-content-hover': '#000000',
  'leaf-color-button-secondary-danger-content-active': '#ffffff',
  'leaf-color-button-secondary-danger-inverse-content-active': '#000000',
  'leaf-color-button-secondary-danger-content-disabled': '#ffffff',
  'leaf-color-button-secondary-danger-inverse-content-disabled': '#1f232a',
  'leaf-color-button-secondary-danger-border': '#2f343d',
  'leaf-color-button-secondary-danger-inverse-border': '#ffffff',
  'leaf-color-button-secondary-danger-border-hover': '#2f343d',
  'leaf-color-button-secondary-danger-inverse-border-hover': '#f8f8f9',
  'leaf-color-button-secondary-danger-border-active': '#1f232a',
  'leaf-color-button-secondary-danger-inverse-border-active': '#edeeef',
  'leaf-color-button-secondary-danger-border-disabled': '#979aa0',
  'leaf-color-button-secondary-danger-inverse-border-disabled': '#b9bcc0',
  'leaf-color-button-secondary-danger-outline': '#000000',
  'leaf-color-button-secondary-danger-inverse-outline': '#ffffff',
  'leaf-color-button-secondary-bg': '#ffffff',
  'leaf-color-button-secondary-inverse-bg': '#ffffff',
  'leaf-color-button-secondary-bg-hover': '#ffffff',
  'leaf-color-button-secondary-inverse-bg-hover': '#ffffff',
  'leaf-color-button-secondary-bg-active': '#ffffff',
  'leaf-color-button-secondary-inverse-bg-active': '#ffffff',
  'leaf-color-button-secondary-bg-disabled': '#dcdddf',
  'leaf-color-button-secondary-inverse-bg-disabled': '#dcdddf',
  'leaf-color-button-secondary-border': '#14568d',
  'leaf-color-button-secondary-inverse-border': '#14568d',
  'leaf-color-button-secondary-border-hover': '#073b64',
  'leaf-color-button-secondary-inverse-border-hover': '#073b64',
  'leaf-color-button-secondary-border-active': '#073b64',
  'leaf-color-button-secondary-inverse-border-active': '#073b64',
  'leaf-color-button-secondary-border-disabled': '#dcdddf',
  'leaf-color-button-secondary-inverse-border-disabled': '#dcdddf',
  'leaf-color-button-secondary-content': '#14568d',
  'leaf-color-button-secondary-inverse-content': '#14568d',
  'leaf-color-button-secondary-content-hover': '#073b64',
  'leaf-color-button-secondary-inverse-content-hover': '#073b64',
  'leaf-color-button-secondary-content-active': '#073b64',
  'leaf-color-button-secondary-inverse-content-active': '#073b64',
  'leaf-color-button-secondary-content-disabled': '#979aa0',
  'leaf-color-button-secondary-inverse-content-disabled': '#979aa0',
  'leaf-color-button-secondary-outline': '#073b64',
  'leaf-color-button-secondary-inverse-outline': '#073b64',
  'leaf-color-button-tertiary-neutral-bg': 'rgba(#000000,0.0)',
  'leaf-color-button-tertiary-neutral-inverse-bg': 'rgba(#000000,0.0)',
  'leaf-color-button-tertiary-neutral-content': '#1f232a',
  'leaf-color-button-tertiary-neutral-inverse-content': '#ffffff',
  'leaf-color-button-tertiary-neutral-border': 'rgba(#000000,0.0)',
  'leaf-color-button-tertiary-neutral-inverse-border': 'rgba(#000000,0.0)',
  'leaf-color-button-tertiary-neutral-bg-hover': 'rgba(#000000,0.0)',
  'leaf-color-button-tertiary-neutral-inverse-bg-hover': 'rgba(#000000,0.0)',
  'leaf-color-button-tertiary-neutral-content-hover': '#1f232a',
  'leaf-color-button-tertiary-neutral-inverse-content-hover': '#ffffff',
  'leaf-color-button-tertiary-neutral-border-hover': '#1f232a',
  'leaf-color-button-tertiary-neutral-inverse-border-hover': '#ffffff',
  'leaf-color-button-tertiary-neutral-border-active': '#1f232a',
  'leaf-color-button-tertiary-neutral-inverse-border-active': '#ffffff',
  'leaf-color-button-tertiary-neutral-bg-active': 'rgba(#000000,0.0)',
  'leaf-color-button-tertiary-neutral-inverse-bg-active': 'rgba(#000000,0.0)',
  'leaf-color-button-tertiary-neutral-content-active': '#1f232a',
  'leaf-color-button-tertiary-neutral-inverse-content-active': '#ffffff',
  'leaf-color-button-tertiary-neutral-bg-disabled': 'rgba(#000000,0.0)',
  'leaf-color-button-tertiary-neutral-inverse-bg-disabled': 'rgba(#000000,0.0)',
  'leaf-color-button-tertiary-neutral-border-disabled': 'rgba(#000000,0.0)',
  'leaf-color-button-tertiary-neutral-inverse-border-disabled': 'rgba(#000000,0.0)',
  'leaf-color-button-tertiary-neutral-content-disabled': '#979aa0',
  'leaf-color-button-tertiary-neutral-inverse-content-disabled': '#515761',
  'leaf-color-button-tertiary-neutral-outline': '#1f232a',
  'leaf-color-button-tertiary-neutral-inverse-outline': '#ffffff',
  'leaf-color-button-tertiary-danger-bg': 'rgba(#000000,0.0)',
  'leaf-color-button-tertiary-danger-inverse-bg': 'rgba(#000000,0.0)',
  'leaf-color-button-tertiary-danger-bg-hover': '#2f343d',
  'leaf-color-button-tertiary-danger-inverse-bg-hover': '#f8f8f9',
  'leaf-color-button-tertiary-danger-bg-active': '#1f232a',
  'leaf-color-button-tertiary-danger-inverse-bg-active': '#edeeef',
  'leaf-color-button-tertiary-danger-bg-disabled': '#b9bcc0',
  'leaf-color-button-tertiary-danger-inverse-bg-disabled': '#b9bcc0',
  'leaf-color-button-tertiary-danger-content': '#ffffff',
  'leaf-color-button-tertiary-danger-inverse-content': '#000000',
  'leaf-color-button-tertiary-danger-content-hover': '#ffffff',
  'leaf-color-button-tertiary-danger-inverse-content-hover': '#000000',
  'leaf-color-button-tertiary-danger-content-active': '#ffffff',
  'leaf-color-button-tertiary-danger-inverse-content-active': '#000000',
  'leaf-color-button-tertiary-danger-content-disabled': '#ffffff',
  'leaf-color-button-tertiary-danger-inverse-content-disabled': '#000000',
  'leaf-color-button-tertiary-danger-border': 'rgba(#000000,0.0)',
  'leaf-color-button-tertiary-danger-inverse-border': 'rgba(#000000,0.0)',
  'leaf-color-button-tertiary-danger-border-hover': '#1f232a',
  'leaf-color-button-tertiary-danger-inverse-border-hover': '#f8f8f9',
  'leaf-color-button-tertiary-danger-border-active': '#1f232a',
  'leaf-color-button-tertiary-danger-inverse-border-active': '#edeeef',
  'leaf-color-button-tertiary-danger-border-disabled': '#b9bcc0',
  'leaf-color-button-tertiary-danger-inverse-border-disabled': '#b9bcc0',
  'leaf-color-button-tertiary-danger-outline': '#000000',
  'leaf-color-button-tertiary-danger-inverse-outline': '#ffffff',
  'leaf-color-button-tertiary-bg': 'rgba(#000000,0.0)',
  'leaf-color-button-tertiary-inverse-bg': 'rgba(#000000,0.0)',
  'leaf-color-button-tertiary-bg-hover': 'rgba(#000000,0.0)',
  'leaf-color-button-tertiary-inverse-bg-hover': 'rgba(#000000,0.0)',
  'leaf-color-button-tertiary-bg-active': 'rgba(#000000,0.0)',
  'leaf-color-button-tertiary-inverse-bg-active': 'rgba(#000000,0.0)',
  'leaf-color-button-tertiary-bg-disabled': 'rgba(#000000,0.0)',
  'leaf-color-button-tertiary-inverse-bg-disabled': 'rgba(#000000,0.0)',
  'leaf-color-button-tertiary-border': 'rgba(#000000,0.0)',
  'leaf-color-button-tertiary-inverse-border': 'rgba(#000000,0.0)',
  'leaf-color-button-tertiary-border-hover': 'rgba(#000000,0.0)',
  'leaf-color-button-tertiary-inverse-border-hover': 'rgba(#000000,0.0)',
  'leaf-color-button-tertiary-border-active': 'rgba(#000000,0.0)',
  'leaf-color-button-tertiary-inverse-border-active': 'rgba(#000000,0.0)',
  'leaf-color-button-tertiary-border-disabled': 'rgba(#000000,0.0)',
  'leaf-color-button-tertiary-inverse-border-disabled': 'rgba(#000000,0.0)',
  'leaf-color-button-tertiary-content': '#14568d',
  'leaf-color-button-tertiary-inverse-content': '#14568d',
  'leaf-color-button-tertiary-content-hover': '#073b64',
  'leaf-color-button-tertiary-inverse-content-hover': '#073b64',
  'leaf-color-button-tertiary-content-active': '#073b64',
  'leaf-color-button-tertiary-inverse-content-active': '#073b64',
  'leaf-color-button-tertiary-content-disabled': '#979aa0',
  'leaf-color-button-tertiary-inverse-content-disabled': '#979aa0',
  'leaf-color-button-tertiary-outline': '#073b64',
  'leaf-color-button-tertiary-inverse-outline': '#073b64',
  'leaf-button-padding-vertical-small': 8,
  'leaf-button-padding-vertical-medium': 8,
  'leaf-button-padding-vertical-large': 8,
  'leaf-button-padding-vertical-icon-only': 8,
  'leaf-button-padding-vertical-small-icon-only': 8,
  'leaf-button-padding-vertical-medium-icon-only': 16,
  'leaf-button-padding-vertical-large-icon-only': 16,
  'leaf-button-padding-horizontal-small': 16,
  'leaf-button-padding-horizontal-medium': 24,
  'leaf-button-padding-horizontal-large': 24,
  'leaf-button-padding-horizontal-icon-only': 8,
  'leaf-button-padding-horizontal-small-icon-only': 8,
  'leaf-button-padding-horizontal-medium-icon-only': 16,
  'leaf-button-padding-horizontal-large-icon-only': 16,
  'leaf-paragraph-spacing-0': 0,
  'leaf-text-case-none': 'none',
  'leaf-text-case-uppercase': 'uppercase',
  'leaf-text-decoration-none': 'none',
  'leaf-text-decoration-underline': 'underline',
  'leaf-paragraph-indent-0': 0,
  'leaf-border-radius-small': 4,
  'leaf-border-radius-default': 4,
  'leaf-border-radius-large': 24,
  'leaf-border-radius-round': 900,
  'leaf-border-radius-button': 4,
  'leaf-border-radius-tabs': 4,
  'leaf-border-radius-badge': 16,
  'leaf-border-radius-container': 0,
  'leaf-border-radius-field': 4,
  'leaf-border-radius-field-brand': 4,
  'leaf-border-radius-brand': 4,
  'leaf-border-radius-none': 0,
  'leaf-color-bg-default': '#ffffff',
  'leaf-color-bg-default-hover': '#def1f9',
  'leaf-color-bg-default-active': '#bde2f3',
  'leaf-color-bg-subtle': '#f8f8f9',
  'leaf-color-bg-moderate': '#747981',
  'leaf-color-bg-inverse-moderate': '#b9bcc0',
  'leaf-color-bg-strong': '#515761',
  'leaf-color-bg-disabled': '#dcdddf',
  'leaf-color-bg-brand': '#eff8fc',
  'leaf-color-bg-brand-strong': '#207BBF',
  'leaf-color-bg-brand-hover': '#bde2f3',
  'leaf-color-bg-brand-active': '#91cbe9',
  'leaf-color-bg-brand-strong-hover': '#073b64',
  'leaf-color-bg-brand-strong-active': '#073b64',
  'leaf-color-bg-success': '#f1f6ed',
  'leaf-color-bg-error': '#fdf0f0',
  'leaf-color-bg-warning': '#fffaef',
  'leaf-color-bg-info': '#edf8fd',
  'leaf-color-bg-attention': '#fff6ff',
  'leaf-color-bg-success-strong': '#3c8700',
  'leaf-color-bg-error-strong': '#df2d2a',
  'leaf-color-bg-warning-strong': '#fdb81e',
  'leaf-color-bg-info-strong': '#073b64',
  'leaf-color-bg-attention-strong': '#982393',
  'leaf-color-bg-opacity-transparent': 'rgba(#000000,0.0)',
  'leaf-color-bg-opacity-default': 'rgba(#000000,0.65)',
  'leaf-color-bg-brand-xstrong': '#14568d',
  'leaf-color-bg-brand-xstrong-hover': '#073b64',
  'leaf-color-bg-brand-xstrong-active': '#073b64',
  'leaf-color-bg-active': '#073b64',
  'leaf-color-bg-inverse-active': '#ffffff',
  'leaf-color-border-default': '#b9bcc0',
  'leaf-color-border-strong': '#515761',
  'leaf-color-border-knockout': '#ffffff',
  'leaf-color-border-disabled': '#b9bcc0',
  'leaf-color-border-brand': '#009bdf',
  'leaf-color-border-brand-subtle': '#99d7f2',
  'leaf-color-border-brand-strong': '#14568d',
  'leaf-color-border-success': '#256700',
  'leaf-color-border-error': '#df2d2a',
  'leaf-color-border-warning': '#515761',
  'leaf-color-border-info': '#14568d',
  'leaf-color-border-attention': '#982393',
  'leaf-color-border-transparent': '#50505000',
  'leaf-color-border-active-outline': '#14568d',
  'leaf-body-xlarge': {
    fontFamily: '"Rubik", sans-serif',
    fontWeight: '400',
    fontSize: 24,
    letterSpacing: 0,
    lineHeight: 28.8,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-body-xlarge-strong': {
    fontFamily: '"Rubik", sans-serif',
    fontWeight: '500',
    fontSize: 24,
    letterSpacing: 0,
    lineHeight: 28.8,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-body-xlarge-link': {
    fontFamily: '"Rubik", sans-serif',
    fontWeight: '500',
    fontSize: 24,
    letterSpacing: 0,
    lineHeight: 28.8,
    textTransform: 'none',
    textDecorationLine: 'underline'
  },
  'leaf-body-large': {
    fontFamily: '"Rubik", sans-serif',
    fontWeight: '400',
    fontSize: 20,
    letterSpacing: 0,
    lineHeight: 24,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-body-large-strong': {
    fontFamily: '"Rubik", sans-serif',
    fontWeight: '500',
    fontSize: 20,
    letterSpacing: 0,
    lineHeight: 24,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-body-default': {
    fontFamily: '"Rubik", sans-serif',
    fontWeight: '400',
    fontSize: 16,
    letterSpacing: 0,
    lineHeight: 24,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-body-default-strong': {
    fontFamily: '"Rubik", sans-serif',
    fontWeight: '500',
    fontSize: 16,
    letterSpacing: 0,
    lineHeight: 24,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-body-small': {
    fontFamily: '"Rubik", sans-serif',
    fontWeight: '400',
    fontSize: 12,
    letterSpacing: 0,
    lineHeight: 15.96,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-body-small-strong': {
    fontFamily: '"Rubik", sans-serif',
    fontWeight: '500',
    fontSize: 12,
    letterSpacing: 0,
    lineHeight: 15.96,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-body-large-link': {
    fontFamily: '"Rubik", sans-serif',
    fontWeight: '400',
    fontSize: 20,
    letterSpacing: 0,
    lineHeight: 24,
    textTransform: 'none',
    textDecorationLine: 'underline'
  },
  'leaf-body-default-link': {
    fontFamily: '"Rubik", sans-serif',
    fontWeight: '400',
    fontSize: 16,
    letterSpacing: 0,
    lineHeight: 24,
    textTransform: 'none',
    textDecorationLine: 'underline'
  },
  'leaf-body-small-link': {
    fontFamily: '"Rubik", sans-serif',
    fontWeight: '400',
    fontSize: 12,
    letterSpacing: 0,
    lineHeight: 15.96,
    textTransform: 'none',
    textDecorationLine: 'underline'
  },
  'leaf-label-default': {
    fontFamily: '"Rubik", sans-serif',
    fontWeight: '500',
    fontSize: 16,
    letterSpacing: 0,
    lineHeight: 24,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-label-large': {
    fontFamily: '"Rubik", sans-serif',
    fontWeight: '500',
    fontSize: 16,
    letterSpacing: 0,
    lineHeight: 24,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-label-small': {
    fontFamily: '"Rubik", sans-serif',
    fontWeight: '500',
    fontSize: 14,
    letterSpacing: 0,
    lineHeight: 20.02,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-title-xlarge': {
    fontFamily: '"Rubik", sans-serif',
    fontWeight: '300',
    fontSize: 32,
    letterSpacing: 0,
    lineHeight: 40,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-title-xlarge-mobile': {
    fontFamily: '"Rubik", sans-serif',
    fontWeight: '300',
    fontSize: 24,
    letterSpacing: 0,
    lineHeight: 27.36,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-title-large': {
    fontFamily: '"Rubik", sans-serif',
    fontWeight: '300',
    fontSize: 24,
    letterSpacing: 0,
    lineHeight: 36,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-title-large-mobile': {
    fontFamily: '"Rubik", sans-serif',
    fontWeight: '300',
    fontSize: 20,
    letterSpacing: 0,
    lineHeight: 23.2,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-title-default': {
    fontFamily: '"Rubik", sans-serif',
    fontWeight: '300',
    fontSize: 20,
    letterSpacing: 0,
    lineHeight: 26,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-title-default-mobile': {
    fontFamily: '"Rubik", sans-serif',
    fontWeight: '300',
    fontSize: 18,
    letterSpacing: 0,
    lineHeight: 23.4,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-title-small': {
    fontFamily: '"Rubik", sans-serif',
    fontWeight: '300',
    fontSize: 16,
    letterSpacing: 0,
    lineHeight: 24,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-title-small-mobile': {
    fontFamily: '"Rubik", sans-serif',
    fontWeight: '300',
    fontSize: 16,
    letterSpacing: 0,
    lineHeight: 24,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-headline-large': {
    fontFamily: '"Rubik", sans-serif',
    fontWeight: '300',
    fontSize: 48,
    letterSpacing: -1,
    lineHeight: 55.68,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-headline-large-mobile': {
    fontFamily: '"Rubik", sans-serif',
    fontWeight: '300',
    fontSize: 40,
    letterSpacing: -0.5,
    lineHeight: 46.4,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-headline-default': {
    fontFamily: '"Rubik", sans-serif',
    fontWeight: '300',
    fontSize: 40,
    letterSpacing: -0.5,
    lineHeight: 48,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-headline-default-mobile': {
    fontFamily: '"Rubik", sans-serif',
    fontWeight: '300',
    fontSize: 32,
    letterSpacing: 0,
    lineHeight: 38.4,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-headline-small': {
    fontFamily: '"Rubik", sans-serif',
    fontWeight: '300',
    fontSize: 32,
    letterSpacing: 0,
    lineHeight: 40,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-headline-small-mobile': {
    fontFamily: '"Rubik", sans-serif',
    fontWeight: '300',
    fontSize: 28,
    letterSpacing: 0,
    lineHeight: 35,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-headline-xsmall': {
    fontFamily: '"Rubik", sans-serif',
    fontWeight: '300',
    fontSize: 24,
    letterSpacing: 0,
    lineHeight: 31.2,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-headline-xsmall-mobile': {
    fontFamily: '"Rubik", sans-serif',
    fontWeight: '300',
    fontSize: 24,
    letterSpacing: 0,
    lineHeight: 31.2,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-display-large': {
    fontFamily: '"Rubik", sans-serif',
    fontWeight: '400',
    fontSize: 80,
    letterSpacing: -1.5,
    lineHeight: 90.4,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-display-large-mobile': {
    fontFamily: '"Rubik", sans-serif',
    fontWeight: '400',
    fontSize: 72,
    letterSpacing: -1.5,
    lineHeight: 81.36,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-display-default': {
    fontFamily: '"Rubik", sans-serif',
    fontWeight: '400',
    fontSize: 64,
    letterSpacing: -1.5,
    lineHeight: 72.32,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-display-default-mobile': {
    fontFamily: '"Rubik", sans-serif',
    fontWeight: '400',
    fontSize: 56,
    letterSpacing: -1.5,
    lineHeight: 63.28,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-display-small': {
    fontFamily: '"Rubik", sans-serif',
    fontWeight: '400',
    fontSize: 48,
    letterSpacing: -1,
    lineHeight: 55.68,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-display-small-mobile': {
    fontFamily: '"Rubik", sans-serif',
    fontWeight: '400',
    fontSize: 40,
    letterSpacing: -0.5,
    lineHeight: 46.4,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-meta-default': {
    fontFamily: '"Rubik", sans-serif',
    fontWeight: '500',
    fontSize: 14,
    letterSpacing: 1,
    lineHeight: 21,
    textTransform: 'uppercase',
    textDecorationLine: 'none'
  },
  'leaf-meta-large': {
    fontFamily: '"Rubik", sans-serif',
    fontWeight: '500',
    fontSize: 16,
    letterSpacing: 1,
    lineHeight: 24,
    textTransform: 'uppercase',
    textDecorationLine: 'none'
  },
  'leaf-meta-small': {
    fontFamily: '"Rubik", sans-serif',
    fontWeight: '500',
    fontSize: 12,
    letterSpacing: 1,
    lineHeight: 15.96,
    textTransform: 'uppercase',
    textDecorationLine: 'none'
  },
  'leaf-meta-default-sentence-case': {
    fontFamily: '"Rubik", sans-serif',
    fontWeight: '500',
    fontSize: 14,
    letterSpacing: 1,
    lineHeight: 21,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-shadow-large': {
    shadowOpacity: 1,
    shadowOffset: { width: 0, height: 10 },
    elevation: 4,
    shadowRadius: 12,
    shadowColor: 'rgba(0,0,0,0.2)'
  },
  'leaf-shadow-default': {
    shadowOpacity: 1,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
    shadowRadius: 6,
    shadowColor: 'rgba(0,0,0,0.1)'
  },
  'leaf-shadow-small': {
    shadowOpacity: 1,
    shadowOffset: { width: 0, height: 1 },
    elevation: 1,
    shadowRadius: 2,
    shadowColor: 'rgba(0,0,0,0.2)'
  },
  'leaf-shadow-none': undefined,
  'leaf-shadow-button': undefined,
  'leaf-desktop-menu-padding-vertical-padding': 16,
  'leaf-desktop-menu-padding-horizontal-padding': 8,
  'leaf-spacing-0': 0,
  'leaf-spacing-2': 2,
  'leaf-spacing-4': 4,
  'leaf-spacing-6': 6,
  'leaf-spacing-8': 8,
  'leaf-spacing-12': 12,
  'leaf-spacing-14': 14,
  'leaf-spacing-16': 16,
  'leaf-spacing-24': 24,
  'leaf-spacing-32': 32,
  'leaf-spacing-40': 40,
  'leaf-spacing-48': 48,
  'leaf-spacing-64': 64,
  'leaf-spacing-80': 80,
  'leaf-spacing-96': 96,
  'leaf-spacing-120': 120,
  'leaf-spacing-160': 160,
  'leaf-color-header-bg-default': '#ffffff',
  'leaf-color-header-inverse-bg-default': '#14568d',
  'leaf-color-header-bg-secondary': '#207BBF',
  'leaf-color-header-inverse-bg-secondary': '#207BBF',
  'leaf-color-header-bg-tertiary': '#14568d',
  'leaf-color-header-inverse-bg-tertiary': '#ffffff',
  'leaf-color-header-menu-bg-default': '#207BBF',
  'leaf-color-header-menu-inverse-bg-default': '#207BBF',
  'leaf-color-header-menu-bg-selected': '#207BBF',
  'leaf-color-header-menu-inverse-bg-selected': '#207BBF',
  'leaf-color-header-menu-bg-hover': '#ffffff',
  'leaf-color-header-menu-inverse-bg-hover': '#ffffff',
  'leaf-color-header-menu-bg-pressed': '#207BBF',
  'leaf-color-header-menu-inverse-bg-pressed': '#207BBF',
  'leaf-color-header-menu-bg-active': '#207BBF',
  'leaf-color-header-menu-inverse-bg-active': '#207BBF',
  'leaf-color-header-menu-bg-focus': '#ffffff',
  'leaf-color-header-menu-inverse-bg-focus': '#ffffff',
  'leaf-color-header-menu-content-default': '#ffffff',
  'leaf-color-header-menu-inverse-content-default': '#ffffff',
  'leaf-color-header-menu-content-hover': '#207BBF',
  'leaf-color-header-menu-inverse-content-hover': '#207BBF',
  'leaf-color-header-menu-content-pressed': '#ffffff',
  'leaf-color-header-menu-inverse-content-pressed': '#ffffff',
  'leaf-color-header-menu-content-active': '#ffffff',
  'leaf-color-header-menu-inverse-content-active': '#ffffff',
  'leaf-color-header-menu-content-selected': '#ffffff',
  'leaf-color-header-menu-inverse-content-selected': '#ffffff',
  'leaf-color-header-menu-content-focus': '#207BBF',
  'leaf-color-header-menu-inverse-content-focus': '#207BBF',
  'leaf-color-header-menu-border-default': 'rgba(#000000,0.0)',
  'leaf-color-header-menu-inverse-border-default': 'rgba(#000000,0.0)',
  'leaf-color-header-menu-border-pressed': '#207BBF',
  'leaf-color-header-menu-inverse-border-pressed': '#207BBF',
  'leaf-color-header-menu-border-active': '#207BBF',
  'leaf-color-header-menu-inverse-border-active': '#207BBF',
  'leaf-color-header-menu-border-selected': '#207BBF',
  'leaf-color-header-menu-inverse-border-selected': '#207BBF',
  'leaf-color-header-menu-border-focus': '#ffffff',
  'leaf-color-header-menu-inverse-border-focus': '#ffffff',
  'leaf-color-header-menu-border-hover': '#ffffff',
  'leaf-color-header-menu-inverse-border-hover': '#ffffff',
  'leaf-color-header-submenu-bg-default': '#ffffff',
  'leaf-color-header-submenu-inverse-bg-default': '#ffffff',
  'leaf-color-header-submenu-bg-hover': '#14568d',
  'leaf-color-header-submenu-inverse-bg-hover': '#14568d',
  'leaf-color-header-submenu-bg-pressed': '#ffffff',
  'leaf-color-header-submenu-inverse-bg-pressed': '#ffffff',
  'leaf-color-header-submenu-bg-active': '#ffffff',
  'leaf-color-header-submenu-inverse-bg-active': '#ffffff',
  'leaf-color-header-submenu-bg-focus': '#14568d',
  'leaf-color-header-submenu-inverse-bg-focus': '#14568d',
  'leaf-color-header-submenu-bg-selected': '#ffffff',
  'leaf-color-header-submenu-inverse-bg-selected': '#ffffff',
  'leaf-color-header-submenu-content-default': '#14568d',
  'leaf-color-header-submenu-inverse-content-default': '#14568d',
  'leaf-color-header-submenu-content-hover': '#ffffff',
  'leaf-color-header-submenu-inverse-content-hover': '#ffffff',
  'leaf-color-header-submenu-content-pressed': '#14568d',
  'leaf-color-header-submenu-inverse-content-pressed': '#14568d',
  'leaf-color-header-submenu-content-active': '#14568d',
  'leaf-color-header-submenu-inverse-content-active': '#14568d',
  'leaf-color-header-submenu-content-focus': '#ffffff',
  'leaf-color-header-submenu-inverse-content-focus': '#ffffff',
  'leaf-color-header-submenu-content-selected': '#14568d',
  'leaf-color-header-submenu-inverse-content-selected': '#14568d',
  'leaf-color-header-submenu-border-default': '#ffffff',
  'leaf-color-header-submenu-inverse-border-default': '#ffffff',
  'leaf-color-header-submenu-border-hover': '#14568d',
  'leaf-color-header-submenu-inverse-border-hover': '#14568d',
  'leaf-color-header-submenu-border-focus': '#14568d',
  'leaf-color-header-submenu-inverse-border-focus': '#14568d',
  'leaf-color-header-submenu-border-active': '#ffffff',
  'leaf-color-header-submenu-inverse-border-active': '#ffffff',
  'leaf-color-header-submenu-border-pressed': '#ffffff',
  'leaf-color-header-submenu-inverse-border-pressed': '#ffffff',
  'leaf-color-header-submenu-border-selected': '#ffffff',
  'leaf-color-header-submenu-inverse-border-selected': '#ffffff',
  'leaf-color-footer-bg-default': '#14568d',
  'leaf-color-footer-bg-secondary': '#14568d',
  'leaf-color-footer-content-default': '#ffffff',
  'leaf-color-footer-content-secondary': '#ffffff',
  'leaf-color-footer-link-default': '#addbf0',
  'leaf-color-footer-link-hover': '#ffffff',
  'leaf-line-heights-0': 1.1500000000000001,
  'leaf-line-heights-1': 1.12,
  'leaf-line-heights-2': 1.1400000000000001,
  'leaf-line-heights-3': 1.25,
  'leaf-line-heights-4': 1.5,
  'leaf-line-heights-5': 1.3,
  'leaf-line-heights-6': 1.33,
  'leaf-line-heights-7': 1.4000000000000001,
  'leaf-line-heights-8': 1.24,
  'leaf-line-heights-9': 1.11,
  'leaf-line-heights-10': 1.1300000000000001,
  'leaf-line-heights-11': 1.16,
  'leaf-line-heights-12': 1.2,
  'leaf-line-heights-13': 1.43,
  'leaf-line-heights-14': 48,
  'leaf-line-heights-15': 72,
  'leaf-font-weights-rubik-0': '400',
  'leaf-font-weights-rubik-1': '300',
  'leaf-font-weights-rubik-2': '500',
  'leaf-font-weights-rubik-3': 'SemiBold',
  'leaf-font-weights-rubik-4': 'Bold',
  'leaf-font-weights-rubik-5': 'Black',
  'leaf-font-weights-rubik-6': 'ExtraBold',
  'leaf-font-size-0': 12,
  'leaf-font-size-1': 14,
  'leaf-font-size-2': 16,
  'leaf-font-size-3': 18,
  'leaf-font-size-4': 20,
  'leaf-font-size-5': 24,
  'leaf-font-size-6': 28,
  'leaf-font-size-7': 32,
  'leaf-font-size-8': 40,
  'leaf-font-size-9': 48,
  'leaf-font-size-10': 56,
  'leaf-font-size-11': 64,
  'leaf-font-size-12': 72,
  'leaf-font-size-13': 80,
  'leaf-letter-spacing-0': 0,
  'leaf-letter-spacing-1': -0.5,
  'leaf-letter-spacing-2': 0,
  'leaf-letter-spacing-3': 1,
  'leaf-letter-spacing-4': -1.5,
  'leaf-letter-spacing-5': -1,
  'leaf-border-width-button-tertiary-outline-focus': 1,
  'leaf-border-width-button-default': 1,
  'leaf-border-width-tab-selected': 2,
  'leaf-border-width-tab-default': 2,
  'leaf-border-width-none': 0,
  'leaf-border-width-default': 1,
  'leaf-border-width-focus': 2,
  'leaf-border-width-large': 4,
  'leaf-border-style-button-tertiary-outline-focus': 'dashed',
  'leaf-border-style-default': 'solid',
  'leaf-icon-size-small': 14,
  'leaf-icon-size-default': 16,
  'leaf-icon-size-large': 16,
  'leaf-badge-padding-horizontal': 16,
  'leaf-badge-padding-vertical': 4,
  'leaf-progress-meter-height': 8,
  'leaf-breakpoint-xsm': '375px',
  'leaf-breakpoint-sm': '560px',
  'leaf-breakpoint-md': '768px',
  'leaf-breakpoint-lg': '960px',
  'leaf-breakpoint-xl': '1200px',
  'leaf-breakpoint-xxl': '1400px',
  'leaf-asset-font-rubik-300-normal': 'rubik-v4-latin-300',
  'leaf-asset-font-rubik-400-normal': 'rubik-v4-latin-regular',
  'leaf-asset-font-rubik-500-normal': 'rubik-v4-latin-500'
}