/**
 * Do not edit directly
 * Generated on Wed, 12 Nov 2025 07:11:37 GMT
 */


module.exports = {
  'cre8-font-family-default': "'Aeonik', sans-serif",
  'cre8-color-content-default': '#132342',
  'cre8-color-content-subtle': '#979aa0',
  'cre8-color-content-disabled': '#979aa0',
  'cre8-color-content-knockout': '#ffffff',
  'cre8-color-content-brand-knockout': '#addbf0',
  'cre8-color-content-brand': '#132342',
  'cre8-color-content-brand-strong': '#132342',
  'cre8-color-content-success': '#256700',
  'cre8-color-content-success-icon': '#256700',
  'cre8-color-content-error': '#e4292f',
  'cre8-color-content-error-icon': '#e4292f',
  'cre8-color-content-warning-icon': '#fdb81e',
  'cre8-color-content-info-icon': '#0f1b33',
  'cre8-color-content-attention-icon': '#973894',
  'cre8-color-content-link': '#132342',
  'cre8-color-content-inverse-link': '#ffffff',
  'cre8-color-content-link-hover': '#0f1b33',
  'cre8-color-content-inverse-link-hover': '#addbf0',
  'cre8-color-content-link-focus': '#ffffff',
  'cre8-color-content-inverse-link-focus': '#000000',
  'cre8-color-content-link-visited': '#0f1b33',
  'cre8-color-content-inverse-link-visited': '#c1d2e1',
  'cre8-color-content-link-active': '#0f1b33',
  'cre8-color-content-inverse-link-active': '#addbf0',
  'cre8-color-content-link-disabled': '#979aa0',
  'cre8-color-content-inverse-link-disabled': '#edeeef',
  'cre8-color-button-primary-danger-bg': '#515761',
  'cre8-color-button-primary-danger-inverse-bg': '#ffffff',
  'cre8-color-button-primary-danger-bg-hover': '#2f343d',
  'cre8-color-button-primary-danger-inverse-bg-hover': '#f8f8f9',
  'cre8-color-button-primary-danger-bg-active': '#000000',
  'cre8-color-button-primary-danger-inverse-bg-active': '#edeeef',
  'cre8-color-button-primary-danger-bg-disabled': '#dcdddf',
  'cre8-color-button-primary-danger-inverse-bg-disabled': '#b9bcc0',
  'cre8-color-button-primary-danger-content': '#ffffff',
  'cre8-color-button-primary-danger-inverse-content': '#000000',
  'cre8-color-button-primary-danger-content-hover': '#ffffff',
  'cre8-color-button-primary-danger-inverse-content-hover': '#000000',
  'cre8-color-button-primary-danger-content-active': '#ffffff',
  'cre8-color-button-primary-danger-inverse-content-active': '#000000',
  'cre8-color-button-primary-danger-content-disabled': '#ffffff',
  'cre8-color-button-primary-danger-inverse-content-disabled': '#000000',
  'cre8-color-button-primary-danger-border': '#515761',
  'cre8-color-button-primary-danger-inverse-border': '#ffffff',
  'cre8-color-button-primary-danger-border-hover': '#2f343d',
  'cre8-color-button-primary-danger-inverse-border-hover': '#f8f8f9',
  'cre8-color-button-primary-danger-border-active': '#000000',
  'cre8-color-button-primary-danger-inverse-border-active': '#edeeef',
  'cre8-color-button-primary-danger-border-disabled': '#dcdddf',
  'cre8-color-button-primary-danger-inverse-border-disabled': '#b9bcc0',
  'cre8-color-button-primary-danger-outline': '#000000',
  'cre8-color-button-primary-danger-inverse-outline': '#ffffff',
  'cre8-color-button-primary-bg': '#132342',
  'cre8-color-button-primary-inverse-bg': '#ffffff',
  'cre8-color-button-primary-bg-hover': '#0f1b33',
  'cre8-color-button-primary-inverse-bg-hover': '#c1d2e1',
  'cre8-color-button-primary-bg-active': '#0f1b33',
  'cre8-color-button-primary-inverse-bg-active': '#addbf0',
  'cre8-color-button-primary-bg-disabled': '#dcdddf',
  'cre8-color-button-primary-inverse-bg-disabled': '#edeeef',
  'cre8-color-button-primary-border': '#132342',
  'cre8-color-button-primary-inverse-border': '#ffffff',
  'cre8-color-button-primary-border-hover': '#0f1b33',
  'cre8-color-button-primary-inverse-border-hover': '#c1d2e1',
  'cre8-color-button-primary-border-active': '#0f1b33',
  'cre8-color-button-primary-inverse-border-active': '#addbf0',
  'cre8-color-button-primary-border-disabled': '#dcdddf',
  'cre8-color-button-primary-inverse-border-disabled': '#edeeef',
  'cre8-color-button-primary-content': '#ffffff',
  'cre8-color-button-primary-inverse-content': '#132342',
  'cre8-color-button-primary-content-hover': '#ffffff',
  'cre8-color-button-primary-inverse-content-hover': '#132342',
  'cre8-color-button-primary-content-active': '#ffffff',
  'cre8-color-button-primary-inverse-content-active': '#132342',
  'cre8-color-button-primary-content-disabled': '#979aa0',
  'cre8-color-button-primary-inverse-content-disabled': '#979aa0',
  'cre8-color-button-primary-outline': '#132342',
  'cre8-color-button-primary-inverse-outline': '#addbf0',
  'cre8-color-button-secondary-neutral-bg': 'rgba( #000000 ,0.0)',
  'cre8-color-button-secondary-neutral-inverse-bg': 'rgba( #000000 ,0.0)',
  'cre8-color-button-secondary-neutral-content': '#000000',
  'cre8-color-button-secondary-neutral-inverse-content': '#ffffff',
  'cre8-color-button-secondary-neutral-border': '#000000',
  'cre8-color-button-secondary-neutral-inverse-border': '#ffffff',
  'cre8-color-button-secondary-neutral-bg-hover': 'rgba(#000000,0.08)',
  'cre8-color-button-secondary-neutral-inverse-bg-hover': 'rgba(#000000,0.25)',
  'cre8-color-button-secondary-neutral-content-hover': '#000000',
  'cre8-color-button-secondary-neutral-inverse-content-hover': '#ffffff',
  'cre8-color-button-secondary-neutral-border-hover': '#000000',
  'cre8-color-button-secondary-neutral-inverse-border-hover': '#ffffff',
  'cre8-color-button-secondary-neutral-border-active': '#000000',
  'cre8-color-button-secondary-neutral-inverse-border-active': '#ffffff',
  'cre8-color-button-secondary-neutral-bg-active': 'rgba(#000000,0.25)',
  'cre8-color-button-secondary-neutral-inverse-bg-active': '#b9bcc0',
  'cre8-color-button-secondary-neutral-content-active': '#000000',
  'cre8-color-button-secondary-neutral-inverse-content-active': '#ffffff',
  'cre8-color-button-secondary-neutral-bg-disabled': '#f8f8f9',
  'cre8-color-button-secondary-neutral-inverse-bg-disabled': '#b9bcc0',
  'cre8-color-button-secondary-neutral-border-disabled': '#f8f8f9',
  'cre8-color-button-secondary-neutral-inverse-border-disabled': '#b9bcc0',
  'cre8-color-button-secondary-neutral-content-disabled': '#979aa0',
  'cre8-color-button-secondary-neutral-inverse-content-disabled': '#515761',
  'cre8-color-button-secondary-neutral-outline': '#000000',
  'cre8-color-button-secondary-neutral-inverse-outline': '#ffffff',
  'cre8-color-button-secondary-danger-bg': 'rgba( #000000 ,0.0)',
  'cre8-color-button-secondary-danger-inverse-bg': 'rgba( #000000 ,0.0)',
  'cre8-color-button-secondary-danger-bg-hover': '#2f343d',
  'cre8-color-button-secondary-danger-inverse-bg-hover': '#f8f8f9',
  'cre8-color-button-secondary-danger-bg-active': '#000000',
  'cre8-color-button-secondary-danger-inverse-bg-active': '#edeeef',
  'cre8-color-button-secondary-danger-bg-disabled': '#b9bcc0',
  'cre8-color-button-secondary-danger-inverse-bg-disabled': '#b9bcc0',
  'cre8-color-button-secondary-danger-content': '#ffffff',
  'cre8-color-button-secondary-danger-inverse-content': '#000000',
  'cre8-color-button-secondary-danger-content-hover': '#ffffff',
  'cre8-color-button-secondary-danger-inverse-content-hover': '#000000',
  'cre8-color-button-secondary-danger-content-active': '#ffffff',
  'cre8-color-button-secondary-danger-inverse-content-active': '#000000',
  'cre8-color-button-secondary-danger-content-disabled': '#ffffff',
  'cre8-color-button-secondary-danger-inverse-content-disabled': '#000000',
  'cre8-color-button-secondary-danger-border': '#2f343d',
  'cre8-color-button-secondary-danger-inverse-border': '#ffffff',
  'cre8-color-button-secondary-danger-border-hover': '#2f343d',
  'cre8-color-button-secondary-danger-inverse-border-hover': '#f8f8f9',
  'cre8-color-button-secondary-danger-border-active': '#000000',
  'cre8-color-button-secondary-danger-inverse-border-active': '#edeeef',
  'cre8-color-button-secondary-danger-border-disabled': '#b9bcc0',
  'cre8-color-button-secondary-danger-inverse-border-disabled': '#b9bcc0',
  'cre8-color-button-secondary-danger-outline': '#000000',
  'cre8-color-button-secondary-danger-inverse-outline': '#ffffff',
  'cre8-color-button-secondary-bg': '#ffffff',
  'cre8-color-button-secondary-inverse-bg': '#ffffff',
  'cre8-color-button-secondary-bg-hover': '#ffffff',
  'cre8-color-button-secondary-inverse-bg-hover': '#ffffff',
  'cre8-color-button-secondary-bg-active': '#ffffff',
  'cre8-color-button-secondary-inverse-bg-active': '#ffffff',
  'cre8-color-button-secondary-bg-disabled': '#dcdddf',
  'cre8-color-button-secondary-inverse-bg-disabled': '#dcdddf',
  'cre8-color-button-secondary-border': '#132342',
  'cre8-color-button-secondary-inverse-border': '#132342',
  'cre8-color-button-secondary-border-hover': '#0f1b33',
  'cre8-color-button-secondary-inverse-border-hover': '#0f1b33',
  'cre8-color-button-secondary-border-active': '#0f1b33',
  'cre8-color-button-secondary-inverse-border-active': '#0f1b33',
  'cre8-color-button-secondary-border-disabled': '#dcdddf',
  'cre8-color-button-secondary-inverse-border-disabled': '#dcdddf',
  'cre8-color-button-secondary-content': '#132342',
  'cre8-color-button-secondary-inverse-content': '#132342',
  'cre8-color-button-secondary-content-hover': '#0f1b33',
  'cre8-color-button-secondary-inverse-content-hover': '#0f1b33',
  'cre8-color-button-secondary-content-active': '#0f1b33',
  'cre8-color-button-secondary-inverse-content-active': '#0f1b33',
  'cre8-color-button-secondary-content-disabled': '#979aa0',
  'cre8-color-button-secondary-inverse-content-disabled': '#979aa0',
  'cre8-color-button-secondary-outline': '#0f1b33',
  'cre8-color-button-secondary-inverse-outline': '#0f1b33',
  'cre8-color-button-tertiary-neutral-bg': 'rgba( #000000 ,0.0)',
  'cre8-color-button-tertiary-neutral-inverse-bg': 'rgba( #000000 ,0.0)',
  'cre8-color-button-tertiary-neutral-content': '#000000',
  'cre8-color-button-tertiary-neutral-inverse-content': '#ffffff',
  'cre8-color-button-tertiary-neutral-border': 'rgba( #000000 ,0.0)',
  'cre8-color-button-tertiary-neutral-inverse-border': 'rgba( #000000 ,0.0)',
  'cre8-color-button-tertiary-neutral-bg-hover': 'rgba( #000000 ,0.0)',
  'cre8-color-button-tertiary-neutral-inverse-bg-hover': 'rgba( #000000 ,0.0)',
  'cre8-color-button-tertiary-neutral-content-hover': '#000000',
  'cre8-color-button-tertiary-neutral-inverse-content-hover': '#ffffff',
  'cre8-color-button-tertiary-neutral-border-hover': '#000000',
  'cre8-color-button-tertiary-neutral-inverse-border-hover': '#ffffff',
  'cre8-color-button-tertiary-neutral-border-active': '#000000',
  'cre8-color-button-tertiary-neutral-inverse-border-active': '#ffffff',
  'cre8-color-button-tertiary-neutral-bg-active': 'rgba( #000000 ,0.0)',
  'cre8-color-button-tertiary-neutral-inverse-bg-active': 'rgba( #000000 ,0.0)',
  'cre8-color-button-tertiary-neutral-content-active': '#000000',
  'cre8-color-button-tertiary-neutral-inverse-content-active': '#ffffff',
  'cre8-color-button-tertiary-neutral-bg-disabled': 'rgba( #000000 ,0.0)',
  'cre8-color-button-tertiary-neutral-inverse-bg-disabled': 'rgba( #000000 ,0.0)',
  'cre8-color-button-tertiary-neutral-border-disabled': 'rgba( #000000 ,0.0)',
  'cre8-color-button-tertiary-neutral-inverse-border-disabled': 'rgba( #000000 ,0.0)',
  'cre8-color-button-tertiary-neutral-content-disabled': '#979aa0',
  'cre8-color-button-tertiary-neutral-inverse-content-disabled': '#515761',
  'cre8-color-button-tertiary-neutral-outline': '#000000',
  'cre8-color-button-tertiary-neutral-inverse-outline': '#ffffff',
  'cre8-color-button-tertiary-danger-bg': 'rgba( #000000 ,0.0)',
  'cre8-color-button-tertiary-danger-inverse-bg': 'rgba( #000000 ,0.0)',
  'cre8-color-button-tertiary-danger-bg-hover': '#2f343d',
  'cre8-color-button-tertiary-danger-inverse-bg-hover': '#f8f8f9',
  'cre8-color-button-tertiary-danger-bg-active': '#000000',
  'cre8-color-button-tertiary-danger-inverse-bg-active': '#edeeef',
  'cre8-color-button-tertiary-danger-bg-disabled': '#b9bcc0',
  'cre8-color-button-tertiary-danger-inverse-bg-disabled': '#b9bcc0',
  'cre8-color-button-tertiary-danger-content': '#ffffff',
  'cre8-color-button-tertiary-danger-inverse-content': '#000000',
  'cre8-color-button-tertiary-danger-content-hover': '#ffffff',
  'cre8-color-button-tertiary-danger-inverse-content-hover': '#000000',
  'cre8-color-button-tertiary-danger-content-active': '#ffffff',
  'cre8-color-button-tertiary-danger-inverse-content-active': '#000000',
  'cre8-color-button-tertiary-danger-content-disabled': '#ffffff',
  'cre8-color-button-tertiary-danger-inverse-content-disabled': '#000000',
  'cre8-color-button-tertiary-danger-border': 'rgba( #000000 ,0.0)',
  'cre8-color-button-tertiary-danger-inverse-border': 'rgba( #000000 ,0.0)',
  'cre8-color-button-tertiary-danger-border-hover': '#2f343d',
  'cre8-color-button-tertiary-danger-inverse-border-hover': '#f8f8f9',
  'cre8-color-button-tertiary-danger-border-active': '#000000',
  'cre8-color-button-tertiary-danger-inverse-border-active': '#edeeef',
  'cre8-color-button-tertiary-danger-border-disabled': '#b9bcc0',
  'cre8-color-button-tertiary-danger-inverse-border-disabled': '#b9bcc0',
  'cre8-color-button-tertiary-danger-outline': '#000000',
  'cre8-color-button-tertiary-danger-inverse-outline': '#ffffff',
  'cre8-color-button-tertiary-bg': 'rgba(#000000,0.0)',
  'cre8-color-button-tertiary-inverse-bg': 'rgba(#000000,0.0)',
  'cre8-color-button-tertiary-bg-hover': 'rgba(#000000,0.0)',
  'cre8-color-button-tertiary-inverse-bg-hover': 'rgba(#000000,0.0)',
  'cre8-color-button-tertiary-bg-active': 'rgba(#000000,0.0)',
  'cre8-color-button-tertiary-inverse-bg-active': 'rgba(#000000,0.0)',
  'cre8-color-button-tertiary-bg-disabled': 'rgba(#000000,0.0)',
  'cre8-color-button-tertiary-inverse-bg-disabled': 'rgba(#000000,0.0)',
  'cre8-color-button-tertiary-border': 'rgba(#000000,0.0)',
  'cre8-color-button-tertiary-inverse-border': 'rgba(#000000,0.0)',
  'cre8-color-button-tertiary-border-hover': 'rgba(#000000,0.0)',
  'cre8-color-button-tertiary-inverse-border-hover': 'rgba(#000000,0.0)',
  'cre8-color-button-tertiary-border-active': 'rgba(#000000,0.0)',
  'cre8-color-button-tertiary-inverse-border-active': 'rgba(#000000,0.0)',
  'cre8-color-button-tertiary-border-disabled': 'rgba(#000000,0.0)',
  'cre8-color-button-tertiary-inverse-border-disabled': 'rgba(#000000,0.0)',
  'cre8-color-button-tertiary-content': '#132342',
  'cre8-color-button-tertiary-inverse-content': '#132342',
  'cre8-color-button-tertiary-content-hover': '#0f1b33',
  'cre8-color-button-tertiary-inverse-content-hover': '#0f1b33',
  'cre8-color-button-tertiary-content-active': '#0f1b33',
  'cre8-color-button-tertiary-inverse-content-active': '#0f1b33',
  'cre8-color-button-tertiary-content-disabled': '#979aa0',
  'cre8-color-button-tertiary-inverse-content-disabled': '#979aa0',
  'cre8-color-button-tertiary-outline': '#0f1b33',
  'cre8-color-button-tertiary-inverse-outline': '#0f1b33',
  'cre8-button-padding-vertical-small': 8,
  'cre8-button-padding-vertical-medium': 8,
  'cre8-button-padding-vertical-large': 8,
  'cre8-button-padding-vertical-icon-only': 8,
  'cre8-button-padding-vertical-small-icon-only': 8,
  'cre8-button-padding-vertical-medium-icon-only': 16,
  'cre8-button-padding-vertical-large-icon-only': 16,
  'cre8-button-padding-horizontal-small': 16,
  'cre8-button-padding-horizontal-medium': 24,
  'cre8-button-padding-horizontal-large': 24,
  'cre8-button-padding-horizontal-icon-only': 8,
  'cre8-button-padding-horizontal-small-icon-only': 8,
  'cre8-button-padding-horizontal-medium-icon-only': 16,
  'cre8-button-padding-horizontal-large-icon-only': 16,
  'cre8-paragraph-indent-0': 0,
  'cre8-border-radius-small': 0,
  'cre8-border-radius-default': 0,
  'cre8-border-radius-large': 4,
  'cre8-border-radius-round': 900,
  'cre8-border-radius-button': 0,
  'cre8-border-radius-badge': 16,
  'cre8-border-radius-tabs': 0,
  'cre8-border-radius-container': 0,
  'cre8-border-radius-field': 0,
  'cre8-border-radius-field-brand': 0,
  'cre8-border-radius-brand': 0,
  'cre8-border-radius-none': 0,
  'cre8-color-bg-default': '#ffffff',
  'cre8-color-bg-subtle': '#f8f8f9',
  'cre8-color-bg-moderate': '#979aa0',
  'cre8-color-bg-inverse-moderate': '#b9bcc0',
  'cre8-color-bg-strong': '#515761',
  'cre8-color-bg-disabled': '#dcdddf',
  'cre8-color-bg-brand': '#edf8fd',
  'cre8-color-bg-brand-strong': '#132342',
  'cre8-color-bg-brand-hover': '#f9dd71',
  'cre8-color-bg-brand-active': '#f5c600',
  'cre8-color-bg-brand-strong-hover': '#132342',
  'cre8-color-bg-brand-strong-active': '#132342',
  'cre8-color-bg-success': '#f1f6ed',
  'cre8-color-bg-error': '#fdf0f0',
  'cre8-color-bg-warning': '#fffaef',
  'cre8-color-bg-info': '#edf8fd',
  'cre8-color-bg-attention': '#fff6ff',
  'cre8-color-bg-success-strong': '#3c8700',
  'cre8-color-bg-error-strong': '#e4292f',
  'cre8-color-bg-warning-strong': '#f5c600',
  'cre8-color-bg-info-strong': '#0f1b33',
  'cre8-color-bg-attention-strong': '#973894',
  'cre8-color-bg-opacity-transparent': 'rgba( #000000 ,0.0)',
  'cre8-color-bg-opacity-default': 'rgba(#000000,0.65)',
  'cre8-color-bg-default-hover': '#c1d2e1',
  'cre8-color-bg-default-active': '#f9dd71',
  'cre8-color-bg-brand-xstrong': '#132342',
  'cre8-color-bg-brand-xstrong-hover': '#132342',
  'cre8-color-bg-brand-xstrong-active': '#132342',
  'cre8-color-bg-active': '#0f1b33',
  'cre8-color-bg-inverse-active': '#ffffff',
  'cre8-color-border-default': '#b9bcc0',
  'cre8-color-border-strong': '#515761',
  'cre8-color-border-knockout': '#ffffff',
  'cre8-color-border-disabled': '#b9bcc0',
  'cre8-color-border-brand': '#132342',
  'cre8-color-border-brand-subtle': '#172a4f',
  'cre8-color-border-brand-strong': '#132342',
  'cre8-color-border-success': '#256700',
  'cre8-color-border-error': '#e4292f',
  'cre8-color-border-warning': '#515761',
  'cre8-color-border-info': '#132342',
  'cre8-color-border-attention': '#973894',
  'cre8-color-border-transparent': '#50505000',
  'cre8-color-border-active-outline': '#132342',
  'cre8-body-xlarge': {
    fontFamily: "'Aeonik', sans-serif",
    fontWeight: '400',
    fontSize: 24,
    letterSpacing: 0,
    lineHeight: 33.6,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-body-xlarge-strong': {
    fontFamily: "'Aeonik', sans-serif",
    fontWeight: '700',
    fontSize: 24,
    letterSpacing: 0,
    lineHeight: 33.6,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-body-xlarge-link': {
    fontFamily: "'Aeonik', sans-serif",
    fontWeight: '700',
    fontSize: 24,
    letterSpacing: 0,
    lineHeight: 33.6,
    textTransform: 'none',
    textDecorationLine: 'underline'
  },
  'cre8-body-large': {
    fontFamily: "'Aeonik', sans-serif",
    fontWeight: '400',
    fontSize: 20,
    letterSpacing: 0,
    lineHeight: 28,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-body-large-strong': {
    fontFamily: "'Aeonik', sans-serif",
    fontWeight: '700',
    fontSize: 20,
    letterSpacing: 0,
    lineHeight: 28,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-body-default': {
    fontFamily: "'Aeonik', sans-serif",
    fontWeight: '400',
    fontSize: 16,
    letterSpacing: 0,
    lineHeight: 24,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-body-default-strong': {
    fontFamily: "'Aeonik', sans-serif",
    fontWeight: '700',
    fontSize: 16,
    letterSpacing: 0,
    lineHeight: 24,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-body-small': {
    fontFamily: "'Aeonik', sans-serif",
    fontWeight: '400',
    fontSize: 12,
    letterSpacing: 0,
    lineHeight: 15.96,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-body-small-strong': {
    fontFamily: "'Aeonik', sans-serif",
    fontWeight: '700',
    fontSize: 12,
    letterSpacing: 0,
    lineHeight: 15.96,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-body-large-link': {
    fontFamily: "'Aeonik', sans-serif",
    fontWeight: '400',
    fontSize: 20,
    letterSpacing: 0,
    lineHeight: 28,
    textTransform: 'none',
    textDecorationLine: 'underline'
  },
  'cre8-body-default-link': {
    fontFamily: "'Aeonik', sans-serif",
    fontWeight: '400',
    fontSize: 16,
    letterSpacing: 0,
    lineHeight: 22.88,
    textTransform: 'none',
    textDecorationLine: 'underline'
  },
  'cre8-body-small-link': {
    fontFamily: "'Aeonik', sans-serif",
    fontWeight: '400',
    fontSize: 12,
    letterSpacing: 0,
    lineHeight: 15.96,
    textTransform: 'none',
    textDecorationLine: 'underline'
  },
  'cre8-label-default': {
    fontFamily: "'Aeonik', sans-serif",
    fontWeight: '700',
    fontSize: 16,
    letterSpacing: 0,
    lineHeight: 24,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-label-large': {
    fontFamily: "'Aeonik', sans-serif",
    fontWeight: '700',
    fontSize: 16,
    letterSpacing: 0,
    lineHeight: 24,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-label-small': {
    fontFamily: "'Aeonik', sans-serif",
    fontWeight: '700',
    fontSize: 14,
    letterSpacing: 0,
    lineHeight: 20.02,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-title-xlarge': {
    fontFamily: "'Aeonik', sans-serif",
    fontWeight: '300',
    fontSize: 32,
    letterSpacing: 0,
    lineHeight: 40,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-title-xlarge-mobile': {
    fontFamily: "'Aeonik', sans-serif",
    fontWeight: '300',
    fontSize: 28,
    letterSpacing: 0,
    lineHeight: 40.04,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-title-large': {
    fontFamily: "'Aeonik', sans-serif",
    fontWeight: '300',
    fontSize: 28,
    letterSpacing: 0,
    lineHeight: 40.04,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-title-large-mobile': {
    fontFamily: "'Aeonik', sans-serif",
    fontWeight: '300',
    fontSize: 24,
    letterSpacing: 0,
    lineHeight: 31.92,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-title-default': {
    fontFamily: "'Aeonik', sans-serif",
    fontWeight: '300',
    fontSize: 24,
    letterSpacing: 0,
    lineHeight: 31.92,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-title-default-mobile': {
    fontFamily: "'Aeonik', sans-serif",
    fontWeight: '300',
    fontSize: 18,
    letterSpacing: 0,
    lineHeight: 23.94,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-title-small': {
    fontFamily: "'Aeonik', sans-serif",
    fontWeight: '300',
    fontSize: 16,
    letterSpacing: 0,
    lineHeight: 24,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-title-small-mobile': {
    fontFamily: "'Aeonik', sans-serif",
    fontWeight: '300',
    fontSize: 16,
    letterSpacing: 0,
    lineHeight: 24,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-headline-large': {
    fontFamily: "'Aeonik', sans-serif",
    fontWeight: '300',
    fontSize: 48,
    letterSpacing: -1,
    lineHeight: 56.16,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-headline-large-mobile': {
    fontFamily: "'Aeonik', sans-serif",
    fontWeight: '300',
    fontSize: 48,
    letterSpacing: -1,
    lineHeight: 55.68,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-headline-default': {
    fontFamily: "'Aeonik', sans-serif",
    fontWeight: '300',
    fontSize: 40,
    letterSpacing: -0.5,
    lineHeight: 48,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-headline-default-mobile': {
    fontFamily: "'Aeonik', sans-serif",
    fontWeight: '300',
    fontSize: 40,
    letterSpacing: -0.5,
    lineHeight: 48,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-headline-small': {
    fontFamily: "'Aeonik', sans-serif",
    fontWeight: '300',
    fontSize: 32,
    letterSpacing: 0,
    lineHeight: 40,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-headline-small-mobile': {
    fontFamily: "'Aeonik', sans-serif",
    fontWeight: '300',
    fontSize: 32,
    letterSpacing: 0,
    lineHeight: 40,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-headline-xsmall': {
    fontFamily: "'Aeonik', sans-serif",
    fontWeight: '300',
    fontSize: 24,
    letterSpacing: 0,
    lineHeight: 30,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-headline-xsmall-mobile': {
    fontFamily: "'Aeonik', sans-serif",
    fontWeight: '300',
    fontSize: 24,
    letterSpacing: 0,
    lineHeight: 30,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-display-large': {
    fontFamily: "'Aeonik', sans-serif",
    fontWeight: '400',
    fontSize: 80,
    letterSpacing: -1.5,
    lineHeight: 90.4,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-display-large-mobile': {
    fontFamily: "'Aeonik', sans-serif",
    fontWeight: '400',
    fontSize: 72,
    letterSpacing: -1.5,
    lineHeight: 81.36,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-display-default': {
    fontFamily: "'Aeonik', sans-serif",
    fontWeight: '400',
    fontSize: 64,
    letterSpacing: -1.5,
    lineHeight: 72.32,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-display-default-mobile': {
    fontFamily: "'Aeonik', sans-serif",
    fontWeight: '400',
    fontSize: 64,
    letterSpacing: -1.5,
    lineHeight: 72.32,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-display-small': {
    fontFamily: "'Aeonik', sans-serif",
    fontWeight: '400',
    fontSize: 48,
    letterSpacing: -1,
    lineHeight: 56.16,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-display-small-mobile': {
    fontFamily: "'Aeonik', sans-serif",
    fontWeight: '400',
    fontSize: 48,
    letterSpacing: -1,
    lineHeight: 56.16,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-meta-default': {
    fontFamily: "'Aeonik', sans-serif",
    fontWeight: '700',
    fontSize: 14,
    letterSpacing: 1,
    lineHeight: 21,
    textTransform: 'uppercase',
    textDecorationLine: 'none'
  },
  'cre8-meta-large': {
    fontFamily: "'Aeonik', sans-serif",
    fontWeight: '700',
    fontSize: 16,
    letterSpacing: 1,
    lineHeight: 24,
    textTransform: 'uppercase',
    textDecorationLine: 'none'
  },
  'cre8-meta-default-sentence-case': {
    fontFamily: "'Aeonik', sans-serif",
    fontWeight: '700',
    fontSize: 14,
    letterSpacing: 1,
    lineHeight: 21,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-meta-small': {
    fontFamily: "'Aeonik', sans-serif",
    fontWeight: '700',
    fontSize: 12,
    letterSpacing: 1,
    lineHeight: 15.96,
    textTransform: 'uppercase',
    textDecorationLine: 'none'
  },
  'cre8-shadow-large': {
    shadowOpacity: 1,
    shadowOffset: { width: 0, height: 10 },
    elevation: 4,
    shadowRadius: 12,
    shadowColor: 'rgba(0,0,0,0.2)'
  },
  'cre8-shadow-default': {
    shadowOpacity: 1,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
    shadowRadius: 6,
    shadowColor: 'rgba(0,0,0,0.1)'
  },
  'cre8-shadow-small': {
    shadowOpacity: 1,
    shadowOffset: { width: 0, height: 1 },
    elevation: 1,
    shadowRadius: 2,
    shadowColor: 'rgba(0,0,0,0.2)'
  },
  'cre8-shadow-none': undefined,
  'cre8-shadow-button': undefined,
  'cre8-desktop-menu-padding-vertical-padding': 16,
  'cre8-desktop-menu-padding-horizontal-padding': 8,
  'cre8-spacing-0': 0,
  'cre8-spacing-2': 2,
  'cre8-spacing-4': 4,
  'cre8-spacing-6': 6,
  'cre8-spacing-8': 8,
  'cre8-spacing-12': 12,
  'cre8-spacing-14': 14,
  'cre8-spacing-16': 16,
  'cre8-spacing-24': 24,
  'cre8-spacing-32': 32,
  'cre8-spacing-40': 40,
  'cre8-spacing-48': 48,
  'cre8-spacing-64': 64,
  'cre8-spacing-80': 80,
  'cre8-spacing-96': 96,
  'cre8-spacing-120': 120,
  'cre8-spacing-160': 160,
  'cre8-color-header-bg-default': '#ffffff',
  'cre8-color-header-inverse-bg-default': '#132342',
  'cre8-color-header-bg-secondary': '#132342',
  'cre8-color-header-inverse-bg-secondary': '#ffffff',
  'cre8-color-header-bg-tertiary': '#132342',
  'cre8-color-header-inverse-bg-tertiary': '#ffffff',
  'cre8-color-header-menu-bg-default': '#ffffff',
  'cre8-color-header-menu-inverse-bg-default': '#132342',
  'cre8-color-header-menu-bg-selected': '#ffffff',
  'cre8-color-header-menu-inverse-bg-selected': '#132342',
  'cre8-color-header-menu-bg-hover': '#ffffff',
  'cre8-color-header-menu-inverse-bg-hover': '#132342',
  'cre8-color-header-menu-bg-pressed': '#ffffff',
  'cre8-color-header-menu-inverse-bg-pressed': '#ffffff',
  'cre8-color-header-menu-bg-active': '#ffffff',
  'cre8-color-header-menu-inverse-bg-active': '#132342',
  'cre8-color-header-menu-bg-focus': '#ffffff',
  'cre8-color-header-menu-inverse-bg-focus': '#132342',
  'cre8-color-header-menu-content-default': '#132342',
  'cre8-color-header-menu-inverse-content-default': '#ffffff',
  'cre8-color-header-menu-content-hover': '#132342',
  'cre8-color-header-menu-inverse-content-hover': '#132342',
  'cre8-color-header-menu-content-pressed': '#132342',
  'cre8-color-header-menu-inverse-content-pressed': '#ffffff',
  'cre8-color-header-menu-content-active': '#132342',
  'cre8-color-header-menu-inverse-content-active': '#ffffff',
  'cre8-color-header-menu-content-selected': '#132342',
  'cre8-color-header-menu-inverse-content-selected': '#ffffff',
  'cre8-color-header-menu-content-focus': '#132342',
  'cre8-color-header-menu-inverse-content-focus': '#ffffff',
  'cre8-color-header-menu-border-default': '#ffffff',
  'cre8-color-header-menu-inverse-border-default': '#ffffff',
  'cre8-color-header-menu-border-pressed': '#132342',
  'cre8-color-header-menu-inverse-border-pressed': '#ffffff',
  'cre8-color-header-menu-border-active': '#132342',
  'cre8-color-header-menu-inverse-border-active': '#ffffff',
  'cre8-color-header-menu-border-selected': '#132342',
  'cre8-color-header-menu-inverse-border-selected': '#ffffff',
  'cre8-color-header-menu-border-focus': '#132342',
  'cre8-color-header-menu-inverse-border-focus': '#ffffff',
  'cre8-color-header-menu-border-hover': '#132342',
  'cre8-color-header-menu-inverse-border-hover': '#ffffff',
  'cre8-color-header-submenu-bg-default': '#ffffff',
  'cre8-color-header-submenu-inverse-bg-default': '#ffffff',
  'cre8-color-header-submenu-bg-hover': '#f9dd71',
  'cre8-color-header-submenu-inverse-bg-hover': '#c1d2e1',
  'cre8-color-header-submenu-bg-pressed': '#f9dd71',
  'cre8-color-header-submenu-inverse-bg-pressed': '#f9dd71',
  'cre8-color-header-submenu-bg-active': '#f9dd71',
  'cre8-color-header-submenu-inverse-bg-active': '#f9dd71',
  'cre8-color-header-submenu-bg-focus': '#ffffff',
  'cre8-color-header-submenu-inverse-bg-focus': '#f9dd71',
  'cre8-color-header-submenu-bg-selected': '#ffffff',
  'cre8-color-header-submenu-inverse-bg-selected': '#f9dd71',
  'cre8-color-header-submenu-content-default': '#132342',
  'cre8-color-header-submenu-inverse-content-default': '#132342',
  'cre8-color-header-submenu-content-hover': '#ffffff',
  'cre8-color-header-submenu-inverse-content-hover': '#132342',
  'cre8-color-header-submenu-content-pressed': '#ffffff',
  'cre8-color-header-submenu-inverse-content-pressed': '#132342',
  'cre8-color-header-submenu-content-active': '#ffffff',
  'cre8-color-header-submenu-inverse-content-active': '#132342',
  'cre8-color-header-submenu-content-focus': '#132342',
  'cre8-color-header-submenu-inverse-content-focus': '#ffffff',
  'cre8-color-header-submenu-content-selected': '#132342',
  'cre8-color-header-submenu-inverse-content-selected': '#ffffff',
  'cre8-color-header-submenu-border-default': '#132342',
  'cre8-color-header-submenu-inverse-border-default': '#132342',
  'cre8-color-header-submenu-border-hover': '#132342',
  'cre8-color-header-submenu-inverse-border-hover': '#132342',
  'cre8-color-header-submenu-border-focus': '#132342',
  'cre8-color-header-submenu-inverse-border-focus': '#ffffff',
  'cre8-color-header-submenu-border-active': '#132342',
  'cre8-color-header-submenu-inverse-border-active': '#132342',
  'cre8-color-header-submenu-border-pressed': '#132342',
  'cre8-color-header-submenu-inverse-border-pressed': '#132342',
  'cre8-color-header-submenu-border-selected': '#132342',
  'cre8-color-header-submenu-inverse-border-selected': '#ffffff',
  'cre8-color-footer-bg-default': '#132342',
  'cre8-color-footer-bg-secondary': '#132342',
  'cre8-color-footer-content-default': '#ffffff',
  'cre8-color-footer-content-secondary': '#ffffff',
  'cre8-color-footer-link-default': '#2ca6ff',
  'cre8-color-footer-link-hover': '#ffffff',
  'cre8-font-families-aeonik': "'Aeonik', sans-serif",
  'cre8-line-heights-0': 1.1500000000000001,
  'cre8-line-heights-1': 1.12,
  'cre8-line-heights-2': 1.1400000000000001,
  'cre8-line-heights-3': 1.25,
  'cre8-line-heights-4': 1.5,
  'cre8-line-heights-5': 1.3,
  'cre8-line-heights-6': 1.33,
  'cre8-line-heights-7': 1.4000000000000001,
  'cre8-line-heights-8': 1.24,
  'cre8-line-heights-9': 1.11,
  'cre8-line-heights-10': 1.1300000000000001,
  'cre8-line-heights-11': 1.17,
  'cre8-line-heights-12': 1.2,
  'cre8-line-heights-13': 1.43,
  'cre8-line-heights-14': 1.56,
  'cre8-line-heights-15': 1.16,
  'cre8-line-heights-16': 72,
  'cre8-font-weights-aeonik-0': '400',
  'cre8-font-weights-aeonik-1': '300',
  'cre8-font-weights-aeonik-2': '700',
  'cre8-font-size-0': 12,
  'cre8-font-size-1': 14,
  'cre8-font-size-2': 16,
  'cre8-font-size-3': 18,
  'cre8-font-size-4': 20,
  'cre8-font-size-5': 24,
  'cre8-font-size-6': 28,
  'cre8-font-size-7': 32,
  'cre8-font-size-8': 40,
  'cre8-font-size-9': 48,
  'cre8-font-size-10': 56,
  'cre8-font-size-11': 64,
  'cre8-font-size-12': 72,
  'cre8-font-size-13': 80,
  'cre8-letter-spacing-0': 0,
  'cre8-letter-spacing-1': -0.5,
  'cre8-letter-spacing-2': 0,
  'cre8-letter-spacing-3': 1,
  'cre8-letter-spacing-4': -1.5,
  'cre8-letter-spacing-5': -1,
  'cre8-paragraph-spacing-0': 0,
  'cre8-text-case-none': 'none',
  'cre8-text-case-uppercase': 'uppercase',
  'cre8-text-decoration-none': 'none',
  'cre8-text-decoration-underline': 'underline',
  'cre8-icon-size-small': 14,
  'cre8-icon-size-default': 16,
  'cre8-icon-size-large': 16,
  'cre8-border-width-button-tertiary-outline-focus': 1,
  'cre8-border-width-button-default': 1,
  'cre8-border-width-tab-selected': 2,
  'cre8-border-width-tab-default': 2,
  'cre8-border-width-none': 0,
  'cre8-border-width-default': 1,
  'cre8-border-width-focus': 2,
  'cre8-border-width-large': 4,
  'cre8-border-style-button-tertiary-outline-focus': 'dashed',
  'cre8-border-style-default': 'solid',
  'cre8-badge-padding-horizontal': 16,
  'cre8-badge-padding-vertical': 4,
  'cre8-progress-meter-height': 8,
  'cre8-breakpoint-xsm': '375px',
  'cre8-breakpoint-sm': '560px',
  'cre8-breakpoint-md': '768px',
  'cre8-breakpoint-lg': '960px',
  'cre8-breakpoint-xl': '1200px',
  'cre8-breakpoint-xxl': '1400px',
  'cre8-asset-font-aeonik-300-normal': 'Aeonik-Light',
  'cre8-asset-font-aeonik-400-normal': 'Aeonik-Regular',
  'cre8-asset-font-aeonik-700-normal': 'Aeonik-Bold'
}