/**
 * Query-time semantic search for search_components.
 *
 * catalog-embeddings.json (generated by cre8-wc's a2ui/generate-embeddings.mjs,
 * a manual step — see that file's header) ships one OpenAI
 * text-embedding-3-small vector per component, built from the same knowledge
 * graph loadKG() reads. At query time this embeds the search string with the
 * same model and ranks components by cosine similarity.
 *
 * Requires OPENAI_API_KEY. Every failure mode here — no key, no committed
 * embeddings file, a failed API call — is treated as "semantic search isn't
 * available right now," never as a tool error: handleSearchComponents falls
 * back to lexical matching whenever this returns null.
 */
import { readFileSync, existsSync } from 'node:fs';
import { createRequire } from 'node:module';

interface EmbeddingVector {
  text_hash: string;
  model: string;
  dims: number;
  vector: number[];
}

interface CatalogEmbeddings {
  meta: {
    model: string;
    dims: number;
    library_version: string;
    component_count: number;
  };
  vectors: Record<string, EmbeddingVector>;
}

export interface SemanticMatch {
  id: string;
  score: number;
}

const EMBEDDING_ENDPOINT = 'https://api.openai.com/v1/embeddings';
const TOP_N = 8;
const MIN_SCORE = 0.2;

let _cache: CatalogEmbeddings | null | undefined;

/** Resolves and parses catalog-embeddings.json. Returns null (and caches
 * that) if it hasn't been generated yet — an expected state, not an error. */
function loadEmbeddings(): CatalogEmbeddings | null {
  if (_cache !== undefined) return _cache;

  let path: string | null = null;
  if (process.env.CRE8_WC_ROOT) {
    const candidate = `${process.env.CRE8_WC_ROOT}/a2ui/catalog-embeddings.json`;
    if (existsSync(candidate)) path = candidate;
  } else {
    try {
      path = createRequire(import.meta.url).resolve('@tmorrow/cre8-wc/a2ui/catalog-embeddings.json');
    } catch {
      path = null;
    }
  }

  _cache = path ? (JSON.parse(readFileSync(path, 'utf-8')) as CatalogEmbeddings) : null;
  return _cache;
}

async function embedQuery(query: string, model: string, dims: number): Promise<number[]> {
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) throw new Error('OPENAI_API_KEY is not set');

  const res = await fetch(EMBEDDING_ENDPOINT, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify({ model, dimensions: dims, input: query }),
  });

  if (!res.ok) {
    const body = await res.text().catch(() => '');
    throw new Error(`OpenAI embeddings request failed: ${res.status} ${res.statusText} ${body}`);
  }

  const json = (await res.json()) as { data?: Array<{ embedding: number[] }> };
  const vector = json.data?.[0]?.embedding;
  if (!vector) throw new Error('OpenAI embeddings response had no vector');
  return vector;
}

function cosineSimilarity(a: number[], b: number[]): number {
  let dot = 0;
  let na = 0;
  let nb = 0;
  for (let i = 0; i < a.length; i++) {
    dot += a[i] * b[i];
    na += a[i] * a[i];
    nb += b[i] * b[i];
  }
  if (na === 0 || nb === 0) return 0;
  return dot / (Math.sqrt(na) * Math.sqrt(nb));
}

/**
 * Ranks catalog components by cosine similarity to `query`.
 *
 * Returns null — never [] — when semantic search couldn't run at all (no
 * embeddings file, no API key, request failure), so the caller can tell
 * "tried and found nothing above the threshold" (empty array, a real
 * answer) apart from "couldn't try" (null, fall back to lexical).
 */
export async function semanticSearch(query: string): Promise<SemanticMatch[] | null> {
  const catalog = loadEmbeddings();
  if (!catalog || !process.env.OPENAI_API_KEY) return null;

  let queryVector: number[];
  try {
    queryVector = await embedQuery(query, catalog.meta.model, catalog.meta.dims);
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    console.error(`[cre8-mcp] semantic search unavailable, falling back to lexical match: ${message}`);
    return null;
  }

  return Object.entries(catalog.vectors)
    .map(([id, v]) => ({ id, score: cosineSimilarity(queryVector, v.vector) }))
    .filter((m) => m.score >= MIN_SCORE)
    .sort((a, b) => b.score - a.score)
    .slice(0, TOP_N);
}
