/**
 * Cre8 MCP Tool Handlers
 *
 * Functions that implement the Cre8 Design System MCP tools.
 * Supports both Web Components (default) and React formats.
 */

import { readFileSync } from 'fs';
import { createRequire } from 'module';
import {
  registerCatalog,
  validateSpec,
  type CatalogSchema,
  type RegisteredCatalog,
} from '@tmorrow/cre8-wc/a2ui/index.js';

// ─── Knowledge Graph types & loader ─────────────────────────────────────────

interface KGProp {
  type: string;
  enum: string[] | null;
  default: unknown;
  description: string;
  'x-kind': string;
}

export interface KGSpecNode {
  component: string;
  props?: Record<string, unknown>;
  children?: (KGSpecNode | string)[];
  slots?: Record<string, (KGSpecNode | string)[]>;
  events?: Record<string, unknown>;
}

export interface KGNode {
  id: string;
  type: 'component' | 'category' | 'enum_prop' | 'slot' | 'pattern';
  category?: string | null;
  description?: string;
  name?: string;
  component?: string;
  props?: Record<string, KGProp>;
  slots?: string[];
  accepts_children?: boolean;
  enum?: string[];
  /** Base class from the AST graph (Cre8Element, Cre8FormElement, …). */
  extends?: string | null;
  /** Smallest authored A2UI subtree rooted at this component. */
  exemplar?: { source: string; path: string; spec: KGSpecNode } | null;
  /** pattern nodes only */
  source?: string;
  spec?: KGSpecNode;
  components?: string[];
}

export type KGEvidenceKind = 'story' | 'source' | 'example' | 'pattern';

export interface KGEdge {
  from: string;
  to: string;
  rel: 'BELONGS_TO' | 'HAS_ENUM_PROP' | 'HAS_SLOT' | 'CONTAINS' | 'IN_FAMILY' | 'EXTENDS' | 'IMPORTS' | 'USED_IN_PATTERN';
  /** CONTAINS only: the A2UI slot, or null for `children`. */
  slot?: string | null;
  /** CONTAINS only: occurrences across all evidence. */
  count?: number;
  /** CONTAINS only: the shipped artifacts that demonstrate this nesting. */
  evidence?: Array<{ kind: KGEvidenceKind; file: string }>;
}

export interface KGMeta {
  generated_from: string[];
  catalog_id: string;
  library: string;
  library_version: string;
  graphify_commit: string | null;
  evidence: { story_files: number; source_files: number; example_files: string[]; pattern_files?: string[] };
  total_nodes: number;
  total_edges: number;
  contains_edges: number;
}

export interface KG {
  meta: KGMeta;
  components: Map<string, KGNode>;
  patterns: KGNode[];
  nodesById: Map<string, KGNode>;
  edgesFrom: Map<string, KGEdge[]>;
  edgesTo: Map<string, KGEdge[]>;
}

let _kgCache: KG | null = null;

/**
 * The knowledge graph generated by packages/cre8-wc/a2ui/generate-catalog-kg.mjs.
 * Every structural answer this server gives comes from here; nothing
 * re-derives nesting from examples or names at runtime.
 */
export function loadKG(): KG {
  if (_kgCache) return _kgCache;
  const req = createRequire(import.meta.url);
  const kgPath = process.env.CRE8_WC_ROOT
    ? `${process.env.CRE8_WC_ROOT}/a2ui/catalog-kg.json`
    : req.resolve('@tmorrow/cre8-wc/a2ui/catalog-kg.json');
  const kg: { meta: KGMeta; nodes: KGNode[]; edges: KGEdge[] } = JSON.parse(readFileSync(kgPath, 'utf-8'));

  const nodesById = new Map(kg.nodes.map((n) => [n.id, n]));
  const components = new Map(
    kg.nodes.filter((n) => n.type === 'component').map((n) => [n.id, n]),
  );
  const patterns = kg.nodes.filter((n) => n.type === 'pattern');
  const edgesFrom = new Map<string, KGEdge[]>();
  const edgesTo = new Map<string, KGEdge[]>();
  for (const edge of kg.edges) {
    if (!edgesFrom.has(edge.from)) edgesFrom.set(edge.from, []);
    edgesFrom.get(edge.from)!.push(edge);
    if (!edgesTo.has(edge.to)) edgesTo.set(edge.to, []);
    edgesTo.get(edge.to)!.push(edge);
  }

  _kgCache = { meta: kg.meta, components, patterns, nodesById, edgesFrom, edgesTo };
  return _kgCache;
}

// Format type
export type ComponentFormat = 'web' | 'react';

// The manifest (mcp-manifest.json / react-manifest.json) is no longer read
// here. Components, categories, composition and patterns all come from the
// knowledge graph; generate-catalog.mjs consumes the manifest at build time.

// Tool Input Types
export interface ListComponentsInput {
  category?: string;
  format?: ComponentFormat;
}

export interface GetComponentInput {
  name: string;
  format?: ComponentFormat;
}

export interface GetPatternsInput {
  name?: string;
  format?: ComponentFormat;
}

export interface GenerateCodeInput {
  schema: ComponentNode | ComponentNode[];
  format?: ComponentFormat;
  indent?: number;
}

interface ComponentNode {
  component: string;
  props?: Record<string, unknown>;
  children?: string | ComponentNode | ComponentNode[];
  slots?: Record<string, string | ComponentNode | ComponentNode[]>;
  content?: string;
}

/**
 * list_components - Lists all available Cre8 components (KG-backed)
 */
export function handleListComponents(input: ListComponentsInput): string {
  const { components } = loadKG();
  let comps = Array.from(components.values());

  if (input.category) {
    comps = comps.filter(
      (c) => (c.category ?? '').toLowerCase() === input.category!.toLowerCase(),
    );
  }

  const grouped: Record<string, Array<{ name: string; description: string }>> = {};
  for (const comp of comps) {
    const cat = comp.category ?? 'Uncategorized';
    if (!grouped[cat]) grouped[cat] = [];
    grouped[cat].push({
      name: comp.id,
      description: (comp.description ?? '').slice(0, 160),
    });
  }

  return JSON.stringify({
    format: input.format ?? 'web',
    library: '@tmorrow/cre8-wc',
    categories: Object.entries(grouped).map(([category, items]) => ({ category, components: items })),
    totalComponents: comps.length,
  }, null, 2);
}

/**
 * get_component - Gets detailed info for a specific component (KG-backed)
 */
export function handleGetComponent(input: GetComponentInput): string {
  const { components, edgesFrom, nodesById } = loadKG();

  const searchName = input.name.toLowerCase().replace(/^cre8-?/, '').replace(/-/g, '');

  let comp =
    components.get(input.name.toLowerCase()) ??
    components.get(`cre8-${input.name.toLowerCase()}`);

  if (!comp) {
    comp = Array.from(components.values()).find((c) => {
      const cn = c.id.toLowerCase().replace(/^cre8-/, '').replace(/-/g, '');
      return cn === searchName;
    });
  }

  if (!comp) {
    return JSON.stringify({
      error: `Component "${input.name}" not found`,
      suggestion: 'Use list_components to see available components',
    });
  }

  const edges = edgesFrom.get(comp.id) ?? [];
  const slots = edges
    .filter((e) => e.rel === 'HAS_SLOT')
    .map((e) => nodesById.get(e.to))
    .filter(Boolean)
    .map((s) => ({ name: (s as KGNode).name!, description: (s as KGNode).description ?? '' }));

  const shortName = comp.id.replace('cre8-', '');
  const format = input.format ?? 'web';
  // cre8-button → Cre8Button (matches generate_code's tag conversion)
  const reactName = 'Cre8' + shortName
    .split('-')
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join('');

  return JSON.stringify({
    format,
    name: format === 'react' ? reactName : comp.id,
    tagName: comp.id,
    category: comp.category ?? 'Uncategorized',
    description: comp.description ?? '',
    import: format === 'react'
      ? `import { ${reactName} } from '@tmorrow/cre8-react';`
      : `import '@tmorrow/cre8-wc/lib/components/${shortName}/${shortName}.js';`,
    props: comp.props ?? {},
    slots,
    accepts_children: comp.accepts_children ?? false,
    extends: comp.extends ?? null,
    // Structural facts come from the graph's CONTAINS edges, each of which
    // names the shipped artifact that demonstrates it.
    contains: (edgesFrom.get(comp.id) ?? [])
      .filter((e) => e.rel === 'CONTAINS')
      .map((e) => ({ component: e.to, slot: e.slot ?? null, count: e.count ?? 0 })),
    containedBy: [...new Set((loadKG().edgesTo.get(comp.id) ?? []).filter((e) => e.rel === 'CONTAINS').map((e) => e.from))].sort(),
  }, null, 2);
}

/**
 * get_patterns - Layout patterns (KG-backed)
 *
 * Patterns are authored A2UI specs (a2ui/patterns/*.json) that the graph
 * validated against the catalog at build time. The template for either
 * format is rendered from the spec here, the same way generate_code renders
 * anything else, so web and React can never drift from each other or from
 * the spec.
 */
export function handleGetPatterns(input: GetPatternsInput): string {
  const format = input.format || 'web';
  const { patterns } = loadKG();

  const render = (p: KGNode) => {
    const generated = JSON.parse(handleGenerateCode({ schema: p.spec as ComponentNode, format })) as { code?: string };
    return {
      format,
      name: p.name,
      description: p.description,
      source: p.source,
      components: p.components ?? [],
      spec: p.spec,
      template: generated.code ?? '',
    };
  };

  if (input.name) {
    const wanted = input.name.toLowerCase();
    const pattern = patterns.find(
      (p) => (p.name ?? '').toLowerCase() === wanted || p.id === `pattern:${wanted}` || p.id.replace(/^pattern:/, '') === wanted.replace(/\s+/g, '-'),
    );

    if (!pattern) {
      return JSON.stringify({
        error: `Pattern "${input.name}" not found`,
        available: patterns.map((p) => p.name),
      });
    }

    return JSON.stringify(render(pattern), null, 2);
  }

  return JSON.stringify({
    format,
    source: 'a2ui/patterns — authored A2UI specs, validated against the catalog when the knowledge graph is built',
    patterns: patterns.map((p) => ({
      name: p.name,
      description: p.description,
      components: p.components ?? [],
    })),
  }, null, 2);
}

/**
 * generate_code - Generates React or Web Component code from a JSON schema
 */
export function handleGenerateCode(input: GenerateCodeInput): string {
  const format = input.format || 'web';
  const baseIndent = input.indent || 0;

  function generateNode(node: ComponentNode | string, indentLevel: number): string {
    const indent = '  '.repeat(indentLevel);

    // Handle string content
    if (typeof node === 'string') {
      return `${indent}${node}`;
    }

    // Get component name in correct format
    let tagName = node.component;

    // Check if this is a plain HTML element (not a cre8 component)
    const htmlTags = new Set([
      'a', 'abbr', 'article', 'aside', 'b', 'blockquote', 'br', 'button',
      'caption', 'cite', 'code', 'col', 'colgroup', 'dd', 'details', 'div',
      'dl', 'dt', 'em', 'fieldset', 'figcaption', 'figure', 'form', 'h1',
      'h2', 'h3', 'h4', 'h5', 'h6', 'header', 'hr', 'i', 'iframe', 'img',
      'input', 'label', 'legend', 'li', 'main', 'mark', 'nav', 'ol', 'option',
      'p', 'pre', 'section', 'select', 'small', 'span', 'strong', 'sub',
      'summary', 'sup', 'table', 'tbody', 'td', 'textarea', 'tfoot', 'th',
      'thead', 'time', 'tr', 'u', 'ul', 'video',
    ]);
    const isHtmlElement = htmlTags.has(tagName.toLowerCase());

    // Only normalize cre8 component names, leave HTML tags as-is
    if (!isHtmlElement) {
      if (format === 'react') {
        // Ensure React format: Cre8Button
        if (!tagName.startsWith('Cre8')) {
          tagName = tagName.startsWith('cre8-')
            ? 'Cre8' + tagName.slice(5).split('-').map(s => s.charAt(0).toUpperCase() + s.slice(1)).join('')
            : 'Cre8' + tagName.charAt(0).toUpperCase() + tagName.slice(1);
        }
      } else {
        // Ensure Web Component format: cre8-button
        if (!tagName.startsWith('cre8-')) {
          tagName = tagName.startsWith('Cre8')
            ? 'cre8-' + tagName.slice(4).replace(/([A-Z])/g, '-$1').toLowerCase().slice(1)
            : 'cre8-' + tagName.toLowerCase();
        }
      }
    }

    // Build props/attributes string
    let propsStr = '';
    if (node.props) {
      const propEntries = Object.entries(node.props);
      for (const [key, value] of propEntries) {
        let propName = key;

        // Convert prop names for web components (camelCase -> kebab-case)
        if (format === 'web' && /[A-Z]/.test(key)) {
          propName = key.replace(/([A-Z])/g, '-$1').toLowerCase();
        }

        // Format the value
        if (typeof value === 'boolean') {
          if (value) {
            propsStr += ` ${propName}`;
          }
        } else if (typeof value === 'string') {
          propsStr += ` ${propName}="${value}"`;
        } else if (typeof value === 'number') {
          propsStr += format === 'react' ? ` ${propName}={${value}}` : ` ${propName}="${value}"`;
        } else if (typeof value === 'object') {
          propsStr += format === 'react' ? ` ${propName}={${JSON.stringify(value)}}` : ` ${propName}='${JSON.stringify(value)}'`;
        }
      }
    }

    // Check for children/content
    const hasChildren = node.children || node.content || node.slots;

    if (!hasChildren) {
      // Self-closing tag
      return format === 'react'
        ? `${indent}<${tagName}${propsStr} />`
        : `${indent}<${tagName}${propsStr}></${tagName}>`;
    }

    // Build children
    const childLines: string[] = [];

    // Handle content
    if (node.content) {
      childLines.push(`${'  '.repeat(indentLevel + 1)}${node.content}`);
    }

    // Handle children
    if (node.children) {
      const children = Array.isArray(node.children) ? node.children : [node.children];
      for (const child of children) {
        childLines.push(generateNode(child, indentLevel + 1));
      }
    }

    // Handle slots
    if (node.slots) {
      for (const [slotName, slotContent] of Object.entries(node.slots)) {
        const slotChildren = Array.isArray(slotContent) ? slotContent : [slotContent];
        for (const child of slotChildren) {
          if (typeof child === 'string') {
            if (format === 'react') {
              childLines.push(`${'  '.repeat(indentLevel + 1)}{/* slot: ${slotName} */}`);
              childLines.push(`${'  '.repeat(indentLevel + 1)}${child}`);
            } else if (slotName === 'default') {
              childLines.push(`${'  '.repeat(indentLevel + 1)}${child}`);
            } else {
              childLines.push(`${'  '.repeat(indentLevel + 1)}<span slot="${slotName}">${child}</span>`);
            }
          } else {
            const childCode = generateNode(child, indentLevel + 1);
            if (format === 'web' && slotName !== 'default') {
              // Add slot attribute for web components
              const slotAttr = ` slot="${slotName}"`;
              const firstTagEnd = childCode.indexOf('>');
              if (firstTagEnd > 0) {
                childLines.push(childCode.slice(0, firstTagEnd) + slotAttr + childCode.slice(firstTagEnd));
              } else {
                childLines.push(childCode);
              }
            } else {
              childLines.push(childCode);
            }
          }
        }
      }
    }

    // Combine
    const openTag = `${indent}<${tagName}${propsStr}>`;
    const closeTag = `${indent}</${tagName}>`;

    if (childLines.length === 1 && !childLines[0].includes('\n') && childLines[0].trim().length < 40) {
      // Single short child - inline
      return `${indent}<${tagName}${propsStr}>${childLines[0].trim()}</${tagName}>`;
    }

    return `${openTag}\n${childLines.join('\n')}\n${closeTag}`;
  }

  // Handle array of nodes
  if (Array.isArray(input.schema)) {
    const lines = input.schema.map(node => generateNode(node, baseIndent));
    return JSON.stringify({
      format,
      code: lines.join('\n'),
    }, null, 2);
  }

  // Single node
  const code = generateNode(input.schema, baseIndent);
  return JSON.stringify({
    format,
    code,
  }, null, 2);
}

// ─── A2UI catalog tools ──────────────────────────────────────────────

let registeredCatalogCache: RegisteredCatalog | null = null;

export function loadA2uiCatalog(): RegisteredCatalog {
  if (registeredCatalogCache) return registeredCatalogCache;
  const require = createRequire(import.meta.url);
  const catalogPath = require.resolve('@tmorrow/cre8-wc/a2ui/catalog.json');
  const schema = JSON.parse(readFileSync(catalogPath, 'utf-8')) as CatalogSchema;
  registeredCatalogCache = registerCatalog(schema);
  return registeredCatalogCache;
}

function normalizeComponentName(name: string): string {
  return name.startsWith('cre8-') ? name : `cre8-${name}`;
}

export interface GetA2uiCatalogInput {
  view?: 'metadata' | 'component' | 'full';
  component?: string;
}

export function handleGetA2uiCatalog(input: GetA2uiCatalogInput): string {
  const catalog = loadA2uiCatalog();
  const view = input.view ?? 'metadata';

  if (view === 'full') {
    return JSON.stringify(catalog.schema, null, 2);
  }

  if (view === 'component') {
    if (!input.component) {
      throw new Error('view="component" requires a `component` argument');
    }
    const tag = normalizeComponentName(input.component);
    const def = catalog.components.get(tag);
    if (!def) {
      const available = Array.from(catalog.components.keys()).sort().join(', ');
      throw new Error(
        `Component "${tag}" not found in A2UI catalog. Available: ${available}`
      );
    }
    return JSON.stringify({ component: tag, definition: def }, null, 2);
  }

  // metadata (default)
  const meta = catalog.schema['x-a2ui'] ?? {};
  const components = Array.from(catalog.components.entries()).map(
    ([tag, def]) => ({
      name: tag,
      category: def['x-category'] ?? 'Uncategorized',
      description: (def.description ?? '').split('\n')[0].slice(0, 160),
      slotNames: def.properties?.slots?.properties
        ? Object.keys(def.properties.slots.properties)
        : def.properties?.children
          ? ['children']
          : [],
    })
  );
  return JSON.stringify(
    {
      catalogId: catalog.id,
      ...meta,
      totalComponents: components.length,
      components,
    },
    null,
    2
  );
}

export interface ValidateA2uiSpecInput {
  spec: unknown;
}

export function handleValidateA2uiSpec(input: ValidateA2uiSpecInput): string {
  const catalog = loadA2uiCatalog();
  try {
    validateSpec(input.spec, catalog);
    return JSON.stringify({ ok: true }, null, 2);
  } catch (e) {
    const message = e instanceof Error ? e.message : String(e);
    return JSON.stringify({ ok: false, error: message }, null, 2);
  }
}
