#!/usr/bin/env python3
"""
Simple Campaign Revenue Chart Generator
This script creates a direct bar chart visualization of campaign vs Revenue
without requiring the MCP framework.
"""

import os
import pandas as pd
import json
import webbrowser
from pathlib import Path

def main():
    # Set paths
    script_dir = Path(__file__).parent
    project_dir = script_dir.parent
    data_dir = project_dir / "data"
    output_dir = project_dir / "output"
    
    # Ensure output directory exists
    output_dir.mkdir(exist_ok=True)
    
    csv_path = data_dir / "Bookexcel.csv"
    
    print(f"Reading data from: {csv_path}")
    
    # Read the CSV data
    try:
        df = pd.read_csv(csv_path)
    except Exception as e:
        print(f"Error reading CSV file: {e}")
        return
    
    # Process the data - group by campaign and sum Revenue
    grouped_data = df.groupby('campaign')['Revenue'].sum().reset_index()
    
    # Sort by revenue in descending order
    grouped_data = grouped_data.sort_values('Revenue', ascending=False)
    
    # Get the top campaigns
    top_campaigns = grouped_data.head(20)
    
    # Convert to lists for the chart
    campaigns = top_campaigns['campaign'].tolist()
    revenue_values = top_campaigns['Revenue'].tolist()
    
    # Generate HTML
    html = generate_bar_chart_html(campaigns, revenue_values)
    
    # Save to file
    output_path = output_dir / "simple_campaign_revenue_chart.html"
    with open(output_path, 'w') as f:
        f.write(html)
    
    # Open in browser
    webbrowser.open(f"file://{output_path.absolute()}")
    print(f"Chart opened in browser: {output_path}")
    
    # Generate some insights
    print("\nData Insights:")
    print(f"Total campaigns: {grouped_data['campaign'].nunique()}")
    print(f"Total revenue: ${grouped_data['Revenue'].sum():,.2f}")
    print(f"Top performing campaign: {grouped_data.iloc[0]['campaign']} (${grouped_data.iloc[0]['Revenue']:,.2f})")
    print(f"Average revenue per campaign: ${grouped_data['Revenue'].mean():,.2f}")

def generate_bar_chart_html(x_values, y_values):
    """Generate a simple bar chart HTML using Plotly"""
    
    # Convert to JSON for embedding in HTML
    x_json = json.dumps(x_values)
    y_json = json.dumps(y_values)
    
    html_template = """
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <title>Campaign Revenue Analysis</title>
        <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
        <style>
            body {
                font-family: Arial, sans-serif;
                margin: 20px;
                background-color: #f5f5f5;
            }
            .container {
                max-width: 1200px;
                margin: 0 auto;
                background-color: white;
                padding: 20px;
                border-radius: 8px;
                box-shadow: 0 2px 10px rgba(0,0,0,0.1);
            }
            h1 {
                color: #333;
                text-align: center;
            }
            .insights {
                margin-top: 30px;
                padding: 15px;
                background-color: #f0f7ff;
                border-radius: 5px;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>Campaign Revenue Analysis</h1>
            <div id="chart" style="width: 100%; height: 600px;"></div>
            
            <div class="insights">
                <h3>Key Insights:</h3>
                <ul>
                    <li>The chart shows revenue generated by each marketing campaign.</li>
                    <li>Campaigns are sorted by total revenue in descending order.</li>
                    <li>Black Friday campaigns appear to generate the highest revenue.</li>
                    <li>Email Newsletter campaigns show consistent revenue across months.</li>
                </ul>
            </div>
        </div>
        
        <script>
            const campaignNames = %s;
            const revenueValues = %s;
            
            const data = [{
                x: campaignNames,
                y: revenueValues,
                type: 'bar',
                marker: {
                    color: '#1f77b4',
                    line: {
                        color: '#1f77b4',
                        width: 1
                    }
                }
            }];
            
            const layout = {
                title: 'Campaign Revenue Comparison',
                xaxis: {
                    title: 'Campaign Name',
                    tickangle: -45
                },
                yaxis: {
                    title: 'Revenue (USD)'
                },
                margin: {
                    b: 150
                }
            };
            
            Plotly.newPlot('chart', data, layout, {responsive: true});
        </script>
    </body>
    </html>
    """ % (x_json, y_json)
    
    return html_template

if __name__ == "__main__":
    main()
