/**
 * Do not edit directly
 * Generated on Wed, 12 Nov 2025 07:11:37 GMT
 */


module.exports = {
  'cre8-desktop-menu-padding-vertical-padding': 16,
  'cre8-desktop-menu-padding-horizontal-padding': 8,
  'cre8-color-header-bg-default': '#ffffff',
  'cre8-color-header-inverse-bg-default': '#15AABF',
  'cre8-color-header-menu-bg-default': '#ffffff',
  'cre8-color-header-menu-inverse-bg-default': '#15AABF',
  'cre8-color-header-menu-bg-hover': '#f6f5f3',
  'cre8-color-header-menu-inverse-bg-hover': '#1098AD',
  'cre8-color-header-menu-bg-focus': '#f6f5f3',
  'cre8-color-header-menu-inverse-bg-focus': '#1098AD',
  'cre8-color-header-menu-bg-active': '#edebe7',
  'cre8-color-header-menu-inverse-bg-active': '#0C8599',
  'cre8-color-header-menu-bg-pressed': '#edebe7',
  'cre8-color-header-menu-inverse-bg-pressed': '#0C8599',
  'cre8-color-header-menu-bg-selected': '#f6f5f3',
  'cre8-color-header-menu-inverse-bg-selected': '#1098AD',
  'cre8-color-header-menu-content-default': '#15AABF',
  'cre8-color-header-menu-inverse-content-default': '#ffffff',
  'cre8-color-header-menu-content-hover': '#1098AD',
  'cre8-color-header-menu-inverse-content-hover': '#ffffff',
  'cre8-color-header-menu-content-focus': '#15AABF',
  'cre8-color-header-menu-inverse-content-focus': '#ffffff',
  'cre8-color-header-menu-content-active': '#0C8599',
  'cre8-color-header-menu-inverse-content-active': '#ffffff',
  'cre8-color-header-menu-content-pressed': '#0C8599',
  'cre8-color-header-menu-inverse-content-pressed': '#ffffff',
  'cre8-color-header-menu-content-selected': '#1098AD',
  'cre8-color-header-menu-inverse-content-selected': '#ffffff',
  'cre8-color-header-menu-border-default': 'rgba( #2d2d2d,0.0)',
  'cre8-color-header-menu-inverse-border-default': 'rgba( #2d2d2d,0.0)',
  'cre8-color-header-menu-border-hover': 'rgba( #2d2d2d,0.0)',
  'cre8-color-header-menu-inverse-border-hover': '#ffffff',
  'cre8-color-header-menu-border-focus': '#1098AD',
  'cre8-color-header-menu-inverse-border-focus': '#ffffff',
  'cre8-color-header-menu-border-active': '#15AABF',
  'cre8-color-header-menu-inverse-border-active': '#ffffff',
  'cre8-color-header-menu-border-pressed': '#15AABF',
  'cre8-color-header-menu-inverse-border-pressed': '#ffffff',
  'cre8-color-header-menu-border-selected': '#1098AD',
  'cre8-color-header-menu-inverse-border-selected': '#f6f5f3',
  'cre8-color-header-submenu-bg-default': '#ffffff',
  'cre8-color-header-submenu-inverse-bg-default': '#15AABF',
  'cre8-color-header-submenu-bg-hover': '#f6f5f3',
  'cre8-color-header-submenu-inverse-bg-hover': '#1098AD',
  'cre8-color-header-submenu-bg-focus': '#ffffff',
  'cre8-color-header-submenu-inverse-bg-focus': '#15AABF',
  'cre8-color-header-submenu-bg-active': '#edebe7',
  'cre8-color-header-submenu-inverse-bg-active': '#0C8599',
  'cre8-color-header-submenu-bg-pressed': '#edebe7',
  'cre8-color-header-submenu-inverse-bg-pressed': '#0C8599',
  'cre8-color-header-submenu-bg-selected': '#f6f5f3',
  'cre8-color-header-submenu-inverse-bg-selected': '#1098AD',
  'cre8-color-header-submenu-content-default': '#15AABF',
  'cre8-color-header-submenu-inverse-content-default': '#ffffff',
  'cre8-color-header-submenu-content-hover': '#1098AD',
  'cre8-color-header-submenu-inverse-content-hover': '#ffffff',
  'cre8-color-header-submenu-content-focus': '#1098AD',
  'cre8-color-header-submenu-inverse-content-focus': '#ffffff',
  'cre8-color-header-submenu-content-active': '#0C8599',
  'cre8-color-header-submenu-inverse-content-active': '#ffffff',
  'cre8-color-header-submenu-content-pressed': '#0C8599',
  'cre8-color-header-submenu-inverse-content-pressed': '#ffffff',
  'cre8-color-header-submenu-content-selected': '#15AABF',
  'cre8-color-header-submenu-inverse-content-selected': '#ffffff',
  'cre8-color-header-submenu-border-default': '#ffffff',
  'cre8-color-header-submenu-inverse-border-default': '#15AABF',
  'cre8-color-header-submenu-border-hover': '#f6f5f3',
  'cre8-color-header-submenu-inverse-border-hover': '#1098AD',
  'cre8-color-header-submenu-border-focus': '#15AABF',
  'cre8-color-header-submenu-inverse-border-focus': '#ffffff',
  'cre8-color-header-submenu-border-active': '#edebe7',
  'cre8-color-header-submenu-inverse-border-active': '#0C8599',
  'cre8-color-header-submenu-border-pressed': '#edebe7',
  'cre8-color-header-submenu-inverse-border-pressed': '#0C8599',
  'cre8-color-header-submenu-border-selected': '#1098AD',
  'cre8-color-header-submenu-inverse-border-selected': '#f6f5f3',
  'cre8-color-header-bg-secondary': '#15AABF',
  'cre8-color-header-inverse-bg-secondary': '#ffffff',
  'cre8-color-header-bg-tertiary': '#15AABF',
  'cre8-color-header-inverse-bg-tertiary': '#ffffff',
  'cre8-color-footer-bg-default': '#15AABF',
  'cre8-color-footer-bg-secondary': '#f6f5f3',
  'cre8-color-footer-content-secondary': '#ffffff',
  'cre8-color-footer-link-hover': '#0C8599',
  'cre8-color-footer-link-default': '#0C8599',
  'cre8-spacing-0': 0,
  'cre8-spacing-2': 2,
  'cre8-spacing-4': 4,
  'cre8-spacing-6': 6,
  'cre8-spacing-8': 8,
  'cre8-spacing-12': 12,
  'cre8-spacing-14': 14,
  'cre8-spacing-16': 16,
  'cre8-spacing-18': 18,
  'cre8-spacing-24': 24,
  'cre8-spacing-32': 32,
  'cre8-spacing-40': 40,
  'cre8-spacing-48': 48,
  'cre8-spacing-64': 64,
  'cre8-spacing-80': 80,
  'cre8-spacing-96': 96,
  'cre8-spacing-120': 120,
  'cre8-spacing-160': 160,
  'cre8-color-button-primary-bg': '#15AABF',
  'cre8-color-button-primary-inverse-bg': '#F3D9FA',
  'cre8-color-button-primary-bg-hover': '#1098AD',
  'cre8-color-button-primary-inverse-bg-hover': '#EEBEFA',
  'cre8-color-button-primary-bg-active': '#0C8599',
  'cre8-color-button-primary-inverse-bg-active': '#E599F7',
  'cre8-color-button-primary-bg-disabled': '#eaeaea',
  'cre8-color-button-primary-inverse-bg-disabled': '#ababab',
  'cre8-color-button-primary-content': '#ffffff',
  'cre8-color-button-primary-inverse-content': '#1098AD',
  'cre8-color-button-primary-content-hover': '#ffffff',
  'cre8-color-button-primary-inverse-content-hover': '#1098AD',
  'cre8-color-button-primary-content-active': '#ffffff',
  'cre8-color-button-primary-inverse-content-active': '#1098AD',
  'cre8-color-button-primary-content-disabled': '#949494',
  'cre8-color-button-primary-inverse-content-disabled': '#6c6c6c',
  'cre8-color-button-primary-border': '#15AABF',
  'cre8-color-button-primary-inverse-border': '#F3D9FA',
  'cre8-color-button-primary-border-hover': '#1098AD',
  'cre8-color-button-primary-inverse-border-hover': '#EEBEFA',
  'cre8-color-button-primary-border-active': '#0C8599',
  'cre8-color-button-primary-inverse-border-active': '#E599F7',
  'cre8-color-button-primary-border-disabled': '#eaeaea',
  'cre8-color-button-primary-inverse-border-disabled': '#ababab',
  'cre8-color-button-primary-outline': '#0C8599',
  'cre8-color-button-primary-inverse-outline': '#F3D9FA',
  'cre8-color-button-primary-danger-bg': '#d02525',
  'cre8-color-button-primary-danger-inverse-bg': '#f88181',
  'cre8-color-button-primary-danger-bg-hover': '#aa1313',
  'cre8-color-button-primary-danger-inverse-bg-hover': '#f5a8a8',
  'cre8-color-button-primary-danger-bg-active': '#7a0000',
  'cre8-color-button-primary-danger-inverse-bg-active': '#fccaca',
  'cre8-color-button-primary-danger-bg-disabled': '#eaeaea',
  'cre8-color-button-primary-danger-inverse-bg-disabled': '#ababab',
  'cre8-color-button-primary-danger-content': '#ffffff',
  'cre8-color-button-primary-danger-inverse-content': '#2d2d2d',
  'cre8-color-button-primary-danger-content-hover': '#ffffff',
  'cre8-color-button-primary-danger-inverse-content-hover': '#2d2d2d',
  'cre8-color-button-primary-danger-content-active': '#ffffff',
  'cre8-color-button-primary-danger-inverse-content-active': '#2d2d2d',
  'cre8-color-button-primary-danger-content-disabled': '#949494',
  'cre8-color-button-primary-danger-inverse-content-disabled': '#6c6c6c',
  'cre8-color-button-primary-danger-border': '#d02525',
  'cre8-color-button-primary-danger-inverse-border': '#f88181',
  'cre8-color-button-primary-danger-border-hover': '#aa1313',
  'cre8-color-button-primary-danger-inverse-border-hover': '#f5a8a8',
  'cre8-color-button-primary-danger-border-active': '#7a0000',
  'cre8-color-button-primary-danger-inverse-border-active': '#fccaca',
  'cre8-color-button-primary-danger-border-disabled': '#eaeaea',
  'cre8-color-button-primary-danger-inverse-border-disabled': '#ababab',
  'cre8-color-button-primary-danger-outline': '#0C8599',
  'cre8-color-button-primary-danger-inverse-outline': '#F3D9FA',
  'cre8-color-button-secondary-neutral-bg': 'rgba( #2d2d2d,0.0)',
  'cre8-color-button-secondary-neutral-inverse-bg': 'rgba( #2d2d2d,0.0)',
  'cre8-color-button-secondary-neutral-content': '#2d2d2d',
  'cre8-color-button-secondary-neutral-inverse-content': '#ffffff',
  'cre8-color-button-secondary-neutral-border': '#2d2d2d',
  'cre8-color-button-secondary-neutral-inverse-border': '#ffffff',
  'cre8-color-button-secondary-neutral-bg-hover': 'rgba( #2d2d2d,0.10)',
  'cre8-color-button-secondary-neutral-inverse-bg-hover': 'rgba(#2d2d2d,0.20)',
  'cre8-color-button-secondary-neutral-content-hover': '#2d2d2d',
  'cre8-color-button-secondary-neutral-inverse-content-hover': '#ffffff',
  'cre8-color-button-secondary-neutral-border-hover': '#2d2d2d',
  'cre8-color-button-secondary-neutral-inverse-border-hover': '#ffffff',
  'cre8-color-button-secondary-neutral-border-active': '#2d2d2d',
  'cre8-color-button-secondary-neutral-inverse-border-active': '#ffffff',
  'cre8-color-button-secondary-neutral-bg-active': 'rgba(#2d2d2d,0.20)',
  'cre8-color-button-secondary-neutral-inverse-bg-active': 'rgba(#2d2d2d,0.50)',
  'cre8-color-button-secondary-neutral-content-active': '#2d2d2d',
  'cre8-color-button-secondary-neutral-inverse-content-active': '#ffffff',
  'cre8-color-button-secondary-neutral-bg-disabled': '#eaeaea',
  'cre8-color-button-secondary-neutral-inverse-bg-disabled': '#ababab',
  'cre8-color-button-secondary-neutral-border-disabled': '#eaeaea',
  'cre8-color-button-secondary-neutral-inverse-border-disabled': '#ababab',
  'cre8-color-button-secondary-neutral-content-disabled': '#949494',
  'cre8-color-button-secondary-neutral-inverse-content-disabled': '#6c6c6c',
  'cre8-color-button-secondary-neutral-outline': '#9C36B5',
  'cre8-color-button-secondary-neutral-inverse-outline': '#F3D9FA',
  'cre8-color-button-secondary-bg': 'rgba( #2d2d2d,0.0)',
  'cre8-color-button-secondary-inverse-bg': 'rgba( #2d2d2d,0.0)',
  'cre8-color-button-secondary-bg-hover': '#ffffff',
  'cre8-color-button-secondary-inverse-bg-hover': 'rgba( #2d2d2d,0.0)',
  'cre8-color-button-secondary-bg-active': '#E3FAFC',
  'cre8-color-button-secondary-inverse-bg-active': '#0C8599',
  'cre8-color-button-secondary-bg-disabled': '#eaeaea',
  'cre8-color-button-secondary-inverse-bg-disabled': 'rgba( #2d2d2d,0.0)',
  'cre8-color-button-secondary-content': '#15AABF',
  'cre8-color-button-secondary-inverse-content': '#F3D9FA',
  'cre8-color-button-secondary-content-hover': '#1098AD',
  'cre8-color-button-secondary-inverse-content-hover': '#EEBEFA',
  'cre8-color-button-secondary-content-active': '#0C8599',
  'cre8-color-button-secondary-inverse-content-active': '#E599F7',
  'cre8-color-button-secondary-content-disabled': '#949494',
  'cre8-color-button-secondary-inverse-content-disabled': '#ababab',
  'cre8-color-button-secondary-border': '#15AABF',
  'cre8-color-button-secondary-inverse-border': '#F3D9FA',
  'cre8-color-button-secondary-border-hover': '#1098AD',
  'cre8-color-button-secondary-inverse-border-hover': '#EEBEFA',
  'cre8-color-button-secondary-border-active': '#0C8599',
  'cre8-color-button-secondary-inverse-border-active': '#E599F7',
  'cre8-color-button-secondary-border-disabled': '#ababab',
  'cre8-color-button-secondary-inverse-border-disabled': '#ababab',
  'cre8-color-button-secondary-outline': '#0C8599',
  'cre8-color-button-secondary-inverse-outline': '#EEBEFA',
  'cre8-color-button-secondary-danger-bg': 'rgba( #2d2d2d,0.0)',
  'cre8-color-button-secondary-danger-inverse-bg': 'rgba( #2d2d2d,0.0)',
  'cre8-color-button-secondary-danger-bg-hover': '#aa1313',
  'cre8-color-button-secondary-danger-inverse-bg-hover': '#f5a8a8',
  'cre8-color-button-secondary-danger-bg-active': '#7a0000',
  'cre8-color-button-secondary-danger-inverse-bg-active': '#fccaca',
  'cre8-color-button-secondary-danger-bg-disabled': '#eaeaea',
  'cre8-color-button-secondary-danger-inverse-bg-disabled': '#ababab',
  'cre8-color-button-secondary-danger-content': '#d02525',
  'cre8-color-button-secondary-danger-inverse-content': '#ff5c5c',
  'cre8-color-button-secondary-danger-content-hover': '#ffffff',
  'cre8-color-button-secondary-danger-inverse-content-hover': '#2d2d2d',
  'cre8-color-button-secondary-danger-content-active': '#ffffff',
  'cre8-color-button-secondary-danger-inverse-content-active': '#2d2d2d',
  'cre8-color-button-secondary-danger-content-disabled': '#949494',
  'cre8-color-button-secondary-danger-inverse-content-disabled': '#6c6c6c',
  'cre8-color-button-secondary-danger-border': '#d02525',
  'cre8-color-button-secondary-danger-inverse-border': '#ff5c5c',
  'cre8-color-button-secondary-danger-border-hover': '#aa1313',
  'cre8-color-button-secondary-danger-inverse-border-hover': '#f5a8a8',
  'cre8-color-button-secondary-danger-border-active': '#7a0000',
  'cre8-color-button-secondary-danger-inverse-border-active': '#fccaca',
  'cre8-color-button-secondary-danger-border-disabled': '#eaeaea',
  'cre8-color-button-secondary-danger-inverse-border-disabled': '#ababab',
  'cre8-color-button-secondary-danger-outline': '#0C8599',
  'cre8-color-button-secondary-danger-inverse-outline': '#F3D9FA',
  'cre8-color-button-tertiary-bg': 'rgba( #2d2d2d,0.0)',
  'cre8-color-button-tertiary-inverse-bg': 'rgba( #2d2d2d,0.0)',
  'cre8-color-button-tertiary-bg-hover': 'rgba( #2d2d2d,0.0)',
  'cre8-color-button-tertiary-inverse-bg-hover': 'rgba( #2d2d2d,0.0)',
  'cre8-color-button-tertiary-bg-active': 'rgba( #2d2d2d,0.0)',
  'cre8-color-button-tertiary-inverse-bg-active': '#0B7285',
  'cre8-color-button-tertiary-bg-disabled': 'rgba( #2d2d2d,0.0)',
  'cre8-color-button-tertiary-inverse-bg-disabled': 'rgba( #2d2d2d,0.0)',
  'cre8-color-button-tertiary-content': '#15AABF',
  'cre8-color-button-tertiary-inverse-content': '#F3D9FA',
  'cre8-color-button-tertiary-content-hover': '#1098AD',
  'cre8-color-button-tertiary-inverse-content-hover': '#EEBEFA',
  'cre8-color-button-tertiary-content-active': '#0C8599',
  'cre8-color-button-tertiary-inverse-content-active': '#E599F7',
  'cre8-color-button-tertiary-content-disabled': '#949494',
  'cre8-color-button-tertiary-inverse-content-disabled': '#ababab',
  'cre8-color-button-tertiary-border': 'rgba( #2d2d2d,0.0)',
  'cre8-color-button-tertiary-inverse-border': 'rgba( #2d2d2d,0.0)',
  'cre8-color-button-tertiary-border-hover': '#1098AD',
  'cre8-color-button-tertiary-inverse-border-hover': '#EEBEFA',
  'cre8-color-button-tertiary-border-active': '#0C8599',
  'cre8-color-button-tertiary-inverse-border-active': '#E599F7',
  'cre8-color-button-tertiary-border-disabled': 'rgba( #2d2d2d,0.0)',
  'cre8-color-button-tertiary-inverse-border-disabled': 'rgba( #2d2d2d,0.0)',
  'cre8-color-button-tertiary-outline': '#0C8599',
  'cre8-color-button-tertiary-inverse-outline': '#EEBEFA',
  'cre8-color-button-tertiary-neutral-bg': 'rgba( #2d2d2d,0.0)',
  'cre8-color-button-tertiary-neutral-inverse-bg': 'rgba( #2d2d2d,0.0)',
  'cre8-color-button-tertiary-neutral-content': '#2d2d2d',
  'cre8-color-button-tertiary-neutral-inverse-content': '#ffffff',
  'cre8-color-button-tertiary-neutral-border': 'rgba( #2d2d2d,0.0)',
  'cre8-color-button-tertiary-neutral-inverse-border': 'rgba( #2d2d2d,0.0)',
  'cre8-color-button-tertiary-neutral-bg-hover': 'rgba( #2d2d2d,0.0)',
  'cre8-color-button-tertiary-neutral-inverse-bg-hover': 'rgba( #2d2d2d,0.0)',
  'cre8-color-button-tertiary-neutral-content-hover': '#2d2d2d',
  'cre8-color-button-tertiary-neutral-inverse-content-hover': '#ffffff',
  'cre8-color-button-tertiary-neutral-border-hover': '#2d2d2d',
  'cre8-color-button-tertiary-neutral-inverse-border-hover': '#ffffff',
  'cre8-color-button-tertiary-neutral-border-active': '#2d2d2d',
  'cre8-color-button-tertiary-neutral-inverse-border-active': '#ffffff',
  'cre8-color-button-tertiary-neutral-bg-active': 'rgba( #2d2d2d,0.0)',
  'cre8-color-button-tertiary-neutral-inverse-bg-active': 'rgba( #2d2d2d,0.0)',
  'cre8-color-button-tertiary-neutral-content-active': '#2d2d2d',
  'cre8-color-button-tertiary-neutral-inverse-content-active': '#ffffff',
  'cre8-color-button-tertiary-neutral-bg-disabled': 'rgba( #2d2d2d,0.0)',
  'cre8-color-button-tertiary-neutral-inverse-bg-disabled': 'rgba( #2d2d2d,0.0)',
  'cre8-color-button-tertiary-neutral-border-disabled': 'rgba( #2d2d2d,0.0)',
  'cre8-color-button-tertiary-neutral-inverse-border-disabled': 'rgba( #2d2d2d,0.0)',
  'cre8-color-button-tertiary-neutral-content-disabled': '#949494',
  'cre8-color-button-tertiary-neutral-inverse-content-disabled': '#6c6c6c',
  'cre8-color-button-tertiary-neutral-outline': '#9C36B5',
  'cre8-color-button-tertiary-neutral-inverse-outline': '#F3D9FA',
  'cre8-color-button-tertiary-danger-bg': 'rgba( #2d2d2d,0.0)',
  'cre8-color-button-tertiary-danger-inverse-bg': 'rgba( #2d2d2d,0.0)',
  'cre8-color-button-tertiary-danger-bg-hover': '#aa1313',
  'cre8-color-button-tertiary-danger-inverse-bg-hover': '#f5a8a8',
  'cre8-color-button-tertiary-danger-bg-active': '#7a0000',
  'cre8-color-button-tertiary-danger-inverse-bg-active': '#fccaca',
  'cre8-color-button-tertiary-danger-bg-disabled': '#eaeaea',
  'cre8-color-button-tertiary-danger-inverse-bg-disabled': '#ababab',
  'cre8-color-button-tertiary-danger-content': '#d02525',
  'cre8-color-button-tertiary-danger-inverse-content': '#ff5c5c',
  'cre8-color-button-tertiary-danger-content-hover': '#ffffff',
  'cre8-color-button-tertiary-danger-inverse-content-hover': '#2d2d2d',
  'cre8-color-button-tertiary-danger-content-active': '#ffffff',
  'cre8-color-button-tertiary-danger-inverse-content-active': '#2d2d2d',
  'cre8-color-button-tertiary-danger-content-disabled': '#949494',
  'cre8-color-button-tertiary-danger-inverse-content-disabled': '#6c6c6c',
  'cre8-color-button-tertiary-danger-border': 'rgba( #2d2d2d,0.0)',
  'cre8-color-button-tertiary-danger-inverse-border': 'rgba( #2d2d2d,0.0)',
  'cre8-color-button-tertiary-danger-border-hover': '#aa1313',
  'cre8-color-button-tertiary-danger-inverse-border-hover': '#f5a8a8',
  'cre8-color-button-tertiary-danger-border-active': '#7a0000',
  'cre8-color-button-tertiary-danger-inverse-border-active': '#fccaca',
  'cre8-color-button-tertiary-danger-border-disabled': '#eaeaea',
  'cre8-color-button-tertiary-danger-inverse-border-disabled': '#ababab',
  'cre8-color-button-tertiary-danger-outline': '#0C8599',
  'cre8-color-button-tertiary-danger-inverse-outline': '#F3D9FA',
  'cre8-color-bg-default': '#ffffff',
  'cre8-color-bg-default-hover': '#ffffff',
  'cre8-color-bg-default-active': '#E3FAFC',
  'cre8-color-bg-subtle': '#f6f5f3',
  'cre8-color-bg-moderate': '#818181',
  'cre8-color-bg-inverse-moderate': '#ababab',
  'cre8-color-bg-strong': '#2d2d2d',
  'cre8-color-bg-disabled': '#eaeaea',
  'cre8-color-bg-brand': '#ffffff',
  'cre8-color-bg-brand-active': '#C5F6FA',
  'cre8-color-bg-brand-hover': '#E3FAFC',
  'cre8-color-bg-brand-strong': '#15AABF',
  'cre8-color-bg-brand-strong-hover': '#1098AD',
  'cre8-color-bg-brand-strong-active': '#0C8599',
  'cre8-color-bg-brand-xstrong': '#1098AD',
  'cre8-color-bg-brand-xstrong-hover': '#0C8599',
  'cre8-color-bg-brand-xstrong-active': '#0C8599',
  'cre8-color-bg-success': '#F5EAFB',
  'cre8-color-bg-success-strong': '#CC5DE8',
  'cre8-color-bg-error': '#ffebeb',
  'cre8-color-bg-error-strong': '#d02525',
  'cre8-color-bg-warning': '#fcf5e5',
  'cre8-color-bg-warning-strong': '#e89f12',
  'cre8-color-bg-info': '#ebf2ff',
  'cre8-color-bg-info-strong': '#1963e1',
  'cre8-color-bg-attention': '#ffffff',
  'cre8-color-bg-attention-strong': '#22B8CF',
  'cre8-color-bg-opacity-transparent': 'rgba( #2d2d2d,0.0)',
  'cre8-color-bg-opacity-default': 'rgba(#2d2d2d,0.50)',
  'cre8-color-bg-active': '#2d2d2d',
  'cre8-color-bg-inverse-active': '#ffffff',
  'cre8-color-content-default': '#2d2d2d',
  'cre8-color-content-subtle': '#6c6c6c',
  'cre8-color-content-disabled': '#949494',
  'cre8-color-content-knockout': '#ffffff',
  'cre8-color-content-brand': '#15AABF',
  'cre8-color-content-brand-strong': '#15AABF',
  'cre8-color-content-brand-knockout': '#F5EAFB',
  'cre8-color-content-success': '#CC5DE8',
  'cre8-color-content-success-icon': '#CC5DE8',
  'cre8-color-content-error': '#d02525',
  'cre8-color-content-error-icon': '#d02525',
  'cre8-color-content-warning-icon': '#2d2d2d',
  'cre8-color-content-info-icon': '#1963e1',
  'cre8-color-content-attention-icon': '#22B8CF',
  'cre8-color-content-link': '#15AABF',
  'cre8-color-content-inverse-link': '#F3D9FA',
  'cre8-color-content-link-hover': '#1098AD',
  'cre8-color-content-inverse-link-hover': '#EEBEFA',
  'cre8-color-content-link-focus': '#ffffff',
  'cre8-color-content-inverse-link-focus': '#2d2d2d',
  'cre8-color-content-link-visited': '#7522d9',
  'cre8-color-content-inverse-link-visited': '#ecc8e4',
  'cre8-color-content-link-disabled': '#949494',
  'cre8-color-content-inverse-link-disabled': '#eaeaea',
  'cre8-color-content-link-active': '#0C8599',
  'cre8-color-content-inverse-link-active': '#E599F7',
  'cre8-color-border-default': '#d5d5d5',
  'cre8-color-border-strong': '#6c6c6c',
  'cre8-color-border-knockout': '#ffffff',
  'cre8-color-border-disabled': '#ababab',
  'cre8-color-border-brand': '#15AABF',
  'cre8-color-border-brand-subtle': '#66D9E8',
  'cre8-color-border-brand-strong': '#15AABF',
  'cre8-color-border-success': '#DA77F2',
  'cre8-color-border-error': '#e93a3a',
  'cre8-color-border-warning': '#e89f12',
  'cre8-color-border-info': '#1963e1',
  'cre8-color-border-attention': '#22B8CF',
  'cre8-color-border-transparent': 'rgba( #2d2d2d,0.0)',
  'cre8-color-border-active-outline': '#1098AD',
  'cre8-color-border-inverse-active-outline': '#F3D9FA',
  'cre8-font-size-0': 12,
  'cre8-font-size-1': 14,
  'cre8-font-size-2': 16,
  'cre8-font-size-3': 18,
  'cre8-font-size-4': 20,
  'cre8-font-size-5': 24,
  'cre8-font-size-6': 28,
  'cre8-font-size-7': 32,
  'cre8-font-size-8': 40,
  'cre8-font-size-9': 48,
  'cre8-font-size-10': 56,
  'cre8-font-size-11': 64,
  'cre8-font-size-12': 72,
  'cre8-font-size-13': 80,
  'cre8-letter-spacing-0': -1.5,
  'cre8-letter-spacing-1': -1,
  'cre8-letter-spacing-2': -0.5,
  'cre8-letter-spacing-3': 0,
  'cre8-letter-spacing-4': 2,
  'cre8-letter-spacing-5': 1,
  'cre8-letter-spacing-6': 1.5,
  'cre8-paragraph-spacing-0': 0,
  'cre8-text-case-none': 'none',
  'cre8-text-case-uppercase': 'uppercase',
  'cre8-text-decoration-none': 'none',
  'cre8-text-decoration-underline': 'underline',
  'cre8-paragraph-indent-0': 0,
  'cre8-border-radius-small': 4,
  'cre8-border-radius-default': 8,
  'cre8-border-radius-large': 16,
  'cre8-border-radius-round': 900,
  'cre8-border-radius-button': 8,
  'cre8-border-radius-badge': 4,
  'cre8-border-radius-tabs': 8,
  'cre8-border-radius-container': 16,
  'cre8-border-radius-field': 8,
  'cre8-border-radius-field-brand': 8,
  'cre8-border-radius-brand': 8,
  'cre8-border-radius-none': 0,
  'cre8-border-width-none': 0,
  'cre8-border-width-default': 1,
  'cre8-border-width-focus': 2,
  'cre8-border-width-large': 4,
  'cre8-border-width-button-tertiary-outline-focus': 2,
  'cre8-border-width-button-default': 2,
  'cre8-border-width-tab-selected': 2,
  'cre8-border-width-tab-default': 2,
  'cre8-border-style-button-tertiary-outline-focus': 'solid',
  'cre8-border-style-default': 'solid',
  'cre8-shadow-default': {
    shadowOpacity: 1,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
    shadowRadius: 6,
    shadowColor: 'rgba(0,0,0,0.1)'
  },
  'cre8-shadow-button': undefined,
  'cre8-shadow-none': undefined,
  'cre8-shadow-large': {
    shadowOpacity: 1,
    shadowOffset: { width: 0, height: 10 },
    elevation: 4,
    shadowRadius: 12,
    shadowColor: 'rgba(0,0,0,0.2)'
  },
  'cre8-shadow-small': {
    shadowOpacity: 1,
    shadowOffset: { width: 0, height: 1 },
    elevation: 1,
    shadowRadius: 2,
    shadowColor: 'rgba(0,0,0,0.2)'
  },
  'cre8-color-link-bg-active': '#333333',
  'cre8-font-families-inter': '"Inter", sans-serif',
  'cre8-font-weights-inter-0': '400',
  'cre8-font-weights-inter-1': '500',
  'cre8-font-weights-inter-2': '700',
  'cre8-font-weights-inter-3': '600',
  'cre8-line-heights-0': 1.25,
  'cre8-line-heights-1': 1.12,
  'cre8-line-heights-2': 1.1400000000000001,
  'cre8-line-heights-3': 1.2,
  'cre8-line-heights-4': 1.3,
  'cre8-line-heights-5': 1.33,
  'cre8-line-heights-6': 1.4000000000000001,
  'cre8-line-heights-7': 1.5,
  'cre8-line-heights-8': 1.43,
  'cre8-line-heights-9': 1.11,
  'cre8-line-heights-10': 1.1300000000000001,
  'cre8-line-heights-11': 1.16,
  'cre8-line-heights-12': 48,
  'cre8-line-heights-13': 40,
  'cre8-line-heights-14': 32,
  'cre8-line-heights-15': 28,
  'cre8-line-heights-16': 24,
  'cre8-line-heights-17': 20,
  'cre8-line-heights-18': 16,
  'cre8-body-xlarge': {
    fontFamily: '"Inter", sans-serif',
    fontWeight: '400',
    fontSize: 24,
    letterSpacing: 0,
    lineHeight: 36,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-body-xlarge-strong': {
    fontFamily: '"Inter", sans-serif',
    fontWeight: '500',
    fontSize: 24,
    letterSpacing: 0,
    lineHeight: 36,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-body-xlarge-link': {
    fontFamily: '"Inter", sans-serif',
    fontWeight: '500',
    fontSize: 24,
    letterSpacing: 0,
    lineHeight: 36,
    textTransform: 'none',
    textDecorationLine: 'underline'
  },
  'cre8-body-large': {
    fontFamily: '"Inter", sans-serif',
    fontWeight: '400',
    fontSize: 18,
    letterSpacing: 0,
    lineHeight: 27,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-body-large-strong': {
    fontFamily: '"Inter", sans-serif',
    fontWeight: '500',
    fontSize: 18,
    letterSpacing: 0,
    lineHeight: 27,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-body-default': {
    fontFamily: '"Inter", sans-serif',
    fontWeight: '400',
    fontSize: 16,
    letterSpacing: 0,
    lineHeight: 24,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-body-default-strong': {
    fontFamily: '"Inter", sans-serif',
    fontWeight: '500',
    fontSize: 16,
    letterSpacing: 0,
    lineHeight: 24,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-body-small': {
    fontFamily: '"Inter", sans-serif',
    fontWeight: '400',
    fontSize: 14,
    letterSpacing: 0,
    lineHeight: 20.02,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-body-small-strong': {
    fontFamily: '"Inter", sans-serif',
    fontWeight: '500',
    fontSize: 14,
    letterSpacing: 0,
    lineHeight: 20.02,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-body-large-link': {
    fontFamily: '"Inter", sans-serif',
    fontWeight: '500',
    fontSize: 18,
    letterSpacing: 0,
    lineHeight: 27,
    textTransform: 'none',
    textDecorationLine: 'underline'
  },
  'cre8-body-default-link': {
    fontFamily: '"Inter", sans-serif',
    fontWeight: '500',
    fontSize: 16,
    letterSpacing: 0,
    lineHeight: 24,
    textTransform: 'none',
    textDecorationLine: 'underline'
  },
  'cre8-body-small-link': {
    fontFamily: '"Inter", sans-serif',
    fontWeight: '500',
    fontSize: 14,
    letterSpacing: 0,
    lineHeight: 20.02,
    textTransform: 'none',
    textDecorationLine: 'underline'
  },
  'cre8-label-default': {
    fontFamily: '"Inter", sans-serif',
    fontWeight: '500',
    fontSize: 16,
    letterSpacing: 0,
    lineHeight: 24,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-label-large': {
    fontFamily: '"Inter", sans-serif',
    fontWeight: '500',
    fontSize: 18,
    letterSpacing: 0,
    lineHeight: 23.94,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-label-small': {
    fontFamily: '"Inter", sans-serif',
    fontWeight: '500',
    fontSize: 14,
    letterSpacing: 0,
    lineHeight: 21,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-title-xlarge': {
    fontFamily: '"Inter", sans-serif',
    fontWeight: '500',
    fontSize: 40,
    letterSpacing: 0,
    lineHeight: 52,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-title-xlarge-mobile': {
    fontFamily: '"Inter", sans-serif',
    fontWeight: '500',
    fontSize: 32,
    letterSpacing: 0,
    lineHeight: 41.6,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-title-large': {
    fontFamily: '"Inter", sans-serif',
    fontWeight: '500',
    fontSize: 28,
    letterSpacing: 0,
    lineHeight: 31.36,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-title-large-mobile': {
    fontFamily: '"Inter", sans-serif',
    fontWeight: '500',
    fontSize: 24,
    letterSpacing: 0,
    lineHeight: 26.88,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-title-default': {
    fontFamily: '"Inter", sans-serif',
    fontWeight: '500',
    fontSize: 24,
    letterSpacing: 0,
    lineHeight: 27.36,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-title-default-mobile': {
    fontFamily: '"Inter", sans-serif',
    fontWeight: '500',
    fontSize: 18,
    letterSpacing: 0,
    lineHeight: 20.52,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-title-small': {
    fontFamily: '"Inter", sans-serif',
    fontWeight: '500',
    fontSize: 18,
    letterSpacing: 0,
    lineHeight: 25.2,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-title-small-mobile': {
    fontFamily: '"Inter", sans-serif',
    fontWeight: '500',
    fontSize: 16,
    letterSpacing: 0,
    lineHeight: 22.4,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-headline-large': {
    fontFamily: '"Inter", sans-serif',
    fontWeight: '600',
    fontSize: 48,
    letterSpacing: -1.5,
    lineHeight: 60,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-headline-large-mobile': {
    fontFamily: '"Inter", sans-serif',
    fontWeight: '600',
    fontSize: 40,
    letterSpacing: 0,
    lineHeight: 50,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-headline-default': {
    fontFamily: '"Inter", sans-serif',
    fontWeight: '600',
    fontSize: 40,
    letterSpacing: -1.5,
    lineHeight: 50,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-headline-default-mobile': {
    fontFamily: '"Inter", sans-serif',
    fontWeight: '600',
    fontSize: 32,
    letterSpacing: 0,
    lineHeight: 40,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-headline-small': {
    fontFamily: '"Inter", sans-serif',
    fontWeight: '600',
    fontSize: 32,
    letterSpacing: -0.5,
    lineHeight: 40,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-headline-small-mobile': {
    fontFamily: '"Inter", sans-serif',
    fontWeight: '600',
    fontSize: 28,
    letterSpacing: 0,
    lineHeight: 35,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-headline-xsmall': {
    fontFamily: '"Inter", sans-serif',
    fontWeight: '600',
    fontSize: 24,
    letterSpacing: 0,
    lineHeight: 30,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-headline-xsmall-mobile': {
    fontFamily: '"Inter", sans-serif',
    fontWeight: '600',
    fontSize: 24,
    letterSpacing: 0,
    lineHeight: 30,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-display-large': {
    fontFamily: '"Inter", sans-serif',
    fontWeight: '700',
    fontSize: 80,
    letterSpacing: -1,
    lineHeight: 100,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-display-large-mobile': {
    fontFamily: '"Inter", sans-serif',
    fontWeight: '700',
    fontSize: 72,
    letterSpacing: -1,
    lineHeight: 90,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-display-default': {
    fontFamily: '"Inter", sans-serif',
    fontWeight: '700',
    fontSize: 64,
    letterSpacing: -1,
    lineHeight: 80,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-display-default-mobile': {
    fontFamily: '"Inter", sans-serif',
    fontWeight: '700',
    fontSize: 56,
    letterSpacing: -1.5,
    lineHeight: 70,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-display-small': {
    fontFamily: '"Inter", sans-serif',
    fontWeight: '700',
    fontSize: 48,
    letterSpacing: -1,
    lineHeight: 60,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-display-small-mobile': {
    fontFamily: '"Inter", sans-serif',
    fontWeight: '700',
    fontSize: 40,
    letterSpacing: -1,
    lineHeight: 50,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-meta-default': {
    fontFamily: '"Inter", sans-serif',
    fontWeight: '700',
    fontSize: 16,
    letterSpacing: 1,
    lineHeight: 19.2,
    textTransform: 'uppercase',
    textDecorationLine: 'none'
  },
  'cre8-meta-default-sentence-case': {
    fontFamily: '"Inter", sans-serif',
    fontWeight: '700',
    fontSize: 16,
    letterSpacing: 0,
    lineHeight: 18.56,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-meta-large': {
    fontFamily: '"Inter", sans-serif',
    fontWeight: '700',
    fontSize: 20,
    letterSpacing: 1.5,
    lineHeight: 24,
    textTransform: 'uppercase',
    textDecorationLine: 'none'
  },
  'cre8-meta-small': {
    fontFamily: '"Inter", sans-serif',
    fontWeight: '700',
    fontSize: 14,
    letterSpacing: 1,
    lineHeight: 16.8,
    textTransform: 'uppercase',
    textDecorationLine: 'none'
  },
  'cre8-icon-size-small': 14,
  'cre8-icon-size-default': 16,
  'cre8-icon-size-large': 18,
  'cre8-badge-padding-horizontal': 6,
  'cre8-badge-padding-vertical': 2,
  'cre8-progress-meter-height': 8,
  'cre8-breakpoint-xsm': '375px',
  'cre8-breakpoint-sm': '560px',
  'cre8-breakpoint-md': '768px',
  'cre8-breakpoint-lg': '960px',
  'cre8-breakpoint-xl': '1200px',
  'cre8-breakpoint-xxl': '1400px',
  'cre8-asset-font-inter-400-normal': 'Inter-Regular',
  'cre8-asset-font-inter-500-medium': 'Inter-Medium',
  'cre8-asset-font-inter-600-medium': 'Inter-SemiBold',
  'cre8-asset-font-inter-700-normal': 'Inter-Bold'
}