import {css} from 'lit';

 const netflix = css`
@font-face {
  font-family: 'Netflix Sans';
  src: url('https://assets.nflxext.com/ffe/siteui/fonts/netflix-sans/v3/NetflixSans_W_Rg.woff2') format('woff2'),
       url('https://assets.nflxext.com/ffe/siteui/fonts/netflix-sans/v3/NetflixSans_W_Rg.woff') format('woff');
  font-weight: 400;
  font-style: normal;
}
@font-face {
  font-family: 'Netflix Sans';
  src: url('https://assets.nflxext.com/ffe/siteui/fonts/netflix-sans/v3/NetflixSans_W_Bd.woff2') format('woff2'),
       url('https://assets.nflxext.com/ffe/siteui/fonts/netflix-sans/v3/NetflixSans_W_Bd.woff') format('woff');
  font-weight: 700;
  font-style: bold;
}
@font-face {
  font-family: 'Netflix Sans';
  src: url('https://assets.nflxext.com/ffe/siteui/fonts/netflix-sans/v3/NetflixSans_W_Lt.woff2') format('woff2'),
       url('https://assets.nflxext.com/ffe/siteui/fonts/netflix-sans/v3/NetflixSans_W_Lt.woff') format('woff');
  font-weight: 300;
  font-style: light;
}
:root {
  --cre8-color-bg-brand: #e50914;
  --cre8-color-bg-brand-hover: #c11119;
  --cre8-color-content-brand-subtle: #b82869;
  --cre8-color-header-bg-default: #000;
  --cre8-color-header-inverse-bg-default: #fff;
  --cre8-color-header-menu-bg-default: #000;
  --cre8-color-header-menu-inverse-bg-default: #fff;
  --cre8-color-header-menu-bg-hover: #232323;
  --cre8-color-header-menu-inverse-bg-hover: #e50914;
  --cre8-color-header-menu-bg-focus: #232323;
  --cre8-color-header-menu-inverse-bg-focus: #e50914;
  --cre8-color-header-menu-bg-active: #c11119;
  --cre8-color-header-menu-inverse-bg-active: #fff;
  --cre8-color-header-menu-bg-pressed: #c11119;
  --cre8-color-header-menu-inverse-bg-pressed: #fff;
  --cre8-color-header-menu-bg-selected: #232323;
  --cre8-color-header-menu-inverse-bg-selected: #e50914;
  --cre8-color-header-menu-content-default: #fff;
  --cre8-color-header-menu-inverse-content-default: #e50914;
  --cre8-color-header-menu-content-hover: #fff;
  --cre8-color-header-menu-inverse-content-hover: #fff;
  --cre8-color-header-menu-content-focus: #fff;
  --cre8-color-header-menu-inverse-content-focus: #fff;
  --cre8-color-header-menu-content-active: #fff;
  --cre8-color-header-menu-inverse-content-active: #fff;
  --cre8-color-header-menu-content-pressed: #fff;
  --cre8-color-header-menu-inverse-content-pressed: #fff;
  --cre8-color-header-menu-content-selected: #fff;
  --cre8-color-header-menu-inverse-content-selected: #fff;
  --cre8-color-header-menu-border-default: rgba(0,0,0,0);
  --cre8-color-header-menu-inverse-border-default: rgba(0,0,0,0);
  --cre8-color-header-menu-border-hover: #e50914;
  --cre8-color-header-menu-inverse-border-hover: #fff;
  --cre8-color-header-menu-border-focus: #e50914;
  --cre8-color-header-menu-inverse-border-focus: #fff;
  --cre8-color-header-menu-border-active: #c11119;
  --cre8-color-header-menu-inverse-border-active: #fff;
  --cre8-color-header-menu-border-pressed: #c11119;
  --cre8-color-header-menu-inverse-border-pressed: #fff;
  --cre8-color-header-menu-border-selected: #e50914;
  --cre8-color-header-menu-inverse-border-selected: #232323;
  --cre8-color-header-submenu-bg-default: #000;
  --cre8-color-header-submenu-inverse-bg-default: #fff;
  --cre8-color-header-submenu-bg-hover: #232323;
  --cre8-color-header-submenu-inverse-bg-hover: #e50914;
  --cre8-color-header-submenu-bg-focus: #000;
  --cre8-color-header-submenu-inverse-bg-focus: #fff;
  --cre8-color-header-submenu-bg-active: #c11119;
  --cre8-color-header-submenu-inverse-bg-active: #fff;
  --cre8-color-header-submenu-bg-pressed: #c11119;
  --cre8-color-header-submenu-inverse-bg-pressed: #fff;
  --cre8-color-header-submenu-bg-selected: #232323;
  --cre8-color-header-submenu-inverse-bg-selected: #e50914;
  --cre8-color-header-submenu-content-default: #fff;
  --cre8-color-header-submenu-inverse-content-default: #e50914;
  --cre8-color-header-submenu-content-hover: #fff;
  --cre8-color-header-submenu-inverse-content-hover: #fff;
  --cre8-color-header-submenu-content-focus: #fff;
  --cre8-color-header-submenu-inverse-content-focus: #fff;
  --cre8-color-header-submenu-content-active: #fff;
  --cre8-color-header-submenu-inverse-content-active: #fff;
  --cre8-color-header-submenu-content-pressed: #fff;
  --cre8-color-header-submenu-inverse-content-pressed: #fff;
  --cre8-color-header-submenu-content-selected: #fff;
  --cre8-color-header-submenu-inverse-content-selected: #fff;
  --cre8-color-header-submenu-border-default: #000;
  --cre8-color-header-submenu-inverse-border-default: #fff;
  --cre8-color-header-submenu-border-hover: #232323;
  --cre8-color-header-submenu-inverse-border-hover: #e50914;
  --cre8-color-header-submenu-border-focus: #e50914;
  --cre8-color-header-submenu-inverse-border-focus: #fff;
  --cre8-color-header-submenu-border-active: #c11119;
  --cre8-color-header-submenu-inverse-border-active: #fff;
  --cre8-color-header-submenu-border-pressed: #c11119;
  --cre8-color-header-submenu-inverse-border-pressed: #fff;
  --cre8-color-header-submenu-border-selected: #e50914;
  --cre8-color-header-submenu-inverse-border-selected: #232323;
  --cre8-color-header-bg-secondary: #232323;
  --cre8-color-header-inverse-bg-secondary: #fff;
  --cre8-color-header-bg-tertiary: #232323;
  --cre8-color-header-inverse-bg-tertiary: #fff;
  --cre8-color-footer-bg-default: #000;
  --cre8-color-footer-bg-secondary: #232323;
  --cre8-color-footer-content-secondary: #fff;
  --cre8-color-footer-link-hover: #e50914;
  --cre8-color-footer-link-default: #e50914;
  --cre8-spacing-0: 0rem;
  --cre8-spacing-2: 0.125rem;
  --cre8-spacing-4: 0.25rem;
  --cre8-spacing-6: 0.375rem;
  --cre8-spacing-8: 0.5rem;
  --cre8-spacing-12: 0.75rem;
  --cre8-spacing-14: 0.875rem;
  --cre8-spacing-16: 1rem;
  --cre8-spacing-18: 1.125rem;
  --cre8-spacing-24: 1.5rem;
  --cre8-spacing-32: 2rem;
  --cre8-spacing-40: 2.5rem;
  --cre8-spacing-48: 3rem;
  --cre8-spacing-64: 4rem;
  --cre8-spacing-80: 5rem;
  --cre8-spacing-96: 6rem;
  --cre8-spacing-120: 7.5rem;
  --cre8-spacing-160: 10rem;
  --cre8-button-padding-vertical-small: 0.5rem;
  --cre8-button-padding-vertical-large: 1rem;
  --cre8-button-padding-vertical-medium: 0.75rem;
  --cre8-button-padding-vertical-icon-only: 0.5rem;
  --cre8-button-padding-vertical-small-icon-only: 0.5rem;
  --cre8-button-padding-vertical-medium-icon-only: 1rem;
  --cre8-button-padding-vertical-large-icon-only: 1rem;
  --cre8-button-padding-horizontal-small: 1rem;
  --cre8-button-padding-horizontal-medium: 1.5rem;
  --cre8-button-padding-horizontal-large: 2rem;
  --cre8-button-padding-horizontal-icon-only: 0.5rem;
  --cre8-button-padding-horizontal-small-icon-only: 0.5rem;
  --cre8-button-padding-horizontal-medium-icon-only: 1rem;
  --cre8-button-padding-horizontal-large-icon-only: 1rem;
  --cre8-color-button-primary-bg: #e50914;
  --cre8-color-button-primary-inverse-bg: #fff;
  --cre8-color-button-primary-bg-hover: #c11119;
  --cre8-color-button-primary-inverse-bg-hover: #fff;
  --cre8-color-button-primary-bg-active: #b82869;
  --cre8-color-button-primary-inverse-bg-active: #fff;
  --cre8-color-button-primary-bg-disabled: #ececec;
  --cre8-color-button-primary-inverse-bg-disabled: #ababab;
  --cre8-color-button-primary-content: #fff;
  --cre8-color-button-primary-inverse-content: #e50914;
  --cre8-color-button-primary-content-hover: #fff;
  --cre8-color-button-primary-inverse-content-hover: #e50914;
  --cre8-color-button-primary-content-active: #fff;
  --cre8-color-button-primary-inverse-content-active: #e50914;
  --cre8-color-button-primary-content-disabled: #949494;
  --cre8-color-button-primary-inverse-content-disabled: #6c6c6c;
  --cre8-color-button-primary-border: #e50914;
  --cre8-color-button-primary-inverse-border: #fff;
  --cre8-color-button-primary-border-hover: #c11119;
  --cre8-color-button-primary-inverse-border-hover: #fff;
  --cre8-color-button-primary-border-active: #b82869;
  --cre8-color-button-primary-inverse-border-active: #fff;
  --cre8-color-button-primary-border-disabled: #ececec;
  --cre8-color-button-primary-inverse-border-disabled: #ababab;
  --cre8-color-button-primary-outline: #e50914;
  --cre8-color-button-primary-inverse-outline: #fff;
  --cre8-color-button-primary-danger-bg: #b82869;
  --cre8-color-button-primary-danger-inverse-bg: #fff;
  --cre8-color-button-primary-danger-bg-hover: #c11119;
  --cre8-color-button-primary-danger-inverse-bg-hover: #fff;
  --cre8-color-button-primary-danger-bg-active: #e50914;
  --cre8-color-button-primary-danger-inverse-bg-active: #fff;
  --cre8-color-button-primary-danger-bg-disabled: #ececec;
  --cre8-color-button-primary-danger-inverse-bg-disabled: #ababab;
  --cre8-color-button-primary-danger-content: #fff;
  --cre8-color-button-primary-danger-inverse-content: #e50914;
  --cre8-color-button-primary-danger-content-hover: #fff;
  --cre8-color-button-primary-danger-inverse-content-hover: #e50914;
  --cre8-color-button-primary-danger-content-active: #fff;
  --cre8-color-button-primary-danger-inverse-content-active: #e50914;
  --cre8-color-button-primary-danger-content-disabled: #949494;
  --cre8-color-button-primary-danger-inverse-content-disabled: #6c6c6c;
  --cre8-color-button-primary-danger-border: #b82869;
  --cre8-color-button-primary-danger-inverse-border: #fff;
  --cre8-color-button-primary-danger-border-hover: #c11119;
  --cre8-color-button-primary-danger-inverse-border-hover: #fff;
  --cre8-color-button-primary-danger-border-active: #e50914;
  --cre8-color-button-primary-danger-inverse-border-active: #fff;
  --cre8-color-button-primary-danger-border-disabled: #ececec;
  --cre8-color-button-primary-danger-inverse-border-disabled: #ababab;
  --cre8-color-button-primary-danger-outline: #e50914;
  --cre8-color-button-primary-danger-inverse-outline: #fff;
  --cre8-color-button-secondary-neutral-bg: rgba(0,0,0,0);
  --cre8-color-button-secondary-neutral-inverse-bg: rgba(0,0,0,0);
  --cre8-color-button-secondary-neutral-content: #fff;
  --cre8-color-button-secondary-neutral-inverse-content: #e50914;
  --cre8-color-button-secondary-neutral-border: #fff;
  --cre8-color-button-secondary-neutral-inverse-border: #e50914;
  --cre8-color-button-secondary-neutral-bg-hover: rgba(0,0,0,0.10);
  --cre8-color-button-secondary-neutral-inverse-bg-hover: rgba(0,0,0,0.20);
  --cre8-color-button-secondary-neutral-content-hover: #fff;
  --cre8-color-button-secondary-neutral-inverse-content-hover: #e50914;
  --cre8-color-button-secondary-neutral-border-hover: #fff;
  --cre8-color-button-secondary-neutral-inverse-border-hover: #e50914;
  --cre8-color-button-secondary-neutral-border-active: #fff;
  --cre8-color-button-secondary-neutral-inverse-border-active: #e50914;
  --cre8-color-button-secondary-neutral-bg-active: rgba(0,0,0,0.20);
  --cre8-color-button-secondary-neutral-inverse-bg-active: rgba(0,0,0,0.50);
  --cre8-color-button-secondary-neutral-content-active: #fff;
  --cre8-color-button-secondary-neutral-inverse-content-active: #e50914;
  --cre8-color-button-secondary-neutral-bg-disabled: #ececec;
  --cre8-color-button-secondary-neutral-inverse-bg-disabled: #ababab;
  --cre8-color-button-secondary-neutral-border-disabled: #ececec;
  --cre8-color-button-secondary-neutral-inverse-border-disabled: #ababab;
  --cre8-color-button-secondary-neutral-content-disabled: #949494;
  --cre8-color-button-secondary-neutral-inverse-content-disabled: #6c6c6c;
  --cre8-color-button-secondary-neutral-outline: #e50914;
  --cre8-color-button-secondary-neutral-inverse-outline: #fff;
  --cre8-color-button-secondary-bg: rgba(0,0,0,0);
  --cre8-color-button-secondary-inverse-bg: rgba(0,0,0,0);
  --cre8-color-button-secondary-bg-hover: #232323;
  --cre8-color-button-secondary-inverse-bg-hover: rgba(0,0,0,0);
  --cre8-color-button-secondary-bg-active: #232323;
  --cre8-color-button-secondary-inverse-bg-active: #fff;
  --cre8-color-button-secondary-bg-disabled: #ececec;
  --cre8-color-button-secondary-inverse-bg-disabled: rgba(0,0,0,0);
  --cre8-color-button-secondary-content: #fff;
  --cre8-color-button-secondary-inverse-content: #e50914;
  --cre8-color-button-secondary-content-hover: #fff;
  --cre8-color-button-secondary-inverse-content-hover: #e50914;
  --cre8-color-button-secondary-content-active: #fff;
  --cre8-color-button-secondary-inverse-content-active: #e50914;
  --cre8-color-button-secondary-content-disabled: #949494;
  --cre8-color-button-secondary-inverse-content-disabled: #ababab;
  --cre8-color-button-secondary-border: #fff;
  --cre8-color-button-secondary-inverse-border: #e50914;
  --cre8-color-button-secondary-border-hover: #fff;
  --cre8-color-button-secondary-inverse-border-hover: #e50914;
  --cre8-color-button-secondary-border-active: #fff;
  --cre8-color-button-secondary-inverse-border-active: #e50914;
  --cre8-color-button-secondary-border-disabled: #ececec;
  --cre8-color-button-secondary-inverse-border-disabled: #ababab;
  --cre8-color-button-secondary-outline: #e50914;
  --cre8-color-button-secondary-inverse-outline: #fff;
  --cre8-color-button-secondary-danger-bg: rgba(0,0,0,0);
  --cre8-color-button-secondary-danger-inverse-bg: rgba(0,0,0,0);
  --cre8-color-button-secondary-danger-bg-hover: #c11119;
  --cre8-color-button-secondary-danger-inverse-bg-hover: #fff;
  --cre8-color-button-secondary-danger-bg-active: #e50914;
  --cre8-color-button-secondary-danger-inverse-bg-active: #fff;
  --cre8-color-button-secondary-danger-bg-disabled: #ececec;
  --cre8-color-button-secondary-danger-inverse-bg-disabled: #ababab;
  --cre8-color-button-secondary-danger-content: #fff;
  --cre8-color-button-secondary-danger-inverse-content: #e50914;
  --cre8-color-button-secondary-danger-content-hover: #fff;
  --cre8-color-button-secondary-danger-inverse-content-hover: #e50914;
  --cre8-color-button-secondary-danger-content-active: #fff;
  --cre8-color-button-secondary-danger-inverse-content-active: #e50914;
  --cre8-color-button-secondary-danger-content-disabled: #949494;
  --cre8-color-button-secondary-danger-inverse-content-disabled: #6c6c6c;
  --cre8-color-button-secondary-danger-border: #b82869;
  --cre8-color-button-secondary-danger-inverse-border: #fff;
  --cre8-color-button-secondary-danger-border-hover: #c11119;
  --cre8-color-button-secondary-danger-inverse-border-hover: #fff;
  --cre8-color-button-secondary-danger-border-active: #e50914;
  --cre8-color-button-secondary-danger-inverse-border-active: #fff;
  --cre8-color-button-secondary-danger-border-disabled: #ececec;
  --cre8-color-button-secondary-danger-inverse-border-disabled: #ababab;
  --cre8-color-button-secondary-danger-outline: #e50914;
  --cre8-color-button-secondary-danger-inverse-outline: #fff;
  --cre8-color-button-tertiary-bg: rgba(0,0,0,0);
  --cre8-color-button-tertiary-inverse-bg: rgba(0,0,0,0);
  --cre8-color-button-tertiary-bg-hover: rgba(0,0,0,0);
  --cre8-color-button-tertiary-inverse-bg-hover: rgba(0,0,0,0);
  --cre8-color-button-tertiary-bg-active: rgba(0,0,0,0);
  --cre8-color-button-tertiary-inverse-bg-active: #fff;
  --cre8-color-button-tertiary-bg-disabled: rgba(0,0,0,0);
  --cre8-color-button-tertiary-inverse-bg-disabled: rgba(0,0,0,0);
  --cre8-color-button-tertiary-content: #fff;
  --cre8-color-button-tertiary-inverse-content: #e50914;
  --cre8-color-button-tertiary-content-hover: #fff;
  --cre8-color-button-tertiary-inverse-content-hover: #e50914;
  --cre8-color-button-tertiary-content-active: #fff;
  --cre8-color-button-tertiary-inverse-content-active: #e50914;
  --cre8-color-button-tertiary-content-disabled: #949494;
  --cre8-color-button-tertiary-inverse-content-disabled: #ababab;
  --cre8-color-button-tertiary-border: rgba(0,0,0,0);
  --cre8-color-button-tertiary-inverse-border: rgba(0,0,0,0);
  --cre8-color-button-tertiary-border-hover: #fff;
  --cre8-color-button-tertiary-inverse-border-hover: #e50914;
  --cre8-color-button-tertiary-border-active: #fff;
  --cre8-color-button-tertiary-inverse-border-active: #e50914;
  --cre8-color-button-tertiary-border-disabled: rgba(0,0,0,0);
  --cre8-color-button-tertiary-inverse-border-disabled: rgba(0,0,0,0);
  --cre8-color-button-tertiary-outline: #e50914;
  --cre8-color-button-tertiary-inverse-outline: #fff;
  --cre8-color-button-tertiary-neutral-bg: rgba(0,0,0,0);
  --cre8-color-button-tertiary-neutral-inverse-bg: rgba(0,0,0,0);
  --cre8-color-button-tertiary-neutral-content: #fff;
  --cre8-typography-body-xlarge-strong-font-family: 'Netflix Sans', Helvetica Neue, Segoe UI, Roboto, Ubuntu, sans-serif;
  --cre8-typography-body-xlarge-strong-text-transform: none;
  --cre8-typography-body-xlarge-link-font-family: 'Netflix Sans', Helvetica Neue, Segoe UI, Roboto, Ubuntu, sans-serif;
  --cre8-typography-body-xlarge-link-text-transform: none;
  --cre8-typography-body-large-font-family: 'Netflix Sans', Helvetica Neue, Segoe UI, Roboto, Ubuntu, sans-serif;
  --cre8-typography-body-large-text-transform: none;
  --cre8-typography-body-large-strong-font-family: 'Netflix Sans', Helvetica Neue, Segoe UI, Roboto, Ubuntu, sans-serif;
  --cre8-typography-body-large-strong-text-transform: none;
  --cre8-typography-body-default-font-family: 'Netflix Sans', Helvetica Neue, Segoe UI, Roboto, Ubuntu, sans-serif;
  --cre8-typography-body-default-text-transform: none;
  --cre8-typography-body-default-strong-font-family: 'Netflix Sans', Helvetica Neue, Segoe UI, Roboto, Ubuntu, sans-serif;
  --cre8-typography-body-default-strong-text-transform: none;
  --cre8-typography-body-small-font-family: 'Netflix Sans', Helvetica Neue, Segoe UI, Roboto, Ubuntu, sans-serif;
  --cre8-typography-body-small-text-transform: none;
  --cre8-typography-body-small-strong-font-family: 'Netflix Sans', Helvetica Neue, Segoe UI, Roboto, Ubuntu, sans-serif;
  --cre8-typography-body-small-strong-text-transform: none;
  --cre8-typography-body-large-link-font-family: 'Netflix Sans', Helvetica Neue, Segoe UI, Roboto, Ubuntu, sans-serif;
  --cre8-typography-body-large-link-text-transform: none;
  --cre8-typography-body-default-link-font-family: 'Netflix Sans', Helvetica Neue, Segoe UI, Roboto, Ubuntu, sans-serif;
  --cre8-typography-body-default-link-text-transform: none;
  --cre8-typography-body-small-link-font-family: 'Netflix Sans', Helvetica Neue, Segoe UI, Roboto, Ubuntu, sans-serif;
  --cre8-typography-body-small-link-text-transform: none;
  --cre8-typography-label-default-font-family: 'Netflix Sans', Helvetica Neue, Segoe UI, Roboto, Ubuntu, sans-serif;
  --cre8-typography-label-default-text-transform: none;
  --cre8-typography-label-large-font-family: 'Netflix Sans', Helvetica Neue, Segoe UI, Roboto, Ubuntu, sans-serif;
  --cre8-typography-label-large-text-transform: none;
  --cre8-typography-label-small-font-family: 'Netflix Sans', Helvetica Neue, Segoe UI, Roboto, Ubuntu, sans-serif;
  --cre8-typography-label-small-text-transform: none;
  --cre8-typography-title-xlarge-font-family: 'Netflix Sans', Helvetica Neue, Segoe UI, Roboto, Ubuntu, sans-serif;
  --cre8-typography-title-xlarge-text-transform: none;
  --cre8-typography-title-xlarge-mobile-font-family: 'Netflix Sans', Helvetica Neue, Segoe UI, Roboto, Ubuntu, sans-serif;
  --cre8-typography-title-xlarge-mobile-text-transform: none;
  --cre8-typography-title-large-font-family: 'Netflix Sans', Helvetica Neue, Segoe UI, Roboto, Ubuntu, sans-serif;
  --cre8-typography-title-large-text-transform: none;
  --cre8-typography-title-large-mobile-font-family: 'Netflix Sans', Helvetica Neue, Segoe UI, Roboto, Ubuntu, sans-serif;
  --cre8-typography-title-large-mobile-text-transform: none;
  --cre8-typography-title-default-font-family: 'Netflix Sans', Helvetica Neue, Segoe UI, Roboto, Ubuntu, sans-serif;
  --cre8-typography-title-default-text-transform: none;
  --cre8-typography-title-default-mobile-font-family: 'Netflix Sans', Helvetica Neue, Segoe UI, Roboto, Ubuntu, sans-serif;
  --cre8-typography-title-default-mobile-text-transform: none;
  --cre8-typography-title-small-font-family: 'Netflix Sans', Helvetica Neue, Segoe UI, Roboto, Ubuntu, sans-serif;
  --cre8-typography-title-small-text-transform: none;
  --cre8-typography-title-small-mobile-font-family: 'Netflix Sans', Helvetica Neue, Segoe UI, Roboto, Ubuntu, sans-serif;
  --cre8-typography-title-small-mobile-text-transform: none;
  --cre8-typography-headline-large-font-family: 'Netflix Sans', Helvetica Neue, Segoe UI, Roboto, Ubuntu, sans-serif;
  --cre8-typography-headline-large-text-transform: none;
  --cre8-typography-headline-large-mobile-font-family: 'Netflix Sans', Helvetica Neue, Segoe UI, Roboto, Ubuntu, sans-serif;
  --cre8-typography-headline-large-mobile-text-transform: none;
  --cre8-typography-headline-default-font-family: 'Netflix Sans', Helvetica Neue, Segoe UI, Roboto, Ubuntu, sans-serif;
  --cre8-typography-headline-default-text-transform: none;
  --cre8-typography-headline-default-mobile-font-family: 'Netflix Sans', Helvetica Neue, Segoe UI, Roboto, Ubuntu, sans-serif;
  --cre8-typography-headline-default-mobile-text-transform: none;
  --cre8-typography-headline-small-font-family: 'Netflix Sans', Helvetica Neue, Segoe UI, Roboto, Ubuntu, sans-serif;
  --cre8-typography-headline-small-text-transform: none;
  --cre8-typography-headline-small-mobile-font-family: 'Netflix Sans', Helvetica Neue, Segoe UI, Roboto, Ubuntu, sans-serif;
  --cre8-typography-headline-small-mobile-text-transform: none;
  --cre8-typography-headline-xsmall-font-family: 'Netflix Sans', Helvetica Neue, Segoe UI, Roboto, Ubuntu, sans-serif;
  --cre8-typography-headline-xsmall-text-transform: none;
  --cre8-typography-headline-xsmall-mobile-font-family: 'Netflix Sans', Helvetica Neue, Segoe UI, Roboto, Ubuntu, sans-serif;
  --cre8-typography-headline-xsmall-mobile-text-transform: none;
  --cre8-typography-display-large-font-family: 'Netflix Sans', Helvetica Neue, Segoe UI, Roboto, Ubuntu, sans-serif;
  --cre8-typography-display-large-text-transform: none;
  --cre8-typography-display-large-mobile-font-family: 'Netflix Sans', Helvetica Neue, Segoe UI, Roboto, Ubuntu, sans-serif;
  --cre8-typography-display-large-mobile-text-transform: none;
  --cre8-typography-display-default-font-family: 'Netflix Sans', Helvetica Neue, Segoe UI, Roboto, Ubuntu, sans-serif;
  --cre8-typography-display-default-text-transform: none;
  --cre8-typography-display-default-mobile-font-family: 'Netflix Sans', Helvetica Neue, Segoe UI, Roboto, Ubuntu, sans-serif;
  --cre8-typography-display-default-mobile-text-transform: none;
  --cre8-typography-display-small-font-family: 'Netflix Sans', Helvetica Neue, Segoe UI, Roboto, Ubuntu, sans-serif;
  --cre8-typography-display-small-text-transform: none;
  --cre8-typography-display-small-mobile-font-family: 'Netflix Sans', Helvetica Neue, Segoe UI, Roboto, Ubuntu, sans-serif;
  --cre8-typography-display-small-mobile-text-transform: none;
  --cre8-typography-meta-default-font-family: 'Netflix Sans', Helvetica Neue, Segoe UI, Roboto, Ubuntu, sans-serif;
  --cre8-typography-meta-default-text-transform: uppercase;
  --cre8-typography-meta-default-sentence-case-font-family: 'Netflix Sans', Helvetica Neue, Segoe UI, Roboto, Ubuntu, sans-serif;
  --cre8-typography-meta-default-sentence-case-text-transform: none;
  --cre8-typography-meta-large-font-family: 'Netflix Sans', Helvetica Neue, Segoe UI, Roboto, Ubuntu, sans-serif;
  --cre8-typography-meta-large-text-transform: uppercase;
  --cre8-typography-meta-small-font-family: 'Netflix Sans', Helvetica Neue, Segoe UI, Roboto, Ubuntu, sans-serif;
  --cre8-typography-meta-small-font-weight: 700;
  --cre8-typography-meta-small-line-height: 1.2;
  --cre8-typography-meta-small-letter-spacing: 0.1em;

  /* --- Generic Brand/Surface/Content/Border Tokens --- */
  --cre8-color-bg-default: #000;
  --cre8-color-bg-subtle: #232323;
  --cre8-color-bg-inverse: #fff;
  --cre8-color-content-default: #fff;
  --cre8-color-content-subtle: #b3b3b3;
  --cre8-color-content-inverse: #000;
  --cre8-color-border-default: #232323;
  --cre8-color-border-subtle: #333;
  --cre8-color-border-inverse: #fff;

  /* --- Typography Tokens (font-size, weight, line-height, letter-spacing) --- */
  --cre8-typography-body-default-font-size: 1rem;
  --cre8-typography-body-default-font-weight: 400;
  --cre8-typography-body-default-line-height: 1.5;
  --cre8-typography-body-default-letter-spacing: normal;

  --cre8-typography-body-large-font-size: 1.125rem;
  --cre8-typography-body-large-font-weight: 400;
  --cre8-typography-body-large-line-height: 1.5;
  --cre8-typography-body-large-letter-spacing: normal;

  --cre8-typography-body-small-font-size: 0.875rem;
  --cre8-typography-body-small-font-weight: 400;
  --cre8-typography-body-small-line-height: 1.5;
  --cre8-typography-body-small-letter-spacing: normal;

  --cre8-typography-title-large-font-size: 2rem;
  --cre8-typography-title-large-font-weight: 700;
  --cre8-typography-title-large-line-height: 1.2;
  --cre8-typography-title-large-letter-spacing: normal;

  --cre8-typography-title-default-font-size: 1.5rem;
  --cre8-typography-title-default-font-weight: 700;
  --cre8-typography-title-default-line-height: 1.2;
  --cre8-typography-title-default-letter-spacing: normal;

  --cre8-typography-title-small-font-size: 1.25rem;
  --cre8-typography-title-small-font-weight: 700;
  --cre8-typography-title-small-line-height: 1.2;
  --cre8-typography-title-small-letter-spacing: normal;

  --cre8-typography-label-default-font-size: 0.875rem;
  --cre8-typography-label-default-font-weight: 500;
  --cre8-typography-label-default-line-height: 1.2;
  --cre8-typography-label-default-letter-spacing: 0.05em;

  --cre8-typography-label-large-font-size: 1rem;
  --cre8-typography-label-large-font-weight: 500;
  --cre8-typography-label-large-line-height: 1.2;
  --cre8-typography-label-large-letter-spacing: 0.05em;

  --cre8-typography-label-small-font-size: 0.75rem;
  --cre8-typography-label-small-font-weight: 500;
  --cre8-typography-label-small-line-height: 1.2;
  --cre8-typography-label-small-letter-spacing: 0.05em;

  --cre8-typography-headline-large-font-size: 2.5rem;
  --cre8-typography-headline-large-font-weight: 700;
  --cre8-typography-headline-large-line-height: 1.1;
  --cre8-typography-headline-large-letter-spacing: normal;

  --cre8-typography-headline-default-font-size: 2rem;
  --cre8-typography-headline-default-font-weight: 700;
  --cre8-typography-headline-default-line-height: 1.1;
  --cre8-typography-headline-default-letter-spacing: normal;

  --cre8-typography-headline-small-font-size: 1.5rem;
  --cre8-typography-headline-small-font-weight: 700;
  --cre8-typography-headline-small-line-height: 1.1;
  --cre8-typography-headline-small-letter-spacing: normal;

  --cre8-typography-display-large-font-size: 3rem;
  --cre8-typography-display-large-font-weight: 700;
  --cre8-typography-display-large-line-height: 1.1;
  --cre8-typography-display-large-letter-spacing: normal;

  --cre8-typography-display-default-font-size: 2.5rem;
  --cre8-typography-display-default-font-weight: 700;
  --cre8-typography-display-default-line-height: 1.1;
  --cre8-typography-display-default-letter-spacing: normal;

  --cre8-typography-display-small-font-size: 2rem;
  --cre8-typography-display-small-font-weight: 700;
  --cre8-typography-display-small-line-height: 1.1;
  --cre8-typography-display-small-letter-spacing: normal;

  --cre8-typography-meta-default-font-size: 0.75rem;
  --cre8-typography-meta-default-font-weight: 700;
  --cre8-typography-meta-default-line-height: 1.2;
  --cre8-typography-meta-default-letter-spacing: 0.1em;

  --cre8-typography-meta-large-font-size: 0.875rem;
  --cre8-typography-meta-large-font-weight: 700;
  --cre8-typography-meta-large-line-height: 1.2;
  --cre8-typography-meta-large-letter-spacing: 0.1em;

  --cre8-typography-meta-small-font-size: 0.625rem;
  --cre8-typography-meta-small-font-weight: 700;
  --cre8-typography-meta-small-line-height: 1.2;
  --cre8-typography-meta-small-letter-spacing: 0.1em;

  --cre8-border-radius-default: 0.5rem;
  --cre8-shadow-default: 0 0.25rem 0.5rem 0 rgba(0,0,0,0.8);
}
`;


export default netflix; 