/**
 * Do not edit directly
 * Generated on Sun, 27 Oct 2024 04:05:11 GMT
 */


module.exports = {
  'leaf-desktop-menu-padding-vertical-padding': 16,
  'leaf-desktop-menu-padding-horizontal-padding': 8,
  'leaf-color-header-bg-default': '#ffffff',
  'leaf-color-header-bg-secondary': '#fbfbfa',
  'leaf-color-header-bg-tertiary': '#012529',
  'leaf-color-header-menu-bg-default': '#ffffff',
  'leaf-color-header-menu-bg-active': '#035c67',
  'leaf-color-header-menu-bg-focus': '#035c67',
  'leaf-color-header-menu-content-default': '#2d2d2d',
  'leaf-color-header-menu-content-active': '#ffffff',
  'leaf-color-header-menu-content-focus': '#ffffff',
  'leaf-color-header-menu-border-default': 'rgba( #2d2d2d,0.0)',
  'leaf-color-header-menu-bg-hover': '#ffffff',
  'leaf-color-header-menu-content-hover': '#035c67',
  'leaf-color-header-menu-border-hover': 'rgba( #2d2d2d,0.0)',
  'leaf-color-header-menu-bg-pressed': '#ffffff',
  'leaf-color-header-menu-content-pressed': '#035c67',
  'leaf-color-header-menu-border-pressed': 'rgba( #2d2d2d,0.0)',
  'leaf-color-header-menu-border-active': 'rgba( #2d2d2d,0.0)',
  'leaf-color-header-menu-border-focus': 'rgba( #2d2d2d,0.0)',
  'leaf-color-header-submenu-bg-default': '#ffffff',
  'leaf-color-header-submenu-bg-focus': '#035c67',
  'leaf-color-header-submenu-content-default': '#035c67',
  'leaf-color-header-submenu-bg-hover': '#035c67',
  'leaf-color-header-submenu-content-hover': '#ffffff',
  'leaf-color-header-submenu-content-focus': '#ffffff',
  'leaf-color-header-submenu-bg-pressed': '#035c67',
  'leaf-color-header-submenu-content-pressed': '#ffffff',
  'leaf-color-footer-bg-default': '#fbfbfa',
  'leaf-color-footer-bg-secondary': '#ffffff',
  'leaf-color-footer-content-default': '#2d2d2d',
  'leaf-color-footer-content-secondary': '#ffffff',
  'leaf-color-footer-link-default': '#035c67',
  'leaf-color-footer-link-hover': '#012529',
  'leaf-spacing-0': 0,
  'leaf-spacing-2': 2,
  'leaf-spacing-4': 4,
  'leaf-spacing-6': 6,
  'leaf-spacing-8': 8,
  'leaf-spacing-12': 12,
  'leaf-spacing-14': 14,
  'leaf-spacing-16': 16,
  'leaf-spacing-18': 18,
  'leaf-spacing-24': 24,
  'leaf-spacing-32': 32,
  'leaf-spacing-40': 40,
  'leaf-spacing-48': 48,
  'leaf-spacing-64': 64,
  'leaf-spacing-80': 80,
  'leaf-spacing-96': 96,
  'leaf-spacing-120': 120,
  'leaf-spacing-160': 160,
  'leaf-color-button-primary-bg': '#035c67',
  'leaf-color-button-primary-bg-hover': '#024a52',
  'leaf-color-button-primary-bg-active': '#012529',
  'leaf-color-button-primary-bg-disabled': '#eaeaea',
  'leaf-color-button-primary-border': '#035c67',
  'leaf-color-button-primary-border-hover': '#024a52',
  'leaf-color-button-primary-border-active': '#012529',
  'leaf-color-button-primary-border-disabled': '#eaeaea',
  'leaf-color-button-primary-content': '#ffffff',
  'leaf-color-button-primary-content-hover': '#ffffff',
  'leaf-color-button-primary-content-active': '#ffffff',
  'leaf-color-button-primary-content-disabled': '#949494',
  'leaf-color-button-primary-outline': '#012529',
  'leaf-color-button-secondary-bg': '#cbe6ea',
  'leaf-color-button-secondary-bg-hover': '#cbe6ea',
  'leaf-color-button-secondary-bg-active': '#cbe6ea',
  'leaf-color-button-secondary-bg-disabled': '#eaeaea',
  'leaf-color-button-secondary-border': '#cbe6ea',
  'leaf-color-button-secondary-border-hover': '#035c67',
  'leaf-color-button-secondary-border-active': '#012529',
  'leaf-color-button-secondary-border-disabled': '#ababab',
  'leaf-color-button-secondary-content': '#035c67',
  'leaf-color-button-secondary-content-hover': '#035c67',
  'leaf-color-button-secondary-content-active': '#012529',
  'leaf-color-button-secondary-content-disabled': '#949494',
  'leaf-color-button-secondary-outline': '#012529',
  'leaf-color-button-tertiary-bg': 'rgba( #2d2d2d,0.0)',
  'leaf-color-button-tertiary-bg-hover': 'rgba( #2d2d2d,0.0)',
  'leaf-color-button-tertiary-bg-active': 'rgba( #2d2d2d,0.0)',
  'leaf-color-button-tertiary-bg-disabled': 'rgba( #2d2d2d,0.0)',
  'leaf-color-button-tertiary-border': 'rgba( #2d2d2d,0.0)',
  'leaf-color-button-tertiary-border-hover': '#012529',
  'leaf-color-button-tertiary-border-active': '#012529',
  'leaf-color-button-tertiary-border-disabled': 'rgba( #2d2d2d,0.0)',
  'leaf-color-button-tertiary-content': '#035c67',
  'leaf-color-button-tertiary-content-hover': '#012529',
  'leaf-color-button-tertiary-content-active': '#012529',
  'leaf-color-button-tertiary-content-disabled': '#949494',
  'leaf-color-button-tertiary-outline': '#012529',
  'leaf-button-padding-vertical-small': 8,
  'leaf-button-padding-vertical-medium': 12,
  'leaf-button-padding-vertical-icon-only': 4,
  'leaf-button-padding-vertical-large': 16,
  'leaf-button-padding-horizontal-small': 16,
  'leaf-button-padding-horizontal-medium': 24,
  'leaf-button-padding-horizontal-large': 32,
  'leaf-button-padding-horizontal-icon-only': 4,
  'leaf-color-bg-default': '#ffffff',
  'leaf-color-bg-subtle': '#fbfbfa',
  'leaf-color-bg-strong': '#2d2d2d',
  'leaf-color-bg-disabled': '#eaeaea',
  'leaf-color-bg-success': '#e6f1f0',
  'leaf-color-bg-success-strong': '#007766',
  'leaf-color-bg-error': '#fdeeee',
  'leaf-color-bg-error-strong': '#bb4242',
  'leaf-color-bg-warning': '#fcf5e5',
  'leaf-color-bg-warning-strong': '#e89f12',
  'leaf-color-bg-info': '#e6eff1',
  'leaf-color-bg-info-strong': '#035c67',
  'leaf-color-bg-attention': '#e1fff5',
  'leaf-color-bg-attention-strong': '#035c67',
  'leaf-color-bg-default-hover': '#e6eff1',
  'leaf-color-bg-brand': '#e6eff1',
  'leaf-color-bg-brand-hover': '#cbe6ea',
  'leaf-color-bg-brand-strong': '#035c67',
  'leaf-color-bg-brand-strong-hover': '#024a52',
  'leaf-color-bg-brand-strong-active': '#012529',
  'leaf-color-bg-brand-xstrong': '#012529',
  'leaf-color-bg-brand-xstrong-hover': '#011c1f',
  'leaf-color-bg-brand-xstrong-active': '#011c1f',
  'leaf-color-bg-opacity-transparent': 'rgba( #2d2d2d,0.0)',
  'leaf-color-bg-opacity-default': 'rgba(#2d2d2d,0.50)',
  'leaf-color-bg-active': '#2d2d2d',
  'leaf-color-content-default': '#2d2d2d',
  'leaf-color-content-subtle': '#6c6c6c',
  'leaf-color-content-disabled': '#949494',
  'leaf-color-content-link-disabled': '#949494',
  'leaf-color-content-knockout': '#ffffff',
  'leaf-color-content-success': '#00473d',
  'leaf-color-content-success-icon': '#007766',
  'leaf-color-content-error': '#bb4242',
  'leaf-color-content-error-icon': '#ea5353',
  'leaf-color-content-attention-icon': '#002f32',
  'leaf-color-content-brand-knockout': '#e6eff1',
  'leaf-color-content-brand': '#035c67',
  'leaf-color-content-brand-strong': '#035c67',
  'leaf-color-content-link': '#035c67',
  'leaf-color-content-link-hover': '#024a52',
  'leaf-color-content-link-active': '#012529',
  'leaf-color-content-link-visited': '#7522D9',
  'leaf-color-content-warning-icon': '#e89f12',
  'leaf-color-content-info-icon': '#035c67',
  'leaf-color-border-default': '#d5d5d5',
  'leaf-color-border-strong': '#949494',
  'leaf-color-border-knockout': '#ffffff',
  'leaf-color-border-disabled': '#ababab',
  'leaf-color-border-success': '#007766',
  'leaf-color-border-error': '#ea5353',
  'leaf-color-border-warning': '#e89f12',
  'leaf-color-border-info': '#012529',
  'leaf-color-border-attention': '#002f32',
  'leaf-color-border-brand': '#035c67',
  'leaf-color-border-brand-subtle': '#56a1aa',
  'leaf-color-border-brand-strong': '#035c67',
  'leaf-color-border-transparent': 'rgba( #2d2d2d,0.0)',
  'leaf-color-border-active-outline': '#035c67',
  'leaf-font-size-0': 12,
  'leaf-font-size-1': 14,
  'leaf-font-size-2': 16,
  'leaf-font-size-3': 18,
  'leaf-font-size-4': 20,
  'leaf-font-size-5': 24,
  'leaf-font-size-6': 28,
  'leaf-font-size-7': 32,
  'leaf-font-size-8': 40,
  'leaf-font-size-9': 48,
  'leaf-font-size-10': 56,
  'leaf-font-size-11': 64,
  'leaf-font-size-12': 72,
  'leaf-letter-spacing-0': -1.5,
  'leaf-letter-spacing-1': -1,
  'leaf-letter-spacing-2': -0.5,
  'leaf-letter-spacing-3': 0,
  'leaf-letter-spacing-4': 2,
  'leaf-letter-spacing-5': 1,
  'leaf-letter-spacing-6': 1.5,
  'leaf-paragraph-spacing-0': 0,
  'leaf-text-case-none': 'none',
  'leaf-text-case-uppercase': 'uppercase',
  'leaf-text-decoration-none': 'none',
  'leaf-text-decoration-underline': 'underline',
  'leaf-paragraph-indent-0': 0,
  'leaf-border-radius-small': 4,
  'leaf-border-radius-default': 8,
  'leaf-border-radius-large': 16,
  'leaf-border-radius-round': 900,
  'leaf-border-radius-button': 8,
  'leaf-border-radius-badge': 4,
  'leaf-border-radius-tabs': 8,
  'leaf-border-radius-container': 16,
  'leaf-border-radius-field': 8,
  'leaf-border-width-none': 0,
  'leaf-border-width-default': 1,
  'leaf-border-width-focus': 2,
  'leaf-border-width-large': 4,
  'leaf-border-width-button-tertiary-outline-focus': 2,
  'leaf-border-width-button-default': 2,
  'leaf-border-width-tab-selected': 2,
  'leaf-border-style-button-tertiary-outline-focus': 'solid',
  'leaf-border-style-default': 'solid',
  'leaf-shadow-default': {
    shadowOpacity: 1,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
    shadowRadius: 6,
    shadowColor: 'rgba(0,0,0,0.1)'
  },
  'leaf-shadow-button': undefined,
  'leaf-shadow-none': undefined,
  'leaf-shadow-large': {
    shadowOpacity: 1,
    shadowOffset: { width: 0, height: 10 },
    elevation: 4,
    shadowRadius: 12,
    shadowColor: 'rgba(0,0,0,0.2)'
  },
  'leaf-shadow-small': {
    shadowOpacity: 1,
    shadowOffset: { width: 0, height: 1 },
    elevation: 1,
    shadowRadius: 2,
    shadowColor: 'rgba(0,0,0,0.2)'
  },
  'leaf-color-link-bg-active': '#333333',
  'leaf-font-families-nb-akademie': '"NB Akademie", sans-serif',
  'leaf-font-weights-nb-akademie-0': '400',
  'leaf-font-weights-nb-akademie-1': '500',
  'leaf-font-weights-nb-akademie-2': '700',
  'leaf-line-heights-0': 1.25,
  'leaf-line-heights-1': 1.12,
  'leaf-line-heights-2': 1.1400000000000001,
  'leaf-line-heights-3': 1.2,
  'leaf-line-heights-4': 1.3,
  'leaf-line-heights-5': 1.33,
  'leaf-line-heights-6': 1.4000000000000001,
  'leaf-line-heights-7': 1.5,
  'leaf-line-heights-8': 1.43,
  'leaf-line-heights-9': 1.11,
  'leaf-line-heights-10': 1.1300000000000001,
  'leaf-line-heights-11': 1.16,
  'leaf-line-heights-12': 48,
  'leaf-line-heights-13': 40,
  'leaf-line-heights-14': 32,
  'leaf-line-heights-15': 28,
  'leaf-line-heights-16': 24,
  'leaf-line-heights-17': 20,
  'leaf-line-heights-18': 16,
  'leaf-body-default': {
    fontFamily: '"NB Akademie", sans-serif',
    fontWeight: '400',
    fontSize: 16,
    letterSpacing: 0,
    lineHeight: 24,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-body-large': {
    fontFamily: '"NB Akademie", sans-serif',
    fontWeight: '400',
    fontSize: 18,
    letterSpacing: 0,
    lineHeight: 19.98,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-body-small': {
    fontFamily: '"NB Akademie", sans-serif',
    fontWeight: '400',
    fontSize: 14,
    letterSpacing: 0,
    lineHeight: 20.02,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-body-default-link': {
    fontFamily: '"NB Akademie", sans-serif',
    fontWeight: '500',
    fontSize: 16,
    letterSpacing: 0,
    lineHeight: 24,
    textTransform: 'none',
    textDecorationLine: 'underline'
  },
  'leaf-body-small-link': {
    fontFamily: '"NB Akademie", sans-serif',
    fontWeight: '500',
    fontSize: 14,
    letterSpacing: 0,
    lineHeight: 20.02,
    textTransform: 'none',
    textDecorationLine: 'underline'
  },
  'leaf-body-large-link': {
    fontFamily: '"NB Akademie", sans-serif',
    fontWeight: '500',
    fontSize: 18,
    letterSpacing: 0,
    lineHeight: 19.98,
    textTransform: 'none',
    textDecorationLine: 'underline'
  },
  'leaf-label-default': {
    fontFamily: '"NB Akademie", sans-serif',
    fontWeight: '500',
    fontSize: 16,
    letterSpacing: 0,
    lineHeight: 24,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-label-large': {
    fontFamily: '"NB Akademie", sans-serif',
    fontWeight: '500',
    fontSize: 20,
    letterSpacing: 0,
    lineHeight: 24,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-label-small': {
    fontFamily: '"NB Akademie", sans-serif',
    fontWeight: '500',
    fontSize: 14,
    letterSpacing: 0,
    lineHeight: 21,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-title-default': {
    fontFamily: '"NB Akademie", sans-serif',
    fontWeight: '500',
    fontSize: 24,
    letterSpacing: 0,
    lineHeight: 27.36,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-title-xlarge': {
    fontFamily: '"NB Akademie", sans-serif',
    fontWeight: '500',
    fontSize: 40,
    letterSpacing: 0,
    lineHeight: 52,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-title-xlarge-mobile': {
    fontFamily: '"NB Akademie", sans-serif',
    fontWeight: '500',
    fontSize: 32,
    letterSpacing: 0,
    lineHeight: 41.6,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-title-large': {
    fontFamily: '"NB Akademie", sans-serif',
    fontWeight: '500',
    fontSize: 28,
    letterSpacing: 0,
    lineHeight: 31.36,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-title-large-mobile': {
    fontFamily: '"NB Akademie", sans-serif',
    fontWeight: '500',
    fontSize: 28,
    letterSpacing: 0,
    lineHeight: 31.36,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-title-small': {
    fontFamily: '"NB Akademie", sans-serif',
    fontWeight: '500',
    fontSize: 18,
    letterSpacing: 0,
    lineHeight: 25.2,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-title-small-mobile': {
    fontFamily: '"NB Akademie", sans-serif',
    fontWeight: '500',
    fontSize: 16,
    letterSpacing: 0,
    lineHeight: 22.4,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-headline-default': {
    fontFamily: '"NB Akademie", sans-serif',
    fontWeight: '700',
    fontSize: 40,
    letterSpacing: -1.5,
    lineHeight: 50,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-headline-default-mobile': {
    fontFamily: '"NB Akademie", sans-serif',
    fontWeight: '700',
    fontSize: 32,
    letterSpacing: 0,
    lineHeight: 40,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-headline-large': {
    fontFamily: '"NB Akademie", sans-serif',
    fontWeight: '700',
    fontSize: 48,
    letterSpacing: -1.5,
    lineHeight: 57.6,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-headline-large-mobile': {
    fontFamily: '"NB Akademie", sans-serif',
    fontWeight: '700',
    fontSize: 40,
    letterSpacing: 0,
    lineHeight: 45.6,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-headline-small': {
    fontFamily: '"NB Akademie", sans-serif',
    fontWeight: '700',
    fontSize: 32,
    letterSpacing: -0.5,
    lineHeight: 38.4,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-headline-xsmall': {
    fontFamily: '"NB Akademie", sans-serif',
    fontWeight: '700',
    fontSize: 24,
    letterSpacing: 0,
    lineHeight: 27.36,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-headline-small-mobile': {
    fontFamily: '"NB Akademie", sans-serif',
    fontWeight: '700',
    fontSize: 28,
    letterSpacing: 0,
    lineHeight: 35,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-display-default': {
    fontFamily: '"NB Akademie", sans-serif',
    fontWeight: '700',
    fontSize: 64,
    letterSpacing: -1,
    lineHeight: 72.96,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-display-default-mobile': {
    fontFamily: '"NB Akademie", sans-serif',
    fontWeight: '700',
    fontSize: 56,
    letterSpacing: -1.5,
    lineHeight: 63.84,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-display-small': {
    fontFamily: '"NB Akademie", sans-serif',
    fontWeight: '700',
    fontSize: 48,
    letterSpacing: -1,
    lineHeight: 54.72,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-display-small-mobile': {
    fontFamily: '"NB Akademie", sans-serif',
    fontWeight: '700',
    fontSize: 40,
    letterSpacing: -1,
    lineHeight: 45.6,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-meta-default': {
    fontFamily: '"NB Akademie", sans-serif',
    fontWeight: '700',
    fontSize: 16,
    letterSpacing: 1,
    lineHeight: 19.2,
    textTransform: 'uppercase',
    textDecorationLine: 'none'
  },
  'leaf-meta-default-sentence-case': {
    fontFamily: '"NB Akademie", sans-serif',
    fontWeight: '700',
    fontSize: 16,
    letterSpacing: 0,
    lineHeight: 18.56,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-meta-large': {
    fontFamily: '"NB Akademie", sans-serif',
    fontWeight: '700',
    fontSize: 20,
    letterSpacing: 1.5,
    lineHeight: 24,
    textTransform: 'uppercase',
    textDecorationLine: 'none'
  },
  'leaf-meta-small': {
    fontFamily: '"NB Akademie", sans-serif',
    fontWeight: '700',
    fontSize: 14,
    letterSpacing: 1,
    lineHeight: 16.8,
    textTransform: 'uppercase',
    textDecorationLine: 'none'
  },
  'leaf-icon-size-small': 14,
  'leaf-icon-size-default': 16,
  'leaf-icon-size-large': 18,
  'leaf-badge-padding-horizontal': 6,
  'leaf-badge-padding-vertical': 2,
  'leaf-progress-meter-height': 8,
  'leaf-breakpoints-bp-xsm': '23.4375rem',
  'leaf-breakpoints-bp-sm': '35rem',
  'leaf-breakpoints-bp-md': '48rem',
  'leaf-breakpoints-bp-lg': '60rem',
  'leaf-breakpoints-bp-xl': '75rem',
  'leaf-breakpoints-bp-xxl': '87.5rem',
  'leaf-asset-font-nb-akademie-400-normal': 'NB Akademie-Regular',
  'leaf-asset-font-nb-akademie-500-medium': 'NB Akademie-Medium',
  'leaf-asset-font-nb-akademie-700-normal': 'NB Akademie-Bold'
}