/**
 * Do not edit directly
 * Generated on Sun, 27 Oct 2024 04:05:11 GMT
 */


module.exports = {
  'cre8-desktop-menu-padding-vertical-padding': 16,
  'cre8-desktop-menu-padding-horizontal-padding': 8,
  'cre8-color-header-bg-default': '#ffffff',
  'cre8-color-header-inverse-bg-default': '#f4f4f4',
  'cre8-color-header-bg-secondary': '#f4f4f4',
  'cre8-color-header-inverse-bg-secondary': '#333333',
  'cre8-color-header-bg-tertiary': '#f4f4f4',
  'cre8-color-header-inverse-bg-tertiary': '#ffffff',
  'cre8-color-header-menu-bg-default': '#ffffff',
  'cre8-color-header-menu-inverse-bg-default': '#f4f4f4',
  'cre8-color-header-menu-bg-selected': '#ffffff',
  'cre8-color-header-menu-inverse-bg-selected': '#f4f4f4',
  'cre8-color-header-menu-bg-hover': '#e6ebff',
  'cre8-color-header-menu-inverse-bg-hover': '#ebebeb',
  'cre8-color-header-menu-bg-pressed': '#ccd6ff',
  'cre8-color-header-menu-inverse-bg-pressed': '#d6d6d6',
  'cre8-color-header-menu-bg-active': '#110081',
  'cre8-color-header-menu-inverse-bg-active': '#d6d6d6',
  'cre8-color-header-menu-bg-focus': '#0a004d',
  'cre8-color-header-menu-inverse-bg-focus': '#333333',
  'cre8-color-header-menu-content-default': '#110081',
  'cre8-color-header-menu-inverse-content-default': '#333333',
  'cre8-color-header-menu-content-hover': '#110081',
  'cre8-color-header-menu-inverse-content-hover': '#110081',
  'cre8-color-header-menu-content-pressed': '#110081',
  'cre8-color-header-menu-inverse-content-pressed': '#333333',
  'cre8-color-header-menu-content-active': '#ffffff',
  'cre8-color-header-menu-inverse-content-active': '#333333',
  'cre8-color-header-menu-content-selected': '#110081',
  'cre8-color-header-menu-inverse-content-selected': '#110081',
  'cre8-color-header-menu-content-focus': '#ffffff',
  'cre8-color-header-menu-inverse-content-focus': '#ffffff',
  'cre8-color-header-menu-border-default': '#f4f4f4',
  'cre8-color-header-menu-inverse-border-default': '#110081',
  'cre8-color-header-menu-border-pressed': '#110081',
  'cre8-color-header-menu-inverse-border-pressed': '#f4f4f4',
  'cre8-color-header-menu-border-active': '#110081',
  'cre8-color-header-menu-inverse-border-active': '#f4f4f4',
  'cre8-color-header-menu-border-selected': '#110081',
  'cre8-color-header-menu-inverse-border-selected': '#110081',
  'cre8-color-header-menu-border-focus': '#0a004d',
  'cre8-color-header-menu-inverse-border-focus': '#333333',
  'cre8-color-header-menu-border-hover': '#e6ebff',
  'cre8-color-header-menu-inverse-border-hover': '#ebebeb',
  'cre8-color-header-submenu-bg-default': '#ffffff',
  'cre8-color-header-submenu-inverse-bg-default': '#ffffff',
  'cre8-color-header-submenu-bg-hover': '#e6ebff',
  'cre8-color-header-submenu-inverse-bg-hover': '#e6ebff',
  'cre8-color-header-submenu-bg-pressed': '#ccd6ff',
  'cre8-color-header-submenu-inverse-bg-pressed': '#ccd6ff',
  'cre8-color-header-submenu-bg-active': '#110081',
  'cre8-color-header-submenu-inverse-bg-active': '#110081',
  'cre8-color-header-submenu-bg-focus': '#110081',
  'cre8-color-header-submenu-inverse-bg-focus': '#110081',
  'cre8-color-header-submenu-bg-selected': '#ffffff',
  'cre8-color-header-submenu-inverse-bg-selected': '#ffffff',
  'cre8-color-header-submenu-content-default': '#110081',
  'cre8-color-header-submenu-inverse-content-default': '#110081',
  'cre8-color-header-submenu-content-hover': '#110081',
  'cre8-color-header-submenu-inverse-content-hover': '#110081',
  'cre8-color-header-submenu-content-pressed': '#110081',
  'cre8-color-header-submenu-inverse-content-pressed': '#110081',
  'cre8-color-header-submenu-content-active': '#ffffff',
  'cre8-color-header-submenu-inverse-content-active': '#ffffff',
  'cre8-color-header-submenu-content-focus': '#ffffff',
  'cre8-color-header-submenu-inverse-content-focus': '#ffffff',
  'cre8-color-header-submenu-content-selected': '#110081',
  'cre8-color-header-submenu-inverse-content-selected': '#110081',
  'cre8-color-header-submenu-border-default': '#ffffff',
  'cre8-color-header-submenu-inverse-border-default': '#ffffff',
  'cre8-color-header-submenu-border-hover': '#e6ebff',
  'cre8-color-header-submenu-inverse-border-hover': '#e6ebff',
  'cre8-color-header-submenu-border-focus': '#110081',
  'cre8-color-header-submenu-inverse-border-focus': '#110081',
  'cre8-color-header-submenu-border-active': '#110081',
  'cre8-color-header-submenu-inverse-border-active': '#110081',
  'cre8-color-header-submenu-border-pressed': '#ccd6ff',
  'cre8-color-header-submenu-inverse-border-pressed': '#ccd6ff',
  'cre8-color-header-submenu-border-selected': '#110081',
  'cre8-color-header-submenu-inverse-border-selected': '#110081',
  'cre8-spacing-0': 0,
  'cre8-spacing-2': 2,
  'cre8-spacing-4': 4,
  'cre8-spacing-6': 6,
  'cre8-spacing-8': 8,
  'cre8-spacing-12': 12,
  'cre8-spacing-14': 14,
  'cre8-spacing-16': 16,
  'cre8-spacing-18': 18,
  'cre8-spacing-24': 24,
  'cre8-spacing-32': 32,
  'cre8-spacing-40': 40,
  'cre8-spacing-48': 48,
  'cre8-spacing-64': 64,
  'cre8-spacing-80': 80,
  'cre8-spacing-96': 96,
  'cre8-spacing-120': 120,
  'cre8-spacing-160': 160,
  'cre8-color-footer-bg-default': '#f4f4f4',
  'cre8-color-footer-bg-secondary': '#ffffff',
  'cre8-color-footer-content-default': '#333333',
  'cre8-color-footer-content-secondary': '#333333',
  'cre8-color-footer-link-default': '#0033ff',
  'cre8-color-footer-link-hover': '#110081',
  'cre8-color-button-primary-danger-bg': '#ba0000',
  'cre8-color-button-primary-danger-inverse-bg': '#d66666',
  'cre8-color-button-primary-danger-bg-hover': '#700000',
  'cre8-color-button-primary-danger-inverse-bg-hover': '#e39999',
  'cre8-color-button-primary-danger-bg-active': '#4a0000',
  'cre8-color-button-primary-danger-inverse-bg-active': '#f1cccc',
  'cre8-color-button-primary-danger-bg-disabled': '#ebebeb',
  'cre8-color-button-primary-danger-inverse-bg-disabled': '#adadad',
  'cre8-color-button-primary-danger-content': '#ffffff',
  'cre8-color-button-primary-danger-inverse-content': '#333333',
  'cre8-color-button-primary-danger-content-hover': '#ffffff',
  'cre8-color-button-primary-danger-inverse-content-hover': '#333333',
  'cre8-color-button-primary-danger-content-active': '#ffffff',
  'cre8-color-button-primary-danger-inverse-content-active': '#333333',
  'cre8-color-button-primary-danger-content-disabled': '#999999',
  'cre8-color-button-primary-danger-inverse-content-disabled': '#707070',
  'cre8-color-button-primary-danger-border': '#ba0000',
  'cre8-color-button-primary-danger-inverse-border': '#d66666',
  'cre8-color-button-primary-danger-border-hover': '#700000',
  'cre8-color-button-primary-danger-inverse-border-hover': '#e39999',
  'cre8-color-button-primary-danger-border-active': '#4a0000',
  'cre8-color-button-primary-danger-inverse-border-active': '#f1cccc',
  'cre8-color-button-primary-danger-border-disabled': '#ebebeb',
  'cre8-color-button-primary-danger-inverse-border-disabled': '#adadad',
  'cre8-color-button-primary-danger-outline': '#333333',
  'cre8-color-button-primary-danger-inverse-outline': '#ffffff',
  'cre8-color-button-primary-bg': '#0033ff',
  'cre8-color-button-primary-inverse-bg': '#ffffff',
  'cre8-color-button-primary-bg-hover': '#001f99',
  'cre8-color-button-primary-inverse-bg-hover': '#e6ebff',
  'cre8-color-button-primary-bg-active': '#001466',
  'cre8-color-button-primary-inverse-bg-active': '#ccd6ff',
  'cre8-color-button-primary-bg-disabled': '#8099ff',
  'cre8-color-button-primary-inverse-bg-disabled': '#8880c0',
  'cre8-color-button-primary-border': '#0033ff',
  'cre8-color-button-primary-inverse-border': '#ffffff',
  'cre8-color-button-primary-border-hover': '#001f99',
  'cre8-color-button-primary-inverse-border-hover': '#e6ebff',
  'cre8-color-button-primary-border-active': '#001466',
  'cre8-color-button-primary-inverse-border-active': '#ccd6ff',
  'cre8-color-button-primary-border-disabled': '#8099ff',
  'cre8-color-button-primary-inverse-border-disabled': '#8880c0',
  'cre8-color-button-primary-content': '#ffffff',
  'cre8-color-button-primary-inverse-content': '#0033ff',
  'cre8-color-button-primary-content-hover': '#ffffff',
  'cre8-color-button-primary-inverse-content-hover': '#0033ff',
  'cre8-color-button-primary-content-active': '#ffffff',
  'cre8-color-button-primary-inverse-content-active': '#0033ff',
  'cre8-color-button-primary-content-disabled': '#ffffff',
  'cre8-color-button-primary-inverse-content-disabled': '#584da7',
  'cre8-color-button-primary-outline': '#333333',
  'cre8-color-button-primary-inverse-outline': '#ffffff',
  'cre8-color-button-secondary-neutral-bg': 'rgba(#333333,0.0)',
  'cre8-color-button-secondary-neutral-inverse-bg': 'rgba(#333333,0.0)',
  'cre8-color-button-secondary-neutral-content': '#333333',
  'cre8-color-button-secondary-neutral-inverse-content': '#ffffff',
  'cre8-color-button-secondary-neutral-border': '#333333',
  'cre8-color-button-secondary-neutral-inverse-border': '#ffffff',
  'cre8-color-button-secondary-neutral-bg-hover': 'rgba( #333333,0.10)',
  'cre8-color-button-secondary-neutral-inverse-bg-hover': 'rgba( #333333,0.20)',
  'cre8-color-button-secondary-neutral-content-hover': '#333333',
  'cre8-color-button-secondary-neutral-inverse-content-hover': '#ffffff',
  'cre8-color-button-secondary-neutral-border-hover': '#333333',
  'cre8-color-button-secondary-neutral-inverse-border-hover': '#ffffff',
  'cre8-color-button-secondary-neutral-border-active': '#333333',
  'cre8-color-button-secondary-neutral-inverse-border-active': '#ffffff',
  'cre8-color-button-secondary-neutral-bg-active': 'rgba( #333333,0.20)',
  'cre8-color-button-secondary-neutral-inverse-bg-active': 'rgba(#333333,0.50)',
  'cre8-color-button-secondary-neutral-content-active': '#333333',
  'cre8-color-button-secondary-neutral-inverse-content-active': '#ffffff',
  'cre8-color-button-secondary-neutral-bg-disabled': '#ebebeb',
  'cre8-color-button-secondary-neutral-inverse-bg-disabled': '#adadad',
  'cre8-color-button-secondary-neutral-border-disabled': '#ebebeb',
  'cre8-color-button-secondary-neutral-inverse-border-disabled': '#adadad',
  'cre8-color-button-secondary-neutral-content-disabled': '#999999',
  'cre8-color-button-secondary-neutral-inverse-content-disabled': '#707070',
  'cre8-color-button-secondary-neutral-outline': '#333333',
  'cre8-color-button-secondary-neutral-inverse-outline': '#ffffff',
  'cre8-color-button-secondary-danger-bg': 'rgba(#333333,0.0)',
  'cre8-color-button-secondary-danger-inverse-bg': 'rgba(#333333,0.0)',
  'cre8-color-button-secondary-danger-bg-hover': '#700000',
  'cre8-color-button-secondary-danger-inverse-bg-hover': '#e39999',
  'cre8-color-button-secondary-danger-bg-active': '#4a0000',
  'cre8-color-button-secondary-danger-inverse-bg-active': '#f1cccc',
  'cre8-color-button-secondary-danger-bg-disabled': '#ebebeb',
  'cre8-color-button-secondary-danger-inverse-bg-disabled': '#adadad',
  'cre8-color-button-secondary-danger-content': '#ba0000',
  'cre8-color-button-secondary-danger-inverse-content': '#d66666',
  'cre8-color-button-secondary-danger-content-hover': '#ffffff',
  'cre8-color-button-secondary-danger-inverse-content-hover': '#333333',
  'cre8-color-button-secondary-danger-content-active': '#ffffff',
  'cre8-color-button-secondary-danger-inverse-content-active': '#333333',
  'cre8-color-button-secondary-danger-content-disabled': '#999999',
  'cre8-color-button-secondary-danger-inverse-content-disabled': '#707070',
  'cre8-color-button-secondary-danger-border': '#ba0000',
  'cre8-color-button-secondary-danger-inverse-border': '#d66666',
  'cre8-color-button-secondary-danger-border-hover': '#700000',
  'cre8-color-button-secondary-danger-inverse-border-hover': '#e39999',
  'cre8-color-button-secondary-danger-border-active': '#4a0000',
  'cre8-color-button-secondary-danger-inverse-border-active': '#f1cccc',
  'cre8-color-button-secondary-danger-border-disabled': '#ebebeb',
  'cre8-color-button-secondary-danger-inverse-border-disabled': '#adadad',
  'cre8-color-button-secondary-danger-outline': '#333333',
  'cre8-color-button-secondary-danger-inverse-outline': '#ffffff',
  'cre8-color-button-secondary-bg': 'rgba(#333333,0.0)',
  'cre8-color-button-secondary-inverse-bg': 'rgba(#333333,0.0)',
  'cre8-color-button-secondary-bg-hover': '#e6ebff',
  'cre8-color-button-secondary-inverse-bg-hover': '#0a004d',
  'cre8-color-button-secondary-bg-active': '#ccd6ff',
  'cre8-color-button-secondary-inverse-bg-active': '#070034',
  'cre8-color-button-secondary-bg-disabled': 'rgba(#333333,0.0)',
  'cre8-color-button-secondary-inverse-bg-disabled': 'rgba(#333333,0.0)',
  'cre8-color-button-secondary-border': '#0033ff',
  'cre8-color-button-secondary-inverse-border': '#ffffff',
  'cre8-color-button-secondary-border-hover': '#0033ff',
  'cre8-color-button-secondary-inverse-border-hover': '#ffffff',
  'cre8-color-button-secondary-border-active': '#0033ff',
  'cre8-color-button-secondary-inverse-border-active': '#ffffff',
  'cre8-color-button-secondary-border-disabled': '#8099ff',
  'cre8-color-button-secondary-inverse-border-disabled': '#999999',
  'cre8-color-button-secondary-content-disabled': '#8099ff',
  'cre8-color-button-secondary-inverse-content-disabled': '#999999',
  'cre8-color-button-secondary-content': '#0033ff',
  'cre8-color-button-secondary-inverse-content': '#ffffff',
  'cre8-color-button-secondary-content-hover': '#0033ff',
  'cre8-color-button-secondary-inverse-content-hover': '#ffffff',
  'cre8-color-button-secondary-content-active': '#0033ff',
  'cre8-color-button-secondary-inverse-content-active': '#ffffff',
  'cre8-color-button-secondary-outline': '#333333',
  'cre8-color-button-secondary-inverse-outline': '#ffffff',
  'cre8-color-button-tertiary-neutral-bg': 'rgba(#333333,0.0)',
  'cre8-color-button-tertiary-neutral-inverse-bg': 'rgba(#333333,0.0)',
  'cre8-color-button-tertiary-neutral-content': '#333333',
  'cre8-color-button-tertiary-neutral-inverse-content': '#ffffff',
  'cre8-color-button-tertiary-neutral-border': 'rgba(#333333,0.0)',
  'cre8-color-button-tertiary-neutral-inverse-border': 'rgba(#333333,0.0)',
  'cre8-color-button-tertiary-neutral-bg-hover': 'rgba(#333333,0.0)',
  'cre8-color-button-tertiary-neutral-inverse-bg-hover': 'rgba(#333333,0.0)',
  'cre8-color-button-tertiary-neutral-content-hover': '#333333',
  'cre8-color-button-tertiary-neutral-inverse-content-hover': '#ffffff',
  'cre8-color-button-tertiary-neutral-border-hover': '#333333',
  'cre8-color-button-tertiary-neutral-inverse-border-hover': '#ffffff',
  'cre8-color-button-tertiary-neutral-border-active': '#333333',
  'cre8-color-button-tertiary-neutral-inverse-border-active': '#ffffff',
  'cre8-color-button-tertiary-neutral-bg-active': 'rgba(#333333,0.0)',
  'cre8-color-button-tertiary-neutral-inverse-bg-active': 'rgba(#333333,0.0)',
  'cre8-color-button-tertiary-neutral-content-active': '#333333',
  'cre8-color-button-tertiary-neutral-inverse-content-active': '#ffffff',
  'cre8-color-button-tertiary-neutral-bg-disabled': 'rgba(#333333,0.0)',
  'cre8-color-button-tertiary-neutral-inverse-bg-disabled': 'rgba(#333333,0.0)',
  'cre8-color-button-tertiary-neutral-border-disabled': 'rgba(#333333,0.0)',
  'cre8-color-button-tertiary-neutral-inverse-border-disabled': 'rgba(#333333,0.0)',
  'cre8-color-button-tertiary-neutral-content-disabled': '#999999',
  'cre8-color-button-tertiary-neutral-inverse-content-disabled': '#707070',
  'cre8-color-button-tertiary-neutral-outline': '#333333',
  'cre8-color-button-tertiary-neutral-inverse-outline': '#ffffff',
  'cre8-color-button-tertiary-danger-bg': 'rgba(#333333,0.0)',
  'cre8-color-button-tertiary-danger-inverse-bg': 'rgba(#333333,0.0)',
  'cre8-color-button-tertiary-danger-bg-hover': '#700000',
  'cre8-color-button-tertiary-danger-inverse-bg-hover': '#e39999',
  'cre8-color-button-tertiary-danger-bg-active': '#4a0000',
  'cre8-color-button-tertiary-danger-inverse-bg-active': '#f1cccc',
  'cre8-color-button-tertiary-danger-bg-disabled': '#ebebeb',
  'cre8-color-button-tertiary-danger-inverse-bg-disabled': '#adadad',
  'cre8-color-button-tertiary-danger-content': '#ba0000',
  'cre8-color-button-tertiary-danger-inverse-content': '#d66666',
  'cre8-color-button-tertiary-danger-content-hover': '#ffffff',
  'cre8-color-button-tertiary-danger-inverse-content-hover': '#333333',
  'cre8-color-button-tertiary-danger-content-active': '#ffffff',
  'cre8-color-button-tertiary-danger-inverse-content-active': '#333333',
  'cre8-color-button-tertiary-danger-content-disabled': '#999999',
  'cre8-color-button-tertiary-danger-inverse-content-disabled': '#707070',
  'cre8-color-button-tertiary-danger-border': 'rgba(#333333,0.0)',
  'cre8-color-button-tertiary-danger-inverse-border': 'rgba(#333333,0.0)',
  'cre8-color-button-tertiary-danger-border-hover': '#700000',
  'cre8-color-button-tertiary-danger-inverse-border-hover': '#e39999',
  'cre8-color-button-tertiary-danger-border-active': '#4a0000',
  'cre8-color-button-tertiary-danger-inverse-border-active': '#f1cccc',
  'cre8-color-button-tertiary-danger-border-disabled': '#ebebeb',
  'cre8-color-button-tertiary-danger-inverse-border-disabled': '#adadad',
  'cre8-color-button-tertiary-danger-outline': '#333333',
  'cre8-color-button-tertiary-danger-inverse-outline': '#ffffff',
  'cre8-color-button-tertiary-bg': 'rgba(#333333,0.0)',
  'cre8-color-button-tertiary-inverse-bg': 'rgba(#333333,0.0)',
  'cre8-color-button-tertiary-bg-hover': 'rgba(#333333,0.0)',
  'cre8-color-button-tertiary-inverse-bg-hover': 'rgba(#333333,0.0)',
  'cre8-color-button-tertiary-bg-active': '#ccd6ff',
  'cre8-color-button-tertiary-inverse-bg-active': '#070034',
  'cre8-color-button-tertiary-bg-disabled': 'rgba(#333333,0.0)',
  'cre8-color-button-tertiary-inverse-bg-disabled': 'rgba(#333333,0.0)',
  'cre8-color-button-tertiary-border': 'rgba(#333333,0.0)',
  'cre8-color-button-tertiary-inverse-border': 'rgba(#333333,0.0)',
  'cre8-color-button-tertiary-border-hover': '#0033ff',
  'cre8-color-button-tertiary-inverse-border-hover': '#ffffff',
  'cre8-color-button-tertiary-border-active': '#0033ff',
  'cre8-color-button-tertiary-inverse-border-active': '#ffffff',
  'cre8-color-button-tertiary-border-disabled': 'rgba(#333333,0.0)',
  'cre8-color-button-tertiary-inverse-border-disabled': 'rgba(#333333,0.0)',
  'cre8-color-button-tertiary-content': '#0033ff',
  'cre8-color-button-tertiary-inverse-content': '#ffffff',
  'cre8-color-button-tertiary-content-hover': '#0033ff',
  'cre8-color-button-tertiary-inverse-content-hover': '#ffffff',
  'cre8-color-button-tertiary-content-active': '#0033ff',
  'cre8-color-button-tertiary-inverse-content-active': '#ffffff',
  'cre8-color-button-tertiary-content-disabled': '#999999',
  'cre8-color-button-tertiary-inverse-content-disabled': '#999999',
  'cre8-color-button-tertiary-outline': '#333333',
  'cre8-color-button-tertiary-inverse-outline': '#ffffff',
  'cre8-button-padding-vertical-small': 8,
  'cre8-button-padding-vertical-medium': 12,
  'cre8-button-padding-vertical-large': 16,
  'cre8-button-padding-vertical-icon-only': 8,
  'cre8-button-padding-vertical-small-icon-only': 8,
  'cre8-button-padding-vertical-medium-icon-only': 16,
  'cre8-button-padding-vertical-large-icon-only': 16,
  'cre8-button-padding-horizontal-small': 16,
  'cre8-button-padding-horizontal-medium': 24,
  'cre8-button-padding-horizontal-large': 32,
  'cre8-button-padding-horizontal-icon-only': 8,
  'cre8-button-padding-horizontal-small-icon-only': 8,
  'cre8-button-padding-horizontal-medium-icon-only': 16,
  'cre8-button-padding-horizontal-large-icon-only': 16,
  'cre8-color-bg-default': '#ffffff',
  'cre8-color-bg-subtle': '#f4f4f4',
  'cre8-color-bg-moderate': '#858585',
  'cre8-color-bg-inverse-moderate': '#adadad',
  'cre8-color-bg-knockout': '#333333',
  'cre8-color-bg-disabled': '#ebebeb',
  'cre8-color-bg-success': '#dae6d1',
  'cre8-color-bg-success-strong': '#488319',
  'cre8-color-bg-error': '#f1cccc',
  'cre8-color-bg-error-strong': '#ba0000',
  'cre8-color-bg-warning': '#fff5d6',
  'cre8-color-bg-warning-strong': '#FFCD34',
  'cre8-color-bg-info': '#ccd6ff',
  'cre8-color-bg-info-strong': '#110081',
  'cre8-color-bg-attention': '#ccd6ff',
  'cre8-color-bg-attention-strong': '#110081',
  'cre8-color-bg-opacity-transparent': 'rgba(#333333,0.0)',
  'cre8-color-bg-opacity-default': 'rgba(#333333,0.50)',
  'cre8-color-bg-brand': '#e6ebff',
  'cre8-color-bg-brand-strong': '#0033ff',
  'cre8-color-bg-brand-strong-hover': '#001f99',
  'cre8-color-bg-brand-strong-active': '#001466',
  'cre8-color-bg-default-hover': '#e6ebff',
  'cre8-color-bg-default-active': '#ccd6ff',
  'cre8-color-bg-brand-hover': '#ccd6ff',
  'cre8-color-bg-brand-active': '#99adff',
  'cre8-color-bg-brand-xstrong': '#110081',
  'cre8-color-bg-brand-xstrong-hover': '#0a004d',
  'cre8-color-bg-brand-xstrong-active': '#070034',
  'cre8-color-bg-active': '#333333',
  'cre8-color-bg-inverse-active': '#ffffff',
  'cre8-color-bg-strong': '#333333',
  'cre8-color-content-default': '#333333',
  'cre8-color-content-subtle': '#5c5c5c',
  'cre8-color-content-disabled': '#858585',
  'cre8-color-content-knockout': '#ffffff',
  'cre8-color-content-brand-knockout': '#ccd6ff',
  'cre8-color-content-brand': '#0033ff',
  'cre8-color-content-brand-strong': '#110081',
  'cre8-color-content-success-icon': '#488319',
  'cre8-color-content-error': '#ba0000',
  'cre8-color-content-error-icon': '#ba0000',
  'cre8-color-content-warning-icon': '#333333',
  'cre8-color-content-info-icon': '#110081',
  'cre8-color-content-attention-icon': '#110081',
  'cre8-color-content-link': '#0033ff',
  'cre8-color-content-inverse-link': '#ffffff',
  'cre8-color-content-link-hover': '#110081',
  'cre8-color-content-inverse-link-hover': '#ccd6ff',
  'cre8-color-content-link-focus': '#ffffff',
  'cre8-color-content-inverse-link-focus': '#333333',
  'cre8-color-content-link-active': '#001466',
  'cre8-color-content-inverse-link-active': '#ccd6ff',
  'cre8-color-content-link-disabled': '#858585',
  'cre8-color-content-inverse-link-disabled': '#d6d6d6',
  'cre8-color-content-link-visted': '#8032df',
  'cre8-color-content-inverse-link-visted': '#e6ebff',
  'cre8-color-content-success': '#3a6914',
  'cre8-color-border-default': '#d6d6d6',
  'cre8-color-border-strong': '#707070',
  'cre8-color-border-knockout': '#ffffff',
  'cre8-color-border-disabled': '#999999',
  'cre8-color-border-brand': '#0033ff',
  'cre8-color-border-brand-subtle': '#ccd6ff',
  'cre8-color-border-brand-strong': '#110081',
  'cre8-color-border-success': '#488319',
  'cre8-color-border-error': '#c83333',
  'cre8-color-border-warning': '#FFCD34',
  'cre8-color-border-info': '#110081',
  'cre8-color-border-attention': '#110081',
  'cre8-color-border-transparent': 'rgba(#333333,0.0)',
  'cre8-color-border-active-outline': '#1f1f1f',
  'cre8-border-button-tertiary-default': 'none',
  'cre8-border-button-tertiary-hover': '2px solid #0033ff',
  'cre8-border-button-tertiary-active': '2px solid #0033ff',
  'cre8-border-button-tertiary-disabled': 'none',
  'cre8-font-size-0': 12,
  'cre8-font-size-1': 14,
  'cre8-font-size-2': 16,
  'cre8-font-size-3': 18,
  'cre8-font-size-4': 20,
  'cre8-font-size-5': 24,
  'cre8-font-size-6': 28,
  'cre8-font-size-7': 32,
  'cre8-font-size-8': 40,
  'cre8-font-size-9': 48,
  'cre8-font-size-10': 56,
  'cre8-font-size-11': 64,
  'cre8-font-size-12': 72,
  'cre8-font-size-13': 80,
  'cre8-letter-spacing-0': -1.5,
  'cre8-letter-spacing-1': -1,
  'cre8-letter-spacing-2': -0.5,
  'cre8-letter-spacing-3': 1,
  'cre8-letter-spacing-4': 2,
  'cre8-letter-spacing-5': 0,
  'cre8-paragraph-spacing-0': 0,
  'cre8-text-case-none': 'none',
  'cre8-text-case-uppercase': 'uppercase',
  'cre8-text-decoration-none': 'none',
  'cre8-text-decoration-underline': 'underline',
  'cre8-paragraph-indent-0': 0,
  'cre8-border-radius-small': 4,
  'cre8-border-radius-default': 8,
  'cre8-border-radius-large': 30,
  'cre8-border-radius-round': 900,
  'cre8-border-radius-button': 900,
  'cre8-border-radius-badge': 4,
  'cre8-border-radius-tabs': 4,
  'cre8-border-radius-container': 30,
  'cre8-border-radius-field': 8,
  'cre8-border-radius-field-brand': 900,
  'cre8-border-radius-brand': 900,
  'cre8-border-radius-none': 0,
  'cre8-border-width-none': 0,
  'cre8-border-width-default': 1,
  'cre8-border-width-focus': 2,
  'cre8-border-width-large': 4,
  'cre8-border-width-button-tertiary-outline-focus': 2,
  'cre8-border-width-button-default': 2,
  'cre8-border-width-tab-selected': 2,
  'cre8-border-width-tab-default': 2,
  'cre8-border-style-button-tertiary-outline-focus': 'solid',
  'cre8-border-style-default': 'solid',
  'cre8-shadow-default': {
    shadowOpacity: 1,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
    shadowRadius: 6,
    shadowColor: 'rgba(0,0,0,0.1)'
  },
  'cre8-shadow-button': undefined,
  'cre8-shadow-none': undefined,
  'cre8-shadow-large': {
    shadowOpacity: 1,
    shadowOffset: { width: 0, height: 10 },
    elevation: 4,
    shadowRadius: 12,
    shadowColor: 'rgba(0,0,0,0.2)'
  },
  'cre8-shadow-small': {
    shadowOpacity: 1,
    shadowOffset: { width: 0, height: 1 },
    elevation: 1,
    shadowRadius: 2,
    shadowColor: 'rgba(0,0,0,0.2)'
  },
  'cre8-color-link-bg-active': '#333333',
  'cre8-font-families-montserrat': '"Montserrat", sans-serif',
  'cre8-font-weights-montserrat-0': '700',
  'cre8-font-weights-montserrat-1': '600',
  'cre8-font-weights-montserrat-2': '400',
  'cre8-font-weights-montserrat-3': '500',
  'cre8-line-heights-0': 1.25,
  'cre8-line-heights-1': 1.12,
  'cre8-line-heights-2': 1.1400000000000001,
  'cre8-line-heights-3': 1.2,
  'cre8-line-heights-4': 1.3,
  'cre8-line-heights-5': 1.33,
  'cre8-line-heights-6': 1.4000000000000001,
  'cre8-line-heights-7': 1.5,
  'cre8-line-heights-8': 1.43,
  'cre8-line-heights-9': 1.11,
  'cre8-line-heights-10': 1.1300000000000001,
  'cre8-line-heights-11': 1.16,
  'cre8-line-heights-12': 48,
  'cre8-line-heights-13': 40,
  'cre8-line-heights-14': 32,
  'cre8-line-heights-15': 28,
  'cre8-line-heights-16': 24,
  'cre8-line-heights-17': 20,
  'cre8-line-heights-18': 16,
  'cre8-display-large': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '700',
    fontSize: 80,
    letterSpacing: -1.5,
    lineHeight: 100,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-display-large-mobile': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '700',
    fontSize: 72,
    letterSpacing: -1.5,
    lineHeight: 90,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-display-default': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '700',
    fontSize: 64,
    letterSpacing: -1.5,
    lineHeight: 72.32,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-display-default-mobile': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '700',
    fontSize: 56,
    letterSpacing: -1.5,
    lineHeight: 63.28,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-display-small': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '700',
    fontSize: 48,
    letterSpacing: -1,
    lineHeight: 55.68,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-display-small-mobile': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '700',
    fontSize: 40,
    letterSpacing: -1,
    lineHeight: 46.4,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-headline-large': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '700',
    fontSize: 48,
    letterSpacing: -1,
    lineHeight: 55.68,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-headline-large-mobile': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '700',
    fontSize: 40,
    letterSpacing: -1,
    lineHeight: 46.4,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-headline-default': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '700',
    fontSize: 40,
    letterSpacing: -0.5,
    lineHeight: 48,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-headline-default-mobile': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '700',
    fontSize: 32,
    letterSpacing: -0.5,
    lineHeight: 38.4,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-headline-small': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '700',
    fontSize: 32,
    letterSpacing: 0,
    lineHeight: 40,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-headline-small-mobile': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '700',
    fontSize: 28,
    letterSpacing: 0,
    lineHeight: 33.6,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-headline-xsmall': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '700',
    fontSize: 24,
    letterSpacing: 0,
    lineHeight: 30,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-headline-xsmall-mobile': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '700',
    fontSize: 24,
    letterSpacing: 0,
    lineHeight: 30,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-title-xlarge': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '700',
    fontSize: 40,
    letterSpacing: 0,
    lineHeight: 50,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-title-xlarge-mobile': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '700',
    fontSize: 32,
    letterSpacing: 0,
    lineHeight: 40,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-title-large': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '700',
    fontSize: 28,
    letterSpacing: 0,
    lineHeight: 31.92,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-title-large-mobile': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '700',
    fontSize: 24,
    letterSpacing: 0,
    lineHeight: 27.36,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-title-default': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '700',
    fontSize: 24,
    letterSpacing: 0,
    lineHeight: 27.84,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-title-default-mobile': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '700',
    fontSize: 18,
    letterSpacing: 0,
    lineHeight: 20.88,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-title-small': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '700',
    fontSize: 16,
    letterSpacing: 0,
    lineHeight: 24,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-title-small-mobile': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '700',
    fontSize: 16,
    letterSpacing: 0,
    lineHeight: 24,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-label-large': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '600',
    fontSize: 18,
    letterSpacing: 0,
    lineHeight: 23.94,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-label-default': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '600',
    fontSize: 16,
    letterSpacing: 0,
    lineHeight: 24,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-label-small': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '600',
    fontSize: 14,
    letterSpacing: 0,
    lineHeight: 20.02,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-body-xlarge': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '400',
    fontSize: 24,
    letterSpacing: 0,
    lineHeight: 36,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-body-xlarge-strong': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '600',
    fontSize: 24,
    letterSpacing: 0,
    lineHeight: 36,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-body-xlarge-link': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '600',
    fontSize: 24,
    letterSpacing: 0,
    lineHeight: 36,
    textTransform: 'none',
    textDecorationLine: 'underline'
  },
  'cre8-body-large': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '400',
    fontSize: 18,
    letterSpacing: 0,
    lineHeight: 27,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-body-large-strong': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '600',
    fontSize: 18,
    letterSpacing: 0,
    lineHeight: 27,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-body-default': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '400',
    fontSize: 16,
    letterSpacing: 0,
    lineHeight: 24,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-body-default-strong': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '600',
    fontSize: 16,
    letterSpacing: 0,
    lineHeight: 24,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-body-small': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '400',
    fontSize: 14,
    letterSpacing: 0,
    lineHeight: 20.02,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-body-small-strong': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '600',
    fontSize: 14,
    letterSpacing: 0,
    lineHeight: 20.02,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-body-large-link': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '600',
    fontSize: 18,
    letterSpacing: 0,
    lineHeight: 27,
    textTransform: 'none',
    textDecorationLine: 'underline'
  },
  'cre8-body-default-link': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '600',
    fontSize: 16,
    letterSpacing: 0,
    lineHeight: 24,
    textTransform: 'none',
    textDecorationLine: 'underline'
  },
  'cre8-body-small-link': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '600',
    fontSize: 14,
    letterSpacing: 0,
    lineHeight: 20.02,
    textTransform: 'none',
    textDecorationLine: 'underline'
  },
  'cre8-meta-default': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '500',
    fontSize: 16,
    letterSpacing: 1,
    lineHeight: 21.28,
    textTransform: 'uppercase',
    textDecorationLine: 'none'
  },
  'cre8-meta-large': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '500',
    fontSize: 20,
    letterSpacing: 1,
    lineHeight: 30,
    textTransform: 'uppercase',
    textDecorationLine: 'none'
  },
  'cre8-meta-default-sentence-case': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '500',
    fontSize: 16,
    letterSpacing: 1,
    lineHeight: 21.28,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'cre8-meta-small': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '500',
    fontSize: 12,
    letterSpacing: 1,
    lineHeight: 15.96,
    textTransform: 'uppercase',
    textDecorationLine: 'none'
  },
  'cre8-icon-size-small': 14,
  'cre8-icon-size-default': 16,
  'cre8-icon-size-large': 18,
  'cre8-badge-padding-horizontal': 8,
  'cre8-badge-padding-vertical': 2,
  'cre8-progress-meter-height': 16,
  'cre8-breakpoint-xsm': '375px',
  'cre8-breakpoint-sm': '560px',
  'cre8-breakpoint-md': '768px',
  'cre8-breakpoint-lg': '960px',
  'cre8-breakpoint-xl': '1200px',
  'cre8-breakpoint-xxl': '1400px',
  'cre8-asset-font-montserrat-400-normal': 'Montserrat-Regular',
  'cre8-asset-font-montserrat-500-normal': 'Montserrat-Medium',
  'cre8-asset-font-montserrat-600-normal': 'Montserrat-SemiBold',
  'cre8-asset-font-montserrat-700-normal': 'Montserrat-Bold'
}