const util = require('util');
const _ = require('lodash');

const reactNativeFormatter = (dictionary) => dictionary.allTokens
    .filter((token) => !token.name.startsWith('cre8-base'))
    .reduce((acc, { name, value }) => ({ ...acc, [name]: value }), {});
const parseTypes = (obj) => Object.entries(obj)
    .map(([key, value]) => {
        const valueType = typeof value;
        const valueStyle = value?.fontFamily ? 'TextStyle' : 'ViewStyle';
        const valueReturn = valueType === 'object' ? valueStyle : valueType;
        return `'${key}': ${valueReturn};`;
    })
    .join('\n  ');

function getMixinName(token, stripMobile) {
    const mixinName = token.name.split('-');
    mixinName.splice(1, 0, token.type);
    const mixinNameStr = mixinName.join('-');
    if (stripMobile) {
        return mixinNameStr.split('-mobile', 1)[0];
    }
    return mixinNameStr;
}

module.exports = (StyleDictionary) => {
    const { fileHeader } = StyleDictionary.formatHelpers;
    const lineSeparator = '\n';

  // Register a custom format to generate @font-face rules.
  // Ref: https://github.com/amzn/style-dictionary/tree/main/examples/advanced/font-face-rules
    StyleDictionary.registerFormat({
        name: 'font-face',
        formatter: ({ dictionary: { allTokens }, options }) => {
            const fontPathPrefix = options.fontPathPrefix || '../';
      // https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/src
            const formatsMap = {
                woff2: 'woff2',
                woff: 'woff',
                ttf: 'truetype',
                otf: 'opentype',
                svg: 'svg',
                eot: 'embedded-opentype',
            };

            return allTokens
                .reduce((fontList, prop) => {
                    const {
                        attributes: { family, weight, style },
                        formats,
                        value: path,
                    } = prop;

                    const urls = formats.map((extension) => {
            // Final formatting structure: url('../path/fontname.extension') format('format type')
                        const fontUrl = `url('${fontPathPrefix}${path}.${extension}')`;
                        const fontFormat = `format('${formatsMap[extension]}')`;

                        return `${fontUrl} ${fontFormat}`;
                    });

                    const fontCss = [
                        '@font-face {',
                        `\n\tfont-family: '${family}';`,
                        `\n\tfont-style: ${style};`,
                        `\n\tfont-weight: ${weight};`,
                        `\n\tsrc: ${urls.join(',\n\t\t\t ')};`,
                        '\n\tfont-display: fallback;',
                        '\n}\n',
                    ].join('');

                    fontList.push(fontCss);

                    return fontList;
                }, [])
                .join('\n');
        },
    });

    StyleDictionary.registerFormat({
        name: 'scss/mixinFormat',
        formatter: ({ dictionary, file }) => {
      // Values pointed to in this formatter are generated by css/typography
            const imports = "@import '../layouts/breakpoints.scss';\n";

            // This selects any token names ending in '-mobile', removes that ending and
            // saves them as a set so as to create the responsive token mixins
            const responsiveTokenNames = new Set(
                dictionary.allTokens
                    .filter((token) => token.name.endsWith('-mobile'))
                    .map((token) => getMixinName(token, true))
            );

            const mixinList = dictionary.allTokens
                .map((token) => {
                    const mixinName = token.name.split('-');
                    mixinName.splice(1, 0, token.type);
                    const mixinFormat = mixinName.join('-');
                    // Here we check if the mixin needs to be responsive,(i.e. included a duplicate-named
                    // token with a mobile variant). We include the mobile mixin outisde of responsive
                    // for teams that may have had a non-cre8 implementaiton and need to deprecate it
                    if (responsiveTokenNames.has(mixinFormat) === true) {
                        return `@mixin ${`${mixinFormat}()`} {
                        font-family: ${`var(--${mixinFormat}-mobile-font-family);`} 
                        font-size: ${`var(--${mixinFormat}-mobile-font-size);`}
                        font-weight: ${`var(--${mixinFormat}-mobile-font-weight);`}
                        line-height: ${`var(--${mixinFormat}-mobile-line-height);`}
                        text-decoration: ${`var(--${mixinFormat}-mobile-text-decoration);`}
                        text-transform: ${`var(--${mixinFormat}-mobile-text-transform);`}
                        @media all and (min-width: $cre8-breakpoint-md) {
                            font-family: ${`var(--${mixinFormat}-font-family);`} 
                            font-size: ${`var(--${mixinFormat}-font-size);`}
                            font-weight: ${`var(--${mixinFormat}-font-weight);`}
                            line-height: ${`var(--${mixinFormat}-line-height);`}
                            text-decoration: ${`var(--${mixinFormat}-text-decoration);`}
                            text-transform: ${`var(--${mixinFormat}-text-transform);`}
                        }
                    };`;
                    }
                    return `
                    @mixin ${`${mixinFormat}()`} {
                        font-family: ${`var(--${mixinFormat}-font-family);`} 
                        font-size: ${`var(--${mixinFormat}-font-size);`}
                        font-weight: ${`var(--${mixinFormat}-font-weight);`}
                        line-height: ${`var(--${mixinFormat}-line-height);`}
                        text-decoration: ${`var(--${mixinFormat}-text-decoration);`}
                        text-transform: ${`var(--${mixinFormat}-text-transform);`}
                    };`;
                })
                .join('\n');

      // The shape we want: --cre8-typography-body-large-font-size
            return fileHeader({ file, commentStyle: 'short' }) + imports + mixinList;
        },
    });

    StyleDictionary.registerFormat({
        name: 'scss/brandWithGlobals',
        formatter: ({ dictionary, file }) => {
            let importStatement = '';

            Object.keys(dictionary.tokens).map((item) => {
                importStatement += `@import './${item}.scss';${lineSeparator}`;
                return importStatement;
            });

      // Insert the import statement with list of separate importable files
            return (
                fileHeader({
                    file,
                    formatting: {
                        lineSeparator,
                        prefix: '  ',
                        header: `/**${lineSeparator}`,
                        footer: `${lineSeparator} */${lineSeparator}${lineSeparator}`,
                    },
                }) + importStatement
            );
        },
    });

  // Support current sass format tokens to their CSS var versions
    StyleDictionary.registerFormat({
        name: 'support-scss/variables',
        formatter: ({ dictionary, file }) => {
      // Make a list of variables mapped to other variables to jam in
            const varMap = dictionary.allTokens
                .map((item) => `$${item.name}: var(--${item.name});`)
                .join('\n');

            return fileHeader({ file, commentStyle: 'short' }) + varMap;
        },
    });
    StyleDictionary.registerFormat({
        name: 'css/typography',
        formatter(dictionary, config, file) {
            const filteredImports = file.options.import;
            let concatString = '';
            filteredImports.forEach((string) => {
                concatString += `@import '${string}';\n`;
            });

            concatString += `:root{${dictionary.allTokens
                .map((token) => {
                    const prefix = config.prefix;
                    const restOfName = token.name.replace(`${prefix}-`, '');

          // Helper function to pass original token values in to get typography parts we need
                    const cssVariable = (varValue) => {
                        const kebabFormat = _.kebabCase(prefix + varValue);
                        return `var(--${kebabFormat});`;
                    };

                    return `--${[prefix, token.type, restOfName, 'font-family'].join(
                        '-'
                    )}: ${cssVariable(token.original.value.fontFamily)}
      --${[prefix, token.type, restOfName, 'font-size'].join(
        '-'
    )}: ${cssVariable(token.original.value.fontSize)}
      --${[prefix, token.type, restOfName, 'font-weight'].join(
        '-'
    )}: ${cssVariable(token.original.value.fontWeight)}
      --${[prefix, token.type, restOfName, 'line-height'].join(
        '-'
    )}: ${cssVariable(token.original.value.lineHeight)}
      --${[prefix, token.type, restOfName, 'text-decoration'].join(
        '-'
    )}: ${cssVariable(token.original.value.textDecoration)}
      --${[prefix, token.type, restOfName, 'text-transform'].join(
        '-'
    )}: ${cssVariable(token.original.value.textCase)}`;
                })
                .join('\n')}}`;
            return concatString;
        },
    });

    StyleDictionary.registerFormat({
        name: 'react-native/typescript-declarations',
        formatter({ dictionary, file }) {
            return `${fileHeader({ file })}
import type { TextStyle, ViewStyle } from 'react-native';
export interface RootObject {
${parseTypes(reactNativeFormatter(dictionary))}
}
declare const root: RootObject;
export default root;`;
        },
    });

    StyleDictionary.registerFormat({
        name: 'react-native/object',
        formatter({ dictionary, file }) {
            return `${fileHeader({ file })}
module.exports = ${util.inspect(
        reactNativeFormatter(dictionary),
        false,
        null,
        false
    )}`;
        },
    });
};
