import {css} from 'lit';

 const starbucks = css`
@font-face {
	font-family: 'Inter';
	font-style: normal;
	font-weight: 400;
	src: url('../../../assets/fonts/Inter-Regular.woff2') format('woff2'),
			 url('../../../assets/fonts/Inter-Regular.woff') format('woff');
	font-display: fallback;
}

@font-face {
	font-family: 'Inter';
	font-style: medium;
	font-weight: 500;
	src: url('../../../assets/fonts/Inter-Medium.woff2') format('woff2'),
			 url('../../../assets/fonts/Inter-Medium.woff') format('woff');
	font-display: fallback;
}

@font-face {
	font-family: 'Inter';
	font-style: medium;
	font-weight: 600;
	src: url('../../../assets/fonts/Inter-SemiBold.woff2') format('woff2'),
			 url('../../../assets/fonts/Inter-SemiBold.woff') format('woff');
	font-display: fallback;
}

@font-face {
	font-family: 'Inter';
	font-style: normal;
	font-weight: 700;
	src: url('../../../assets/fonts/Inter-Bold.woff2') format('woff2'),
			 url('../../../assets/fonts/Inter-Bold.woff') format('woff');
	font-display: fallback;
}
:root {
  --cre8-desktop-menu-padding-vertical-padding: 1rem;
  --cre8-desktop-menu-padding-horizontal-padding: 0.5rem;
  --cre8-color-header-bg-default: #ffffff;
  --cre8-color-header-inverse-bg-default: #007bff;
  --cre8-color-header-menu-bg-default: #ffffff;
  --cre8-color-header-menu-inverse-bg-default: #007bff;
  --cre8-color-header-menu-bg-hover: #f9f9f9;
  --cre8-color-header-menu-inverse-bg-hover: #00754A;
  --cre8-color-header-menu-bg-focus: #f9f9f9;
  --cre8-color-header-menu-inverse-bg-focus: #00754A;
  --cre8-color-header-menu-bg-active: #edebe9;
  --cre8-color-header-menu-inverse-bg-active: #006241;
  --cre8-color-header-menu-bg-pressed: #edebe9;
  --cre8-color-header-menu-inverse-bg-pressed: #006241;
  --cre8-color-header-menu-bg-selected: #f9f9f9;
  --cre8-color-header-menu-inverse-bg-selected: #00754A;
  --cre8-color-header-menu-content-default: #007bff;
  --cre8-color-header-menu-inverse-content-default: #ffffff;
  --cre8-color-header-menu-content-hover: #00754A;
  --cre8-color-header-menu-inverse-content-hover: #ffffff;
  --cre8-color-header-menu-content-focus: #007bff;
  --cre8-color-header-menu-inverse-content-focus: #ffffff;
  --cre8-color-header-menu-content-active: #006241;
  --cre8-color-header-menu-inverse-content-active: #ffffff;
  --cre8-color-header-menu-content-pressed: #006241;
  --cre8-color-header-menu-inverse-content-pressed: #ffffff;
  --cre8-color-header-menu-content-selected: #00754A;
  --cre8-color-header-menu-inverse-content-selected: #ffffff;
  --cre8-color-header-menu-border-default: rgba(45, 45, 45, 0.0);
  --cre8-color-header-menu-inverse-border-default: rgba(45, 45, 45, 0.0);
  --cre8-color-header-menu-border-hover: rgba(45, 45, 45, 0.0);
  --cre8-color-header-menu-inverse-border-hover: #ffffff;
  --cre8-color-header-menu-border-focus: #00754A;
  --cre8-color-header-menu-inverse-border-focus: #ffffff;
  --cre8-color-header-menu-border-active: #007bff;
  --cre8-color-header-menu-inverse-border-active: #ffffff;
  --cre8-color-header-menu-border-pressed: #007bff;
  --cre8-color-header-menu-inverse-border-pressed: #ffffff;
  --cre8-color-header-menu-border-selected: #00754A;
  --cre8-color-header-menu-inverse-border-selected: #f9f9f9;
  --cre8-color-header-submenu-bg-default: #ffffff;
  --cre8-color-header-submenu-inverse-bg-default: #007bff;
  --cre8-color-header-submenu-bg-hover: #f9f9f9;
  --cre8-color-header-submenu-inverse-bg-hover: #00754A;
  --cre8-color-header-submenu-bg-focus: #ffffff;
  --cre8-color-header-submenu-inverse-bg-focus: #007bff;
  --cre8-color-header-submenu-bg-active: #edebe9;
  --cre8-color-header-submenu-inverse-bg-active: #006241;
  --cre8-color-header-submenu-bg-pressed: #edebe9;
  --cre8-color-header-submenu-inverse-bg-pressed: #006241;
  --cre8-color-header-submenu-bg-selected: #f9f9f9;
  --cre8-color-header-submenu-inverse-bg-selected: #00754A;
  --cre8-color-header-submenu-content-default: #007bff;
  --cre8-color-header-submenu-inverse-content-default: #ffffff;
  --cre8-color-header-submenu-content-hover: #00754A;
  --cre8-color-header-submenu-inverse-content-hover: #ffffff;
  --cre8-color-header-submenu-content-focus: #00754A;
  --cre8-color-header-submenu-inverse-content-focus: #ffffff;
  --cre8-color-header-submenu-content-active: #006241;
  --cre8-color-header-submenu-inverse-content-active: #ffffff;
  --cre8-color-header-submenu-content-pressed: #006241;
  --cre8-color-header-submenu-inverse-content-pressed: #ffffff;
  --cre8-color-header-submenu-content-selected: #007bff;
  --cre8-color-header-submenu-inverse-content-selected: #ffffff;
  --cre8-color-header-submenu-border-default: #ffffff;
  --cre8-color-header-submenu-inverse-border-default: #007bff;
  --cre8-color-header-submenu-border-hover: #f9f9f9;
  --cre8-color-header-submenu-inverse-border-hover: #00754A;
  --cre8-color-header-submenu-border-focus: #007bff;
  --cre8-color-header-submenu-inverse-border-focus: #ffffff;
  --cre8-color-header-submenu-border-active: #edebe9;
  --cre8-color-header-submenu-inverse-border-active: #006241;
  --cre8-color-header-submenu-border-pressed: #edebe9;
  --cre8-color-header-submenu-inverse-border-pressed: #006241;
  --cre8-color-header-submenu-border-selected: #00754A;
  --cre8-color-header-submenu-inverse-border-selected: #f9f9f9;
  --cre8-color-header-bg-secondary: #007bff;
  --cre8-color-header-inverse-bg-secondary: #ffffff;
  --cre8-color-header-bg-tertiary: #007bff;
  --cre8-color-header-inverse-bg-tertiary: #ffffff;
  --cre8-color-footer-bg-default: #007bff;
  --cre8-color-footer-bg-secondary: #f9f9f9;
  --cre8-color-footer-content-secondary: #ffffff;
  --cre8-color-footer-link-hover: #006241;
  --cre8-color-footer-link-default: #006241;
  --cre8-spacing-0: 0rem;
  --cre8-spacing-2: 0.125rem;
  --cre8-spacing-4: 0.25rem;
  --cre8-spacing-6: 0.375rem;
  --cre8-spacing-8: 0.5rem;
  --cre8-spacing-12: 0.75rem;
  --cre8-spacing-14: 0.875rem;
  --cre8-spacing-16: 1rem;
  --cre8-spacing-18: 1.125rem;
  --cre8-spacing-24: 1.5rem;
  --cre8-spacing-32: 2rem;
  --cre8-spacing-40: 2.5rem;
  --cre8-spacing-48: 3rem;
  --cre8-spacing-64: 4rem;
  --cre8-spacing-80: 5rem;
  --cre8-spacing-96: 6rem;
  --cre8-spacing-120: 7.5rem;
  --cre8-spacing-160: 10rem;
  --cre8-button-padding-vertical-small: 0.5rem;
  --cre8-button-padding-vertical-large: 1rem;
  --cre8-button-padding-vertical-medium: 0.75rem;
  --cre8-button-padding-vertical-icon-only: 0.5rem;
  --cre8-button-padding-vertical-small-icon-only: 0.5rem;
  --cre8-button-padding-vertical-medium-icon-only: 1rem;
  --cre8-button-padding-vertical-large-icon-only: 1rem;
  --cre8-button-padding-horizontal-small: 1rem;
  --cre8-button-padding-horizontal-medium: 1.5rem;
  --cre8-button-padding-horizontal-large: 2rem;
  --cre8-button-padding-horizontal-icon-only: 0.5rem;
  --cre8-button-padding-horizontal-small-icon-only: 0.5rem;
  --cre8-button-padding-horizontal-medium-icon-only: 1rem;
  --cre8-button-padding-horizontal-large-icon-only: 1rem;
  --cre8-color-button-primary-bg: #007bff;
  --cre8-color-button-primary-inverse-bg: #f9f9f9;
  --cre8-color-button-primary-bg-hover: #00754A;
  --cre8-color-button-primary-inverse-bg-hover: #f2f0eb;
  --cre8-color-button-primary-bg-active: #006241;
  --cre8-color-button-primary-inverse-bg-active: #edebe9;
  --cre8-color-button-primary-bg-disabled: #eaeaea;
  --cre8-color-button-primary-inverse-bg-disabled: #ababab;
  --cre8-color-button-primary-content: #ffffff;
  --cre8-color-button-primary-inverse-content: #00754A;
  --cre8-color-button-primary-content-hover: #ffffff;
  --cre8-color-button-primary-inverse-content-hover: #00754A;
  --cre8-color-button-primary-content-active: #ffffff;
  --cre8-color-button-primary-inverse-content-active: #00754A;
  --cre8-color-button-primary-content-disabled: #949494;
  --cre8-color-button-primary-inverse-content-disabled: #6c6c6c;
  --cre8-color-button-primary-border: #007bff;
  --cre8-color-button-primary-inverse-border: #f9f9f9;
  --cre8-color-button-primary-border-hover: #00754A;
  --cre8-color-button-primary-inverse-border-hover: #f2f0eb;
  --cre8-color-button-primary-border-active: #006241;
  --cre8-color-button-primary-inverse-border-active: #edebe9;
  --cre8-color-button-primary-border-disabled: #eaeaea;
  --cre8-color-button-primary-inverse-border-disabled: #ababab;
  --cre8-color-button-primary-outline: #006241;
  --cre8-color-button-primary-inverse-outline: #f9f9f9;
  --cre8-color-button-primary-danger-bg: #c82014;
  --cre8-color-button-primary-danger-inverse-bg: #fbbc05;
  --cre8-color-button-primary-danger-bg-hover: #a31810;
  --cre8-color-button-primary-danger-inverse-bg-hover: #fbbc05;
  --cre8-color-button-primary-danger-bg-active: #7a0000;
  --cre8-color-button-primary-danger-inverse-bg-active: #fbbc05;
  --cre8-color-button-primary-danger-bg-disabled: #eaeaea;
  --cre8-color-button-primary-danger-inverse-bg-disabled: #ababab;
  --cre8-color-button-primary-danger-content: #ffffff;
  --cre8-color-button-primary-danger-inverse-content: #2d2d2d;
  --cre8-color-button-primary-danger-content-hover: #ffffff;
  --cre8-color-button-primary-danger-inverse-content-hover: #2d2d2d;
  --cre8-color-button-primary-danger-content-active: #ffffff;
  --cre8-color-button-primary-danger-inverse-content-active: #2d2d2d;
  --cre8-color-button-primary-danger-content-disabled: #949494;
  --cre8-color-button-primary-danger-inverse-content-disabled: #6c6c6c;
  --cre8-color-button-primary-danger-border: #c82014;
  --cre8-color-button-primary-danger-inverse-border: #fbbc05;
  --cre8-color-button-primary-danger-border-hover: #a31810;
  --cre8-color-button-primary-danger-inverse-border-hover: #fbbc05;
  --cre8-color-button-primary-danger-border-active: #7a0000;
  --cre8-color-button-primary-danger-inverse-border-active: #fbbc05;
  --cre8-color-button-primary-danger-border-disabled: #eaeaea;
  --cre8-color-button-primary-danger-inverse-border-disabled: #ababab;
  --cre8-color-button-primary-danger-outline: #006241;
  --cre8-color-button-primary-danger-inverse-outline: #f9f9f9;
  --cre8-color-button-secondary-neutral-bg: rgba(45, 45, 45, 0.0);
  --cre8-color-button-secondary-neutral-inverse-bg: rgba(45, 45, 45, 0.0);
  --cre8-color-button-secondary-neutral-content: #000000;
  --cre8-color-button-secondary-neutral-inverse-content: #ffffff;
  --cre8-color-button-secondary-neutral-border: #edebe9;
  --cre8-color-button-secondary-neutral-inverse-border: #ffffff;
  --cre8-color-button-secondary-neutral-bg-hover: rgba(45, 45, 45, 0.10);
  --cre8-color-button-secondary-neutral-inverse-bg-hover: rgba(45, 45, 45, 0.20);
  --cre8-color-button-secondary-neutral-content-hover: #000000;
  --cre8-color-button-secondary-neutral-inverse-content-hover: #ffffff;
  --cre8-color-button-secondary-neutral-border-hover: #edebe9;
  --cre8-color-button-secondary-neutral-inverse-border-hover: #ffffff;
  --cre8-color-button-secondary-neutral-border-active: #edebe9;
  --cre8-color-button-secondary-neutral-inverse-border-active: #ffffff;
  --cre8-color-button-secondary-neutral-bg-active: rgba(45, 45, 45, 0.20);
  --cre8-color-button-secondary-neutral-inverse-bg-active: rgba(45, 45, 45, 0.50);
  --cre8-color-button-secondary-neutral-content-active: #000000;
  --cre8-color-button-secondary-neutral-inverse-content-active: #ffffff;
  --cre8-color-button-secondary-neutral-bg-disabled: #eaeaea;
  --cre8-color-button-secondary-neutral-inverse-bg-disabled: #ababab;
  --cre8-color-button-secondary-neutral-border-disabled: #eaeaea;
  --cre8-color-button-secondary-neutral-inverse-border-disabled: #ababab;
  --cre8-color-button-secondary-neutral-content-disabled: #949494;
  --cre8-color-button-secondary-neutral-inverse-content-disabled: #6c6c6c;
  --cre8-color-button-secondary-neutral-outline: #007bff;
  --cre8-color-button-secondary-neutral-inverse-outline: #f9f9f9;
  --cre8-color-button-secondary-bg: rgba(45, 45, 45, 0.0);
  --cre8-color-button-secondary-inverse-bg: rgba(45, 45, 45, 0.0);
  --cre8-color-button-secondary-bg-hover: #ffffff;
  --cre8-color-button-secondary-inverse-bg-hover: rgba(45, 45, 45, 0.0);
  --cre8-color-button-secondary-bg-active: #d4e9e2;
  --cre8-color-button-secondary-inverse-bg-active: #006241;
  --cre8-color-button-secondary-bg-disabled: #eaeaea;
  --cre8-color-button-secondary-inverse-bg-disabled: rgba(45, 45, 45, 0.0);
  --cre8-color-button-secondary-content: #007bff;
  --cre8-color-button-secondary-inverse-content: #f9f9f9;
  --cre8-color-button-secondary-content-hover: #00754A;
  --cre8-color-button-secondary-inverse-content-hover: #f2f0eb;
  --cre8-color-button-secondary-content-active: #006241;
  --cre8-color-button-secondary-inverse-content-active: #edebe9;
  --cre8-color-button-secondary-content-disabled: #949494;
  --cre8-color-button-secondary-inverse-content-disabled: #ababab;
  --cre8-color-button-secondary-border: #007bff;
  --cre8-color-button-secondary-inverse-border: #f9f9f9;
  --cre8-color-button-secondary-border-hover: #00754A;
  --cre8-color-button-secondary-inverse-border-hover: #f2f0eb;
  --cre8-color-button-secondary-border-active: #006241;
  --cre8-color-button-secondary-inverse-border-active: #edebe9;
  --cre8-color-button-secondary-border-disabled: #ababab;
  --cre8-color-button-secondary-inverse-border-disabled: #ababab;
  --cre8-color-button-secondary-outline: #006241;
  --cre8-color-button-secondary-inverse-outline: #f2f0eb;
  --cre8-color-button-secondary-danger-bg: rgba(45, 45, 45, 0.0);
  --cre8-color-button-secondary-danger-inverse-bg: rgba(45, 45, 45, 0.0);
  --cre8-color-button-secondary-danger-bg-hover: #a31810;
  --cre8-color-button-secondary-danger-inverse-bg-hover: #fbbc05;
  --cre8-color-button-secondary-danger-bg-active: #7a0000;
  --cre8-color-button-secondary-danger-inverse-bg-active: #fbbc05;
  --cre8-color-button-secondary-danger-bg-disabled: #eaeaea;
  --cre8-color-button-secondary-danger-inverse-bg-disabled: #ababab;
  --cre8-color-button-secondary-danger-content: #c82014;
  --cre8-color-button-secondary-danger-inverse-content: #fbbc05;
  --cre8-color-button-secondary-danger-content-hover: #ffffff;
  --cre8-color-button-secondary-danger-inverse-content-hover: #2d2d2d;
  --cre8-color-button-secondary-danger-content-active: #ffffff;
  --cre8-color-button-secondary-danger-inverse-content-active: #2d2d2d;
  --cre8-color-button-secondary-danger-content-disabled: #949494;
  --cre8-color-button-secondary-danger-inverse-content-disabled: #6c6c6c;
  --cre8-color-button-secondary-danger-border: #c82014;
  --cre8-color-button-secondary-danger-inverse-border: #fbbc05;
  --cre8-color-button-secondary-danger-border-hover: #a31810;
  --cre8-color-button-secondary-danger-inverse-border-hover: #fbbc05;
  --cre8-color-button-secondary-danger-border-active: #7a0000;
  --cre8-color-button-secondary-danger-inverse-border-active: #fbbc05;
  --cre8-color-button-secondary-danger-border-disabled: #eaeaea;
  --cre8-color-button-secondary-danger-inverse-border-disabled: #ababab;
  --cre8-color-button-secondary-danger-outline: #006241;
  --cre8-color-button-secondary-danger-inverse-outline: #f9f9f9;
  --cre8-color-button-tertiary-bg: rgba(45, 45, 45, 0.0);
  --cre8-color-button-tertiary-inverse-bg: rgba(45, 45, 45, 0.0);
  --cre8-color-button-tertiary-bg-hover: rgba(45, 45, 45, 0.0);
  --cre8-color-button-tertiary-inverse-bg-hover: rgba(45, 45, 45, 0.0);
  --cre8-color-button-tertiary-bg-active: rgba(45, 45, 45, 0.0);
  --cre8-color-button-tertiary-inverse-bg-active: #2b5148;
  --cre8-color-button-tertiary-bg-disabled: rgba(45, 45, 45, 0.0);
  --cre8-color-button-tertiary-inverse-bg-disabled: rgba(45, 45, 45, 0.0);
  --cre8-color-button-tertiary-content: #007bff;
  --cre8-color-button-tertiary-inverse-content: #f9f9f9;
  --cre8-color-button-tertiary-content-hover: #00754A;
  --cre8-color-button-tertiary-inverse-content-hover: #f2f0eb;
  --cre8-color-button-tertiary-content-active: #006241;
  --cre8-color-button-tertiary-inverse-content-active: #edebe9;
  --cre8-color-button-tertiary-content-disabled: #949494;
  --cre8-color-button-tertiary-inverse-content-disabled: #ababab;
  --cre8-color-button-tertiary-border: rgba(45, 45, 45, 0.0);
  --cre8-color-button-tertiary-inverse-border: rgba(45, 45, 45, 0.0);
  --cre8-color-button-tertiary-border-hover: #00754A;
  --cre8-color-button-tertiary-inverse-border-hover: #f2f0eb;
  --cre8-color-button-tertiary-border-active: #006241;
  --cre8-color-button-tertiary-inverse-border-active: #edebe9;
  --cre8-color-button-tertiary-border-disabled: rgba(45, 45, 45, 0.0);
  --cre8-color-button-tertiary-inverse-border-disabled: rgba(45, 45, 45, 0.0);
  --cre8-color-button-tertiary-outline: #006241;
  --cre8-color-button-tertiary-inverse-outline: #f2f0eb;
  --cre8-color-button-tertiary-neutral-bg: rgba(45, 45, 45, 0.0);
  --cre8-color-button-tertiary-neutral-inverse-bg: rgba(45, 45, 45, 0.0);
  --cre8-color-button-tertiary-neutral-content: #000000;
  --cre8-font-families-inter: 'Inter', Open-Sans, sans-serif;
  --cre8-font-weights-regular: 400;
  --cre8-font-weights-bold: 600;
  --cre8-font-weights-light: 200;
  --cre8-border-radius-default: 4px;
  --cre8-border-radius-small: 2px;
  --cre8-border-radius-large: 8px;
  --cre8-shadow-default: 0 2px 8px rgba(0,0,0,0.08);
  --cre8-shadow-medium: 0 4px 16px rgba(0,0,0,0.12);
  --cre8-shadow-large: 0 8px 32px rgba(0,0,0,0.16);
}
`;
export default starbucks;