/**
 * Do not edit directly
 * Generated on Sun, 27 Oct 2024 04:05:11 GMT
 */


module.exports = {
  'leaf-desktop-menu-padding-vertical-padding': 16,
  'leaf-desktop-menu-padding-horizontal-padding': 8,
  'leaf-color-header-bg-default': '#ffffff',
  'leaf-color-header-inverse-bg-default': '#0170bc',
  'leaf-color-header-bg-secondary': '#0170bc',
  'leaf-color-header-inverse-bg-secondary': '#ffffff',
  'leaf-color-header-bg-tertiary': '#f9fafd',
  'leaf-color-header-inverse-bg-tertiary': '#0170bc',
  'leaf-color-header-menu-bg-default': '#ffffff',
  'leaf-color-header-menu-inverse-bg-default': '#0170bc',
  'leaf-color-header-menu-bg-selected': '#ffffff',
  'leaf-color-header-menu-inverse-bg-selected': '#0170bc',
  'leaf-color-header-menu-bg-hover': '#ffffff',
  'leaf-color-header-menu-inverse-bg-hover': '#014371',
  'leaf-color-header-menu-bg-pressed': '#e5f0f8',
  'leaf-color-header-menu-inverse-bg-pressed': '#014371',
  'leaf-color-header-menu-bg-active': '#e5f0f8',
  'leaf-color-header-menu-inverse-bg-active': '#014371',
  'leaf-color-header-menu-bg-focus': '#ffffff',
  'leaf-color-header-menu-inverse-bg-focus': '#014371',
  'leaf-color-header-menu-content-default': '#0170bc',
  'leaf-color-header-menu-inverse-content-default': '#ffffff',
  'leaf-color-header-menu-content-hover': '#ffffff',
  'leaf-color-header-menu-inverse-content-hover': '#ffffff',
  'leaf-color-header-menu-content-pressed': '#ffffff',
  'leaf-color-header-menu-inverse-content-pressed': '#ffffff',
  'leaf-color-header-menu-content-active': '#ffffff',
  'leaf-color-header-menu-inverse-content-active': '#ffffff',
  'leaf-color-header-menu-content-selected': '#ffffff',
  'leaf-color-header-menu-inverse-content-selected': '#ffffff',
  'leaf-color-header-menu-content-focus': '#ffffff',
  'leaf-color-header-menu-inverse-content-focus': '#ffffff',
  'leaf-color-header-menu-border-default': '#0170bc',
  'leaf-color-header-menu-inverse-border-default': '#0170bc',
  'leaf-color-header-menu-border-pressed': '#014371',
  'leaf-color-header-menu-inverse-border-pressed': '#f9fafd',
  'leaf-color-header-menu-border-active': '#014371',
  'leaf-color-header-menu-inverse-border-active': '#f9fafd',
  'leaf-color-header-menu-border-selected': '#014371',
  'leaf-color-header-menu-inverse-border-selected': '#e5f0f8',
  'leaf-color-header-menu-border-focus': '#014371',
  'leaf-color-header-menu-inverse-border-focus': '#f9fafd',
  'leaf-color-header-submenu-bg-default': '#ffffff',
  'leaf-color-header-submenu-inverse-bg-default': '#ffffff',
  'leaf-color-header-submenu-bg-hover': '#f2f8fb',
  'leaf-color-header-submenu-inverse-bg-hover': '#f2f8fb',
  'leaf-color-header-submenu-bg-pressed': '#f2f8fb',
  'leaf-color-header-submenu-inverse-bg-pressed': '#f2f8fb',
  'leaf-color-header-submenu-bg-active': '#f2f8fb',
  'leaf-color-header-submenu-inverse-bg-active': '#f2f8fb',
  'leaf-color-header-submenu-bg-focus': '#f2f8fb',
  'leaf-color-header-submenu-inverse-bg-focus': '#f2f8fb',
  'leaf-color-header-submenu-bg-selected': '#f2f8fb',
  'leaf-color-header-submenu-inverse-bg-selected': '#f2f8fb',
  'leaf-color-header-submenu-content-default': '#014371',
  'leaf-color-header-submenu-inverse-content-default': '#014371',
  'leaf-color-header-submenu-content-hover': '#014371',
  'leaf-color-header-submenu-inverse-content-hover': '#014371',
  'leaf-color-header-submenu-content-pressed': '#014371',
  'leaf-color-header-submenu-inverse-content-pressed': '#014371',
  'leaf-color-header-submenu-content-active': '#014371',
  'leaf-color-header-submenu-inverse-content-active': '#014371',
  'leaf-color-header-submenu-content-focus': '#014371',
  'leaf-color-header-submenu-inverse-content-focus': '#014371',
  'leaf-color-header-submenu-content-selected': '#014371',
  'leaf-color-header-submenu-inverse-content-selected': '#014371',
  'leaf-color-header-submenu-border-default': '#014371',
  'leaf-color-header-submenu-inverse-border-default': '#014371',
  'leaf-color-header-submenu-border-hover': '#014371',
  'leaf-color-header-submenu-inverse-border-hover': '#014371',
  'leaf-color-header-submenu-border-focus': '#014371',
  'leaf-color-header-submenu-inverse-border-focus': '#014371',
  'leaf-color-header-submenu-border-active': '#014371',
  'leaf-color-header-submenu-inverse-border-active': '#014371',
  'leaf-color-header-submenu-border-pressed': '#014371',
  'leaf-color-header-submenu-inverse-border-pressed': '#014371',
  'leaf-color-header-submenu-border-selected': '#014371',
  'leaf-color-header-submenu-inverse-border-selected': '#014371',
  'leaf-spacing-0': 0,
  'leaf-spacing-2': 2,
  'leaf-spacing-4': 4,
  'leaf-spacing-6': 6,
  'leaf-spacing-8': 8,
  'leaf-spacing-12': 12,
  'leaf-spacing-14': 14,
  'leaf-spacing-16': 16,
  'leaf-spacing-18': 18,
  'leaf-spacing-24': 24,
  'leaf-spacing-32': 32,
  'leaf-spacing-40': 40,
  'leaf-spacing-48': 48,
  'leaf-spacing-64': 64,
  'leaf-spacing-80': 80,
  'leaf-spacing-96': 96,
  'leaf-spacing-120': 120,
  'leaf-spacing-160': 160,
  'leaf-color-footer-bg-default': '#f9fafd',
  'leaf-color-footer-bg-secondary': '#282c2f',
  'leaf-color-footer-content-default': '#282c2f',
  'leaf-color-footer-content-secondary': '#ffffff',
  'leaf-color-footer-link-default': '#0170bc',
  'leaf-color-footer-link-hover': '#014371',
  'leaf-color-button-primary-danger-bg': '#7f848b',
  'leaf-color-button-primary-danger-inverse-bg': '#ffffff',
  'leaf-color-button-primary-danger-bg-hover': '#5a636b',
  'leaf-color-button-primary-danger-inverse-bg-hover': '#f2f4f9',
  'leaf-color-button-primary-danger-bg-active': '#282c2f',
  'leaf-color-button-primary-danger-inverse-bg-active': '#eef1f5',
  'leaf-color-button-primary-danger-bg-disabled': '#cccccc',
  'leaf-color-button-primary-danger-inverse-bg-disabled': '#cccccc',
  'leaf-color-button-primary-danger-content': '#ffffff',
  'leaf-color-button-primary-danger-inverse-content': '#000000',
  'leaf-color-button-primary-danger-content-hover': '#f9fafd',
  'leaf-color-button-primary-danger-inverse-content-hover': '#000000',
  'leaf-color-button-primary-danger-content-active': '#f9fafd',
  'leaf-color-button-primary-danger-inverse-content-active': '#000000',
  'leaf-color-button-primary-danger-content-disabled': '#f9fafd',
  'leaf-color-button-primary-danger-inverse-content-disabled': '#000000',
  'leaf-color-button-primary-danger-border': '#7f848b',
  'leaf-color-button-primary-danger-inverse-border': '#ffffff',
  'leaf-color-button-primary-danger-border-hover': '#5a636b',
  'leaf-color-button-primary-danger-inverse-border-hover': '#f2f4f9',
  'leaf-color-button-primary-danger-border-active': '#282c2f',
  'leaf-color-button-primary-danger-inverse-border-active': '#eef1f5',
  'leaf-color-button-primary-danger-border-disabled': '#cccccc',
  'leaf-color-button-primary-danger-inverse-border-disabled': '#cccccc',
  'leaf-color-button-primary-danger-outline': '#282c2f',
  'leaf-color-button-primary-danger-inverse-outline': '#ffffff',
  'leaf-color-button-primary-bg': '#0170bc',
  'leaf-color-button-primary-inverse-bg': '#0170bc',
  'leaf-color-button-primary-bg-hover': '#014371',
  'leaf-color-button-primary-inverse-bg-hover': '#014371',
  'leaf-color-button-primary-bg-active': '#014371',
  'leaf-color-button-primary-inverse-bg-active': '#014371',
  'leaf-color-button-primary-bg-disabled': '#72aad0',
  'leaf-color-button-primary-inverse-bg-disabled': '#72aad0',
  'leaf-color-button-primary-border': '#0170bc',
  'leaf-color-button-primary-inverse-border': '#0170bc',
  'leaf-color-button-primary-border-hover': '#014371',
  'leaf-color-button-primary-inverse-border-hover': '#014371',
  'leaf-color-button-primary-border-active': '#014371',
  'leaf-color-button-primary-inverse-border-active': '#014371',
  'leaf-color-button-primary-border-disabled': '#72aad0',
  'leaf-color-button-primary-inverse-border-disabled': '#72aad0',
  'leaf-color-button-primary-content': '#ffffff',
  'leaf-color-button-primary-inverse-content': '#ffffff',
  'leaf-color-button-primary-content-hover': '#ffffff',
  'leaf-color-button-primary-inverse-content-hover': '#ffffff',
  'leaf-color-button-primary-content-active': '#ffffff',
  'leaf-color-button-primary-inverse-content-active': '#ffffff',
  'leaf-color-button-primary-content-disabled': '#ffffff',
  'leaf-color-button-primary-inverse-content-disabled': '#ffffff',
  'leaf-color-button-primary-outline': '#282c2f',
  'leaf-color-button-primary-inverse-outline': '#282c2f',
  'leaf-color-button-secondary-neutral-bg': 'rgba( #282c2f,0.0)',
  'leaf-color-button-secondary-neutral-inverse-bg': 'rgba( #282c2f,0.0)',
  'leaf-color-button-secondary-neutral-content': '#5a636b',
  'leaf-color-button-secondary-neutral-inverse-content': '#ffffff',
  'leaf-color-button-secondary-neutral-border': '#5a636b',
  'leaf-color-button-secondary-neutral-inverse-border': '#ffffff',
  'leaf-color-button-secondary-neutral-bg-hover': 'rgba( #282c2f,0.25)',
  'leaf-color-button-secondary-neutral-inverse-bg-hover': 'rgba( #282c2f,0.25)',
  'leaf-color-button-secondary-neutral-content-hover': '#282c2f',
  'leaf-color-button-secondary-neutral-inverse-content-hover': '#ffffff',
  'leaf-color-button-secondary-neutral-border-hover': '#282c2f',
  'leaf-color-button-secondary-neutral-inverse-border-hover': '#ffffff',
  'leaf-color-button-secondary-neutral-border-active': '#282c2f',
  'leaf-color-button-secondary-neutral-inverse-border-active': '#ffffff',
  'leaf-color-button-secondary-neutral-bg-active': 'rgba( #282c2f,0.25)',
  'leaf-color-button-secondary-neutral-inverse-bg-active': '#cccccc',
  'leaf-color-button-secondary-neutral-content-active': '#282c2f',
  'leaf-color-button-secondary-neutral-inverse-content-active': '#ffffff',
  'leaf-color-button-secondary-neutral-bg-disabled': '#f2f4f9',
  'leaf-color-button-secondary-neutral-inverse-bg-disabled': '#c4c9cf',
  'leaf-color-button-secondary-neutral-border-disabled': '#f2f4f9',
  'leaf-color-button-secondary-neutral-inverse-border-disabled': '#c4c9cf',
  'leaf-color-button-secondary-neutral-content-disabled': '#cccccc',
  'leaf-color-button-secondary-neutral-inverse-content-disabled': '#a6abb2',
  'leaf-color-button-secondary-neutral-outline': '#282c2f',
  'leaf-color-button-secondary-neutral-inverse-outline': '#ffffff',
  'leaf-color-button-secondary-danger-bg': 'rgba( #282c2f,0.0)',
  'leaf-color-button-secondary-danger-inverse-bg': 'rgba( #282c2f,0.0)',
  'leaf-color-button-secondary-danger-bg-hover': '#5a636b',
  'leaf-color-button-secondary-danger-inverse-bg-hover': '#f2f4f9',
  'leaf-color-button-secondary-danger-bg-active': '#282c2f',
  'leaf-color-button-secondary-danger-inverse-bg-active': '#eef1f5',
  'leaf-color-button-secondary-danger-bg-disabled': '#cccccc',
  'leaf-color-button-secondary-danger-inverse-bg-disabled': '#cccccc',
  'leaf-color-button-secondary-danger-content': '#ffffff',
  'leaf-color-button-secondary-danger-inverse-content': '#000000',
  'leaf-color-button-secondary-danger-content-hover': '#f9fafd',
  'leaf-color-button-secondary-danger-inverse-content-hover': '#000000',
  'leaf-color-button-secondary-danger-content-active': '#f9fafd',
  'leaf-color-button-secondary-danger-inverse-content-active': '#000000',
  'leaf-color-button-secondary-danger-content-disabled': '#f9fafd',
  'leaf-color-button-secondary-danger-inverse-content-disabled': '#000000',
  'leaf-color-button-secondary-danger-border': '#5a636b',
  'leaf-color-button-secondary-danger-inverse-border': '#ffffff',
  'leaf-color-button-secondary-danger-border-hover': '#5a636b',
  'leaf-color-button-secondary-danger-inverse-border-hover': '#f2f4f9',
  'leaf-color-button-secondary-danger-border-active': '#282c2f',
  'leaf-color-button-secondary-danger-inverse-border-active': '#eef1f5',
  'leaf-color-button-secondary-danger-border-disabled': '#cccccc',
  'leaf-color-button-secondary-danger-inverse-border-disabled': '#cccccc',
  'leaf-color-button-secondary-danger-outline': '#282c2f',
  'leaf-color-button-secondary-danger-inverse-outline': '#ffffff',
  'leaf-color-button-secondary-bg': 'rgba( #282c2f,0.0)',
  'leaf-color-button-secondary-bg-hover': '#f2f8fb',
  'leaf-color-button-secondary-bg-active': '#f2f8fb',
  'leaf-color-button-secondary-bg-disabled': 'rgba( #282c2f,0.0)',
  'leaf-color-button-secondary-border': '#0170bc',
  'leaf-color-button-secondary-border-hover': '#0170bc',
  'leaf-color-button-secondary-border-active': '#0170bc',
  'leaf-color-button-secondary-border-disabled': '#72aad0',
  'leaf-color-button-secondary-content': '#0170bc',
  'leaf-color-button-secondary-content-hover': '#0170bc',
  'leaf-color-button-secondary-content-active': '#0170bc',
  'leaf-color-button-secondary-content-disabled': '#72aad0',
  'leaf-color-button-secondary-outline': '#282c2f',
  'leaf-color-button-tertiary-neutral-bg': 'rgba( #282c2f,0.0)',
  'leaf-color-button-tertiary-neutral-inverse-bg': 'rgba( #282c2f,0.0)',
  'leaf-color-button-tertiary-neutral-content': '#5a636b',
  'leaf-color-button-tertiary-neutral-inverse-content': '#ffffff',
  'leaf-color-button-tertiary-neutral-border': 'rgba( #282c2f,0.0)',
  'leaf-color-button-tertiary-neutral-inverse-border': 'rgba( #282c2f,0.0)',
  'leaf-color-button-tertiary-neutral-bg-hover': 'rgba( #282c2f,0.0)',
  'leaf-color-button-tertiary-neutral-inverse-bg-hover': 'rgba( #282c2f,0.0)',
  'leaf-color-button-tertiary-neutral-content-hover': '#282c2f',
  'leaf-color-button-tertiary-neutral-inverse-content-hover': '#ffffff',
  'leaf-color-button-tertiary-neutral-border-hover': 'rgba( #282c2f,0.0)',
  'leaf-color-button-tertiary-neutral-inverse-border-hover': 'rgba( #282c2f,0.0)',
  'leaf-color-button-tertiary-neutral-border-active': '#282c2f',
  'leaf-color-button-tertiary-neutral-inverse-border-active': '#ffffff',
  'leaf-color-button-tertiary-neutral-bg-active': 'rgba( #282c2f,0.0)',
  'leaf-color-button-tertiary-neutral-inverse-bg-active': 'rgba( #282c2f,0.0)',
  'leaf-color-button-tertiary-neutral-content-active': '#282c2f',
  'leaf-color-button-tertiary-neutral-inverse-content-active': '#ffffff',
  'leaf-color-button-tertiary-neutral-bg-disabled': 'rgba( #282c2f,0.0)',
  'leaf-color-button-tertiary-neutral-inverse-bg-disabled': 'rgba( #282c2f,0.0)',
  'leaf-color-button-tertiary-neutral-border-disabled': 'rgba( #282c2f,0.0)',
  'leaf-color-button-tertiary-neutral-inverse-border-disabled': 'rgba( #282c2f,0.0)',
  'leaf-color-button-tertiary-neutral-content-disabled': '#cccccc',
  'leaf-color-button-tertiary-neutral-inverse-content-disabled': '#a6abb2',
  'leaf-color-button-tertiary-neutral-outline': '#282c2f',
  'leaf-color-button-tertiary-neutral-inverse-outline': '#ffffff',
  'leaf-color-button-tertiary-danger-bg': 'rgba( #282c2f,0.0)',
  'leaf-color-button-tertiary-danger-inverse-bg': 'rgba( #282c2f,0.0)',
  'leaf-color-button-tertiary-danger-bg-hover': '#5a636b',
  'leaf-color-button-tertiary-danger-inverse-bg-hover': '#f2f4f9',
  'leaf-color-button-tertiary-danger-bg-active': '#282c2f',
  'leaf-color-button-tertiary-danger-inverse-bg-active': '#eef1f5',
  'leaf-color-button-tertiary-danger-bg-disabled': '#cccccc',
  'leaf-color-button-tertiary-danger-inverse-bg-disabled': '#cccccc',
  'leaf-color-button-tertiary-danger-content': '#ffffff',
  'leaf-color-button-tertiary-danger-inverse-content': '#000000',
  'leaf-color-button-tertiary-danger-content-hover': '#f9fafd',
  'leaf-color-button-tertiary-danger-inverse-content-hover': '#000000',
  'leaf-color-button-tertiary-danger-content-active': '#f9fafd',
  'leaf-color-button-tertiary-danger-inverse-content-active': '#000000',
  'leaf-color-button-tertiary-danger-content-disabled': '#f9fafd',
  'leaf-color-button-tertiary-danger-inverse-content-disabled': '#000000',
  'leaf-color-button-tertiary-danger-border': 'rgba( #282c2f,0.0)',
  'leaf-color-button-tertiary-danger-inverse-border': 'rgba( #282c2f,0.0)',
  'leaf-color-button-tertiary-danger-border-hover': '#5a636b',
  'leaf-color-button-tertiary-danger-inverse-border-hover': '#f2f4f9',
  'leaf-color-button-tertiary-danger-border-active': '#282c2f',
  'leaf-color-button-tertiary-danger-inverse-border-active': '#eef1f5',
  'leaf-color-button-tertiary-danger-border-disabled': '#cccccc',
  'leaf-color-button-tertiary-danger-inverse-border-disabled': '#cccccc',
  'leaf-color-button-tertiary-danger-outline': '#282c2f',
  'leaf-color-button-tertiary-danger-inverse-outline': '#ffffff',
  'leaf-color-button-tertiary-bg': 'rgba( #282c2f,0.0)',
  'leaf-color-button-tertiary-bg-hover': 'rgba( #282c2f,0.0)',
  'leaf-color-button-tertiary-bg-active': '#f2f8fb',
  'leaf-color-button-tertiary-bg-disabled': 'rgba( #282c2f,0.0)',
  'leaf-color-button-tertiary-border': 'rgba( #282c2f,0.0)',
  'leaf-color-button-tertiary-border-hover': '#0170bc',
  'leaf-color-button-tertiary-border-active': '#0170bc',
  'leaf-color-button-tertiary-border-disabled': 'rgba( #282c2f,0.0)',
  'leaf-color-button-tertiary-content': '#0170bc',
  'leaf-color-button-tertiary-content-hover': '#0170bc',
  'leaf-color-button-tertiary-content-active': '#0170bc',
  'leaf-color-button-tertiary-content-disabled': '#c4c9cf',
  'leaf-color-button-tertiary-outline': '#282c2f',
  'leaf-button-padding-vertical-small': 8,
  'leaf-button-padding-vertical-large': 16,
  'leaf-button-padding-vertical-medium': 12,
  'leaf-button-padding-vertical-icon-only': 8,
  'leaf-button-padding-vertical-small-icon-only': 8,
  'leaf-button-padding-vertical-medium-icon-only': 16,
  'leaf-button-padding-vertical-large-icon-only': 16,
  'leaf-button-padding-horizontal-small': 16,
  'leaf-button-padding-horizontal-medium': 24,
  'leaf-button-padding-horizontal-large': 32,
  'leaf-button-padding-horizontal-icon-only': 8,
  'leaf-button-padding-horizontal-small-icon-only': 8,
  'leaf-button-padding-horizontal-medium-icon-only': 16,
  'leaf-button-padding-horizontal-large-icon-only': 16,
  'leaf-color-bg-default': '#ffffff',
  'leaf-color-bg-default-hover': '#f2f8fb',
  'leaf-color-bg-default-active': '#cce2f2',
  'leaf-color-bg-subtle': '#f2f4f9',
  'leaf-color-bg-moderate': '#a6abb2',
  'leaf-color-bg-inverse-moderate': '#c4c9cf',
  'leaf-color-bg-strong': '#282c2f',
  'leaf-color-bg-disabled': '#e5e9ed',
  'leaf-color-bg-brand': '#e5f0f8',
  'leaf-color-bg-brand-hover': '#cce2f2',
  'leaf-color-bg-brand-active': '#72aad0',
  'leaf-color-bg-brand-strong': '#0170bc',
  'leaf-color-bg-brand-strong-hover': '#014371',
  'leaf-color-bg-brand-strong-active': '#014371',
  'leaf-color-bg-brand-xstrong': '#0170bc',
  'leaf-color-bg-brand-xstrong-hover': '#014371',
  'leaf-color-bg-brand-xstrong-active': '#014371',
  'leaf-color-bg-success': '#c9edda',
  'leaf-color-bg-success-strong': '#277a47',
  'leaf-color-bg-error': '#f5cccc',
  'leaf-color-bg-error-strong': '#cc0000',
  'leaf-color-bg-warning': '#fcf0d6',
  'leaf-color-bg-warning-strong': '#e49e07',
  'leaf-color-bg-info': '#e5ecf1',
  'leaf-color-bg-info-strong': '#004986',
  'leaf-color-bg-attention': '#E6D6F9',
  'leaf-color-bg-attention-strong': '#7522d9',
  'leaf-color-bg-opacity-transparent': 'rgba( #282c2f,0.0)',
  'leaf-color-bg-opacity-default': 'rgba( #282c2f,0.50)',
  'leaf-color-bg-active': '#282c2f',
  'leaf-color-bg-inverse-active': '#ffffff',
  'leaf-color-content-default': '#282c2f',
  'leaf-color-content-subtle': '#5a636b',
  'leaf-color-content-disabled': '#7f848b',
  'leaf-color-content-knockout': '#ffffff',
  'leaf-color-content-brand': '#0170bc',
  'leaf-color-content-brand-strong': '#014371',
  'leaf-color-content-brand-knockout': '#f2f6f8',
  'leaf-color-content-success': '#277a47',
  'leaf-color-content-success-icon': '#277a47',
  'leaf-color-content-error': '#cc0000',
  'leaf-color-content-error-icon': '#cc0000',
  'leaf-color-content-warning-icon': '#e49e07',
  'leaf-color-content-info-icon': '#004986',
  'leaf-color-content-attention-icon': '#7522d9',
  'leaf-color-content-link': '#0170bc',
  'leaf-color-content-inverse-link': '#ffffff',
  'leaf-color-content-link-hover': '#014371',
  'leaf-color-content-inverse-link-hover': '#f2f6f8',
  'leaf-color-content-link-focus': '#ffffff',
  'leaf-color-content-inverse-link-focus': '#282c2f',
  'leaf-color-content-link-active': '#014371',
  'leaf-color-content-inverse-link-active': '#f2f6f8',
  'leaf-color-content-link-visited': '#7522d9',
  'leaf-color-content-inverse-link-visited': '#f2f8fb',
  'leaf-color-content-link-disabled': '#7f848b',
  'leaf-color-content-inverse-link-disabled': '#eef1f5',
  'leaf-color-border-default': '#a6abb2',
  'leaf-color-border-strong': '#7f848b',
  'leaf-color-border-knockout': '#ffffff',
  'leaf-color-border-disabled': '#c4c9cf',
  'leaf-color-border-brand': '#0170bc',
  'leaf-color-border-brand-subtle': '#cce2f2',
  'leaf-color-border-brand-strong': '#014371',
  'leaf-color-border-success': '#277a47',
  'leaf-color-border-error': '#cc0000',
  'leaf-color-border-warning': '#e49e07',
  'leaf-color-border-info': '#004986',
  'leaf-color-border-attention': '#7522d9',
  'leaf-color-border-transparent': 'rgba( #282c2f,0.0)',
  'leaf-color-border-active-outline': '#282c2f',
  'leaf-border-button-tertiary-default': 'none',
  'leaf-border-button-tertiary-hover': '2px solid #0170bc',
  'leaf-border-button-tertiary-active': '2px solid #0170bc',
  'leaf-border-button-tertiary-disabled': 'none',
  'leaf-font-size-0': 12,
  'leaf-font-size-1': 14,
  'leaf-font-size-2': 16,
  'leaf-font-size-3': 18,
  'leaf-font-size-4': 20,
  'leaf-font-size-5': 24,
  'leaf-font-size-6': 28,
  'leaf-font-size-7': 32,
  'leaf-font-size-8': 40,
  'leaf-font-size-9': 48,
  'leaf-font-size-10': 56,
  'leaf-font-size-11': 64,
  'leaf-font-size-12': 72,
  'leaf-font-size-13': 80,
  'leaf-letter-spacing-0': -1.5,
  'leaf-letter-spacing-1': -1,
  'leaf-letter-spacing-2': -0.5,
  'leaf-letter-spacing-3': 0,
  'leaf-letter-spacing-4': 2,
  'leaf-letter-spacing-5': 0,
  'leaf-paragraph-spacing-0': 0,
  'leaf-text-case-none': 'none',
  'leaf-text-case-uppercase': 'uppercase',
  'leaf-text-decoration-none': 'none',
  'leaf-text-decoration-underline': 'underline',
  'leaf-paragraph-indent-0': 0,
  'leaf-border-radius-small': 4,
  'leaf-border-radius-default': 8,
  'leaf-border-radius-large': 30,
  'leaf-border-radius-round': 900,
  'leaf-border-radius-button': 900,
  'leaf-border-radius-badge': 4,
  'leaf-border-radius-tabs': 4,
  'leaf-border-radius-container': 30,
  'leaf-border-radius-field': 8,
  'leaf-border-radius-field-brand': 8,
  'leaf-border-radius-brand': 8,
  'leaf-border-radius-none': 0,
  'leaf-border-width-none': 0,
  'leaf-border-width-default': 1,
  'leaf-border-width-focus': 2,
  'leaf-border-width-large': 4,
  'leaf-border-width-button-tertiary-outline-focus': 2,
  'leaf-border-width-button-default': 1,
  'leaf-border-width-tab-selected': 2,
  'leaf-border-width-tab-default': 2,
  'leaf-border-style-button-tertiary-outline-focus': 'solid',
  'leaf-border-style-default': 'solid',
  'leaf-shadow-default': {
    shadowOpacity: 1,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
    shadowRadius: 6,
    shadowColor: 'rgba(0,0,0,0.1)'
  },
  'leaf-shadow-button': undefined,
  'leaf-shadow-none': undefined,
  'leaf-shadow-large': {
    shadowOpacity: 1,
    shadowOffset: { width: 0, height: 10 },
    elevation: 4,
    shadowRadius: 12,
    shadowColor: 'rgba(0,0,0,0.2)'
  },
  'leaf-shadow-small': {
    shadowOpacity: 1,
    shadowOffset: { width: 0, height: 1 },
    elevation: 1,
    shadowRadius: 2,
    shadowColor: 'rgba(0,0,0,0.2)'
  },
  'leaf-color-link-bg-active': '#333333',
  'leaf-line-heights-0': 1.25,
  'leaf-line-heights-1': 1.12,
  'leaf-line-heights-2': 1.1400000000000001,
  'leaf-line-heights-3': 1.2,
  'leaf-line-heights-4': 1.3,
  'leaf-line-heights-5': 1.33,
  'leaf-line-heights-6': 1.4000000000000001,
  'leaf-line-heights-7': 1.5,
  'leaf-line-heights-8': 1.43,
  'leaf-line-heights-9': 1.11,
  'leaf-line-heights-10': 1.1300000000000001,
  'leaf-line-heights-11': 1.16,
  'leaf-display-large': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '700',
    fontSize: 80,
    letterSpacing: -1.5,
    lineHeight: 100,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-display-large-mobile': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '700',
    fontSize: 72,
    letterSpacing: -1.5,
    lineHeight: 90,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-display-default': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '700',
    fontSize: 64,
    letterSpacing: -1.5,
    lineHeight: 80,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-display-default-mobile': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '700',
    fontSize: 56,
    letterSpacing: -1,
    lineHeight: 72.8,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-display-small': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '700',
    fontSize: 48,
    letterSpacing: -1,
    lineHeight: 53.76,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-display-small-mobile': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '700',
    fontSize: 40,
    letterSpacing: 0,
    lineHeight: 45.6,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-headline-large': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '700',
    fontSize: 48,
    letterSpacing: -1,
    lineHeight: 53.76,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-headline-large-mobile': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '700',
    fontSize: 32,
    letterSpacing: 0,
    lineHeight: 36.48,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-headline-default': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '700',
    fontSize: 40,
    letterSpacing: 0,
    lineHeight: 45.6,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-headline-default-mobile': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '700',
    fontSize: 32,
    letterSpacing: 0,
    lineHeight: 38.4,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-headline-small': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '700',
    fontSize: 32,
    letterSpacing: 0,
    lineHeight: 38.4,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-headline-small-mobile': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '700',
    fontSize: 28,
    letterSpacing: 0,
    lineHeight: 36.4,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-headline-xsmall': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '700',
    fontSize: 24,
    letterSpacing: 0,
    lineHeight: 28.8,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-headline-xsmall-mobile': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '700',
    fontSize: 24,
    letterSpacing: 0,
    lineHeight: 28.8,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-title-xlarge': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '700',
    fontSize: 32,
    letterSpacing: 0,
    lineHeight: 38.4,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-title-xlarge-mobile': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '700',
    fontSize: 28,
    letterSpacing: 0,
    lineHeight: 36.4,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-title-large': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '700',
    fontSize: 28,
    letterSpacing: 0,
    lineHeight: 36.4,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-title-large-mobile': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '700',
    fontSize: 24,
    letterSpacing: 0,
    lineHeight: 26.88,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-title-default': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '700',
    fontSize: 24,
    letterSpacing: 0,
    lineHeight: 26.88,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-title-default-mobile': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '700',
    fontSize: 18,
    letterSpacing: 0,
    lineHeight: 20.16,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-title-small': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '700',
    fontSize: 16,
    letterSpacing: 0,
    lineHeight: 21.28,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-title-small-mobile': {
    fontFamily: '"Montserrat", sans-serif',
    fontWeight: '700',
    fontSize: 16,
    letterSpacing: 0,
    lineHeight: 21.28,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-label-large': {
    fontFamily: '"Open Sans", sans-serif',
    fontWeight: '600',
    fontSize: 18,
    letterSpacing: 0,
    lineHeight: 23.94,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-label-default': {
    fontFamily: '"Open Sans", sans-serif',
    fontWeight: '600',
    fontSize: 16,
    letterSpacing: 0,
    lineHeight: 21.28,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-label-small': {
    fontFamily: '"Open Sans", sans-serif',
    fontWeight: '600',
    fontSize: 14,
    letterSpacing: 0,
    lineHeight: 19.6,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-body-xlarge': {
    fontFamily: '"Open Sans", sans-serif',
    fontWeight: '400',
    fontSize: 24,
    letterSpacing: 0,
    lineHeight: 36,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-body-xlarge-strong': {
    fontFamily: '"Open Sans", sans-serif',
    fontWeight: '600',
    fontSize: 24,
    letterSpacing: 0,
    lineHeight: 36,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-body-xlarge-link': {
    fontFamily: '"Open Sans", sans-serif',
    fontWeight: '600',
    fontSize: 24,
    letterSpacing: 0,
    lineHeight: 36,
    textTransform: 'none',
    textDecorationLine: 'underline'
  },
  'leaf-body-large': {
    fontFamily: '"Open Sans", sans-serif',
    fontWeight: '400',
    fontSize: 18,
    letterSpacing: 0,
    lineHeight: 27,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-body-large-strong': {
    fontFamily: '"Open Sans", sans-serif',
    fontWeight: '600',
    fontSize: 18,
    letterSpacing: 0,
    lineHeight: 27,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-body-default': {
    fontFamily: '"Open Sans", sans-serif',
    fontWeight: '400',
    fontSize: 16,
    letterSpacing: 0,
    lineHeight: 21.28,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-body-default-strong': {
    fontFamily: '"Open Sans", sans-serif',
    fontWeight: '600',
    fontSize: 16,
    letterSpacing: 0,
    lineHeight: 21.28,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-body-small': {
    fontFamily: '"Open Sans", sans-serif',
    fontWeight: '400',
    fontSize: 14,
    letterSpacing: 0,
    lineHeight: 19.6,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-body-small-strong': {
    fontFamily: '"Open Sans", sans-serif',
    fontWeight: '600',
    fontSize: 14,
    letterSpacing: 0,
    lineHeight: 19.6,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-body-large-link': {
    fontFamily: '"Open Sans", sans-serif',
    fontWeight: '600',
    fontSize: 18,
    letterSpacing: 0,
    lineHeight: 27,
    textTransform: 'none',
    textDecorationLine: 'underline'
  },
  'leaf-body-default-link': {
    fontFamily: '"Open Sans", sans-serif',
    fontWeight: '600',
    fontSize: 16,
    letterSpacing: 0,
    lineHeight: 21.28,
    textTransform: 'none',
    textDecorationLine: 'underline'
  },
  'leaf-body-small-link': {
    fontFamily: '"Open Sans", sans-serif',
    fontWeight: '600',
    fontSize: 14,
    letterSpacing: 0,
    lineHeight: 19.6,
    textTransform: 'none',
    textDecorationLine: 'underline'
  },
  'leaf-meta-large': {
    fontFamily: '"Open Sans", sans-serif',
    fontWeight: '400',
    fontSize: 20,
    letterSpacing: 0,
    lineHeight: 28,
    textTransform: 'uppercase',
    textDecorationLine: 'none'
  },
  'leaf-meta-default': {
    fontFamily: '"Open Sans", sans-serif',
    fontWeight: '400',
    fontSize: 16,
    letterSpacing: 0,
    lineHeight: 21.28,
    textTransform: 'uppercase',
    textDecorationLine: 'none'
  },
  'leaf-meta-default-sentence-case': {
    fontFamily: '"Open Sans", sans-serif',
    fontWeight: '400',
    fontSize: 14,
    letterSpacing: 0,
    lineHeight: 19.6,
    textTransform: 'none',
    textDecorationLine: 'none'
  },
  'leaf-meta-small': {
    fontFamily: '"Open Sans", sans-serif',
    fontWeight: '400',
    fontSize: 12,
    letterSpacing: 0,
    lineHeight: 13.56,
    textTransform: 'uppercase',
    textDecorationLine: 'none'
  },
  'leaf-icon-size-small': 14,
  'leaf-icon-size-default': 16,
  'leaf-icon-size-large': 18,
  'leaf-badge-padding-horizontal': 8,
  'leaf-badge-padding-vertical': 2,
  'leaf-font-families-montserrat': '"Montserrat", sans-serif',
  'leaf-font-families-open-sans': '"Open Sans", sans-serif',
  'leaf-font-weights-montserrat-0': '400',
  'leaf-font-weights-montserrat-1': '600',
  'leaf-font-weights-montserrat-2': '700',
  'leaf-font-weights-open-sans-0': '400',
  'leaf-font-weights-open-sans-1': '600',
  'leaf-font-weights-open-sans-2': '700',
  'leaf-breakpoint-xsm': '375px',
  'leaf-breakpoint-sm': '560px',
  'leaf-breakpoint-md': '768px',
  'leaf-breakpoint-lg': '960px',
  'leaf-breakpoint-xl': '1200px',
  'leaf-breakpoint-xxl': '1400px',
  'leaf-asset-font-montserrat-400-normal': 'Montserrat-Regular',
  'leaf-asset-font-montserrat-600-normal': 'Montserrat-SemiBold',
  'leaf-asset-font-montserrat-700-normal': 'Montserrat-Bold',
  'leaf-asset-font-open-sans-400-normal': 'OpenSans-Regular',
  'leaf-asset-font-open-sans-600-normal': 'OpenSans-SemiBold',
  'leaf-asset-font-open-sans-700-normal': 'OpenSans-Bold'
}